### ISSUE TITLE
load balanced database

### ISSUE THREAD

**Issue by brendankearney** [ampache/ampache#1060]
i am running a 3-way replicated mariadb setup using galera, with HAProxy configured to load balance across two of the nodes.  the device not in the load balanced pool is my nas, which has my media on local disks and runs ampache.  the intention is to have the database instance on the nas available for replication, to avoid the split-brain contention issues, but not serve actual "production" queries or load.

i am looking to understand how i can use the HAProxy VIP in ampache.  it seems i run into issues with session info.  if i point to any individual mariadb instance, i have no issues.  if i point to the VIP, i get pages with missing content and the issue worsens to the point where i get the update.php page and no updates are listed as being necessary.

is there something specific i would need to do, in order to get ampache working with load balanced database instances?

**Comment by Afterster** [comment]
Are you sure this is the correct way for database load balancing?
I think your issue is similar to issues related to caching with varnish for instance.
Only catalog data should be considered 'static' and be cached (or load balanced). User specific data shouldn't be load balanced (neither cached) except if you can isolate the user session and always serve (restrict if caching) from the same server for its session life. My thoughts but I never did such setup.
