### ISSUE TITLE
Error: Defined Path is inside an existing catalog

### ISSUE THREAD

**Issue by matteos1** [ampache/ampache#1075]
for error i inserted a directory in add catalogue that contain music and video.
i want to differenziate music and video but i'm not able to delete catalogue.
and catalogue is not show in list

how can i delete all catalogue?

![2015-12-26](https://cloud.githubusercontent.com/assets/16237822/12006631/ba5bc738-abde-11e5-8b12-a4f1089dc512.png)
![2015-12-26 1](https://cloud.githubusercontent.com/assets/16237822/12006633/ce9ac334-abde-11e5-80f9-04413c395b60.png)

**Comment by Afterster** [comment]
If your catalog is not listed, then it is already delete. You just have to add a new catalog as on your first screenshot ; don't forget to select catalog type to 'local' and enter your media root path.

Otherwise, please use the group for this kind of question and be patient, github repository is about development. I will do some cleanup on issues btw (sorry in advance for any frustration :smile:).

**Comment by matteos1** [comment]
it's already select another catalogue..
the last give same error

**Comment by Afterster** [comment]
I'm sorry but I have real difficulties to understand you, on this issue and on the other one you created. I believe you are not a native English speaker, neither I am. So please don't take it wrong, but I will not be able to help you if you don't provide **explained details** and **logs**.

**Comment by matteos1** [comment]
my directory of music is /media/ampache/music/
media/ampache/ contain also film clip and other
for error i put in catalogue -> local     media/ampache/
i delete from webpage of ampache  media/ampache/ and try to insert /media/ampache/music/
but this error  happen Defined Path is inside an existing catalog

**Comment by Psy-Virus** [comment]
Okay, as I understand it, you have your music within /ampache/music/ and other media like videos in /ampache/. This simply does not work, because /ampache/music/ is within /ampache/. So If you add a catalog with the path "/ampache/music/ first, your can't add "/ampache/" as second catalog, because files within catalogs are added recursively. That means every file in every folder within the given path is parsed and added to the catalog.
The only way you can ad two or more catalogs is if you add two independent paths like:
First catalog: "/ampache/music/"
Second catalog: "/ampache/video/" 

!but not!

First Catalog: "/ampache/"
Second Catalog: "/ampache/music/"
Because the second catalog is within the first catalog.

!or!

First Catalog: "/ampache/music/"
Second Catalog: "/ampache/"
Because the first catalog is within the second catalog

If you try it like the second or third methos you would try to add files or folders that already have been added.

I think this should clear it up. Simply try the first mentioned method and it will work.

If you still receive an error, please take a look in your database and check, if within the tables catalog or catalog_dropbox or catalog_local is any entry. If so, simply delete them and start over again with adding a catalog.

### For the future
Please use our [Google Groups Forum](https://groups.google.com/forum/#!forum/ampache) for discussions and help.

:-)

**Comment by matteos1** [comment]
ok
i think to enter in database and search for data and delete

**Comment by matteos1** [comment]
could you insert a function to delete all data?

**Comment by Psy-Virus** [comment]
I think this will be added one time with #223

But it's also maximum two minutes of work if you do it manually.

Is there anything within any of the catalog* Tables within your (MY)SQL-Database?

Like this:
![isthereanything](https://cloud.githubusercontent.com/assets/6222200/12021496/80eacd32-ad87-11e5-8e27-184ae22bcf93.png)
