### ISSUE TITLE
Embed Player

### ISSUE THREAD

**Issue by Bitart** [ampache/ampache#1112]
Hi,

I am new to Ampache. I have it running right now and connected to admin interface. But, how can someone access an specific "radio station" using e.g: "JW Player". Example: I have an web site and would like to embed a player on it, as an iframe in top header, and reproduce that specific radio station. So, every new visitor will listen to music when visiting that site. 

How to achieve this?

Regards,

**Comment by Afterster** [comment]
Radio station is an external, you should be able to embed it with any web player.
Otherwise if you mean to build a radio station from Ampache catalog, there is several way (using [channels](https://github.com/ampache/ampache/wiki/Channels), shares, linked with [Icecast](https://github.com/ampache/ampache/wiki/Ampache-on-Icecast)...)

Anyway, this is discussion and not an issue, closing it here.
