### ISSUE TITLE
Albums of Same Name but Different Artists Put Together

### ISSUE THREAD

**Issue by goodmorty** [ampache/ampache#1179]
# Environment
- Ampache version: 3.8.3-develop
- Web server + version: Apache 2.2.12
- Server operating system: Ubuntu
- Client operating system: Windows
- Client type:
  - [x] Web
  - [x] Ampache
# Description

I have a couple sets of albums (Angles by dan le sac Vs Scroobius Pip and Angles by The Strokes for example) that share names with each other and when I look for them in the library they only appear under one of the artsits names. The example above appears only under The Shins, even being listed as such on the 'dan le sac Vs Scroobius Pip' Artist page.

**Comment by kuzi-moto** [comment]
The listing is kind of weird sometimes, you might need to include the musicbrainz album ID and/or artist ID for them to appear separately.

**Comment by goodmorty** [comment]
I can't find a way to do that, it only lets me edit the songs individually, otherwise it takes me to the strokes artist edit every time

**Comment by kuzi-moto** [comment]
If the tag doesn't already exist on the files it might not show up (not
entirely sure), so you might need to use tag-editing software instead, then
refresh your catalog.

**Comment by goodmorty** [comment]
also my edit feature rarely seems to work

**Comment by Dual-Boot** [comment]
Edit does not work anymore since 3.8.2.
Maybe it is related to this bug too https://github.com/ampache/ampache/issues/1172

**Comment by wagnered** [comment]
You might try Musicbrainz Picard. It handles a variety of types and has
a version for Windows. It adds the MB ids in batch but allows editing
other tags if needed.


On 03/14/2016 10:44 AM, goodmorty wrote:
> also my edit feature rarely seems to work
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ampache/ampache/issues/1179#issuecomment-196430022>.
> 

-- 
73 From
Ernie D
Federal Way, WA | CN87ug

**Comment by arielelkin** [comment]
This is also an issue for songs that do **not** have a specific album (i.e. songs that do not have an album specified in their metadata). 

The result is that, currently, all songs that do not have an album are considered to be in the same album.

This has pretty bad implications. Suppose some artist has songs that do not have an album. When you browse into the artist, one of the albums shows up as `Unknown (Orphaned)`, and when you open it you get a list of _all_ songs that don't have an album.

**Comment by Phyks** [comment]
@arielelkin Do you have an alternative proposal for orphaned songs?

**Comment by arielelkin** [comment]
@Phyks Sure.

* Browsing by Artist: If I open Artist A's `Unknown` album, it should return a list of _just_ the songs by Artist A that don't have an album.

* Browsing by Album: Don't include the album `Unknown (Orphaned)` among all albums. Because there is no such album :-P

**Comment by Phyks** [comment]
> * Browsing by Artist: If I open Artist A's `Unknown` album, it should
return a list of _just_ the songs by Artist A that don't have an album.

This does not seem very difficult to be done. I will check it. And I
think it makes sense to adopt this behavior.


> * Browsing by Album: Don't include the album `Unknown (Orphaned)`
among all albums. Because there is no such album :-P

I do not fully agree with this. If I understand correctly, we are
talking about the "Albums" view under a given artist view (that is the
table of albums under the artist bio). By default, Ampache displays
artist view in albums view (that is, a table of albums) rather than song
view (a table of all the songs from this artist). Going from Albums view
to Songs view requires one extra click (or changing the default
configuration).

If we adopt the behavior described above, some songs will simply not be
discoverable from the default artist view, as they don't have any
associated album which would be displayed in the table (contrary to
being grouped in the current "unknown album"). I think this would result
in bad user experience, with users not able to find their songs anymore,
or having to do too much clicks. I would need advices from other
developers (@Niols, @Afterster) before considering working on this.


By the way, I am wondering, how often does songs without associated
album is supposed to be happening? I mean, is it something that really
happens often in real life, or is always due to a missing field in
metadata or so?

-- 
Phyks

**Comment by arielelkin** [comment]
>By the way, I am wondering, how often does songs without associated
album is supposed to be happening? I mean, is it something that really
happens often in real life, or is always due to a missing field in
metadata or so?
25% of all my songs don't have an album (bootlegs, downloads from soundcloud or bandcamp, or simply unknown)

> If we adopt the behavior described above, some songs will simply not be
discoverable from the default artist view, as they don't have any
associated album which would be displayed in the table (contrary to
being grouped in the current "unknown album").

I think the problem here is that the UI for the default artist view assumes that each song has an album:

![image](https://cloud.githubusercontent.com/assets/1756909/16967080/a737dfa4-4e07-11e6-85fd-1820ae2dc84d.png)

The UI assumes that an Artist's songs need to be either in his "Albums" or in his "Missing Albums". But this isn't the case for many songs (like the 25% I mention above).

So what I'd suggest for the UI of the Artist's page is: 

* The header beneath "Artist" should say "Songs" instead of "Albums"
* The artist's songs should be listed there, grouped by Albums. Albumless songs should be grouped at the top.

**Comment by Phyks** [comment]
Yes, I think Ampache mostly has in mind managing albums tagged with musicbrainz id and so on.

What you suggest basically boils down to the "show songs list" toggle in artists view, no?

What about having the same view as now, but putting the extra songs in the bottom?

Actually, I am trying to do a rework of the interface (very basic for now) at the moment, and I adopted a "Spotify" artist view style, which would solve it I think.

**Comment by arielelkin** [comment]
>What you suggest basically boils down to the "show songs list" toggle in artists view, no?

Which one? Could you please post a screenshot of it? 

>What about having the same view as now, but putting the extra songs in the bottom?

That'd be absolutely fine, as long as the albumless songs are not under the heading "Album", they should be under a different (or no) heading.

**Comment by Phyks** [comment]
Actions => Show all, under the artist name.

Results is:
![2016-07-22-173408](https://cloud.githubusercontent.com/assets/3856586/17062263/84740b3c-5032-11e6-9e12-6cefb1b06658.png)

Ok for the extra songs in the bottom. This would not be difficult to do in the UI, but may require some changes in Ampache backend =(

**Comment by kuzi-moto** [comment]
> Could it be that current ampache can only distinguish two albums of the same name if they have different MusicBrainz ID? 

@pacija Yes, I believe this is the case.

@goodmorty were you still having issues with this? As mentioned, albums can only be separated by the MBID. It sounds like editing songs from Ampache didn't seem to work well either for you but this is a pretty old issue now so things might have changed.

**Comment by lachlan-00** [comment]
The SQL is to group by album, album_artist and album_mbid

```
GROUP BY `album`.`name`, `album`.`album_artist`,`album`.`mbid`
```

**Comment by lachlan-00** [comment]
This issue should be well and truly fixed now. enable album group and you're grand!
