### ISSUE TITLE
Artist metadata is incorrectly truncated

### ISSUE THREAD

**Issue by flowerysong** [ampache/ampache#1241]
4d3949cf throws away artist name information for (some) collaborations, but does not modify the artist MBID information. When a file is tagged with multiple artists, the mb_artistid is a concatenation of the individual artist MBIDs. If we add an album where Fall Out Boy had ten different collaborations, ten visually indistinguishable Fall Out Boy artists will be added to the database. Before this change there would be ten entries with the correct collaboration info.

I've reverted this change locally since I prefer to keep the collaboration information; if you want to stick with throwing away information, you need to also truncate the mb_artistid when doing so.

**Comment by Afterster** [comment]
I believe you're using 3.8.2.
Current develop branch already took the second approach your suggested with commit 57b38eb952f136aea4d853b206b73ab19ec8d32b.
This cannot be fixed correctly without handling #347. I will close this as it indirectly refer to this issue now.

Good to see you here otherwise ;).

**Comment by flowerysong** [comment]
No, this was against the develop branch.  57b38eb does not address this because it tries to split the MBID on '/', but the MBIDs are concatenated with no separator.
