### ISSUE TITLE
No error message when an album does not exist

### ISSUE THREAD

**Issue by Phyks** [ampache/ampache#1328]
# Environment
- Ampache version: latest develop as of today
- Web server + version:
- Server operating system:
- Client operating system:

- Client type:
  - Web
# Settings

# Description

There is no error message when the user browse to a page corresponding to an album which does not exist.

Typically, `https://SERVER/#albums.php?action=show&album=3873` where album `3873` does not exist. Instead, an empty album is shown, which is misleading.
# Logs

**Comment by lachlan-00** [comment]
Closing! This is now in my branch and will merge into core soon.

I've added a debug message and a visual warning when this happens on an empty page.
![image](https://user-images.githubusercontent.com/1305249/59321848-fd4d2880-8d16-11e9-95db-87c8380925e8.png)

Loading a blank album page is confusing and weird. especially because Ampache falls back to Various as the name when blank.
