### ISSUE TITLE
Since #1239, gettext-plurals aren't recognized anymore

### ISSUE THREAD

**Issue by Psy-Virus** [ampache/ampache#1329]
As I've written [here](https://github.com/ampache/ampache/pull/1239#issuecomment-230351952), the plurals aren't recognized by gettext anymore.

**Comment by Niols** [comment]
And you believe it's related to #1319, right?
@Phyks, could you have broken something in your PR?

**Comment by Psy-Virus** [comment]
Hey @Niols,

Why should it be 1319? There where only changes on some translation keywords/indicators. I think it's #1239 because it's the first change on gettext related stuff since Month (except I missed something).

:-)

**Comment by Phyks** [comment]
@Psy-Virus Sorry, I missed your comment on the MR =(

What do you mean by "the plurals aren't recognized by gettext anymore"? Do you have an example?

I think this may be due to [this function](https://github.com/ampache/ampache/blob/0842e288df74896b1155b5ab90a9733fd0d3cdae/lib/i18n.php#L53).

As you can see, it defaults to returning the plural english string if `n__` function does not exist. Is it the behavior you see?

Else, the underlying function is part of `Gettext` PHP library: https://github.com/oscarotero/Gettext/blob/1a276316c9543a90b3d7f55a89bb4db82e3b5077/src/translator_functions.php#L25

It may be a bug upstream.

I don't have much time to look at it at the moment. If you can provide more infos on this, I may be able to solve it quickly. Else, I will have a look ASAP.

**Comment by Psy-Virus** [comment]
No problem, @Phyks ^^

Okay, everything I can see is: If I set Ampache to default language English (US), everything works fine. But if I set a translation, plurals are printed in English. They're also not gathered by the gather script any more.
I saw it as I created the last general translation update, the existing plurals were marked as obsolete and got deleted from the po's.

Here's an example:
![pluralsdetailindex](https://cloud.githubusercontent.com/assets/6222200/16774052/b3ba39b4-485a-11e6-89e8-64e05c837347.png)

As you can see, translated plurals aren't recognized because they're not in the po's. If I write them manually into the po's, they're recognized.

So the problem seems to be that they are not gathered. But if they exist, they work.

:-)

**Comment by Psy-Virus** [comment]
Could it be, that the local xgettext does not know how to work with nT_ ?

**Comment by Psy-Virus** [comment]
I think I fixed it... please hold the line... :-P

**Comment by Psy-Virus** [comment]
It was the local xgettext. You forgot to specify, that `nT` has arguments.
So the right keyword is `--keyword=nT_:1,2`.

Thanks for the quick responses, guys!

will be fixed with #1330

**Comment by Phyks** [comment]
Oh, sorry for the mistake =(((

Thanks for the fix!
