### ISSUE TITLE
Settings should be copied over from ampache.cfg.dist, instead of setting defaults in install.lib.php

### ISSUE THREAD

**Issue by producerism** [ampache/ampache#1333]
# Environment

 * Ampache version: latest (22eadddd59c769d9987d95a74bb8bd94c05bd8e4)
 * Web server + version: apache2
 * Server operating system: ubuntu 14.04 (running inside docker)
 * Client operating system: windows 10 / firefox

# Description

It seems that the ampache.cfg.php.dist file should be able to be edited so that any modified values carry over during install/setup, and when the ampache.cfg file is created.

For example, if I set `transcode_mp3 = allowed` in the cfg.dist, that should copy over when the real config file is created.

However, instead there appear to be some hard-coded defaults in the install.lib.php file:
https://github.com/ampache/ampache/blob/develop/lib/install.lib.php#L395-404

It seems that this file sets defaults that might not be expected. Also curious why the cfg.dist file is provided at all, since modifications to that file could just be overwritten (unexpectedly) by the install.lib.php code. On top of that, there does not seem to be a way to change the `transcode_mp3` setting within the Ampache Admin UI, and must be done via manually editing the generated ampache.cfg file.

Am I missing something, or is this working as intended?

**Comment by Phyks** [comment]
I am not sure to fully understand the issue here.

1. `ampache.cfg.php.dist` is actually the default configuration file, as far as I know, as you can show in the function `generate_config` which takes it as reference values [here](https://github.com/Phyks/ampache/blob/a50fb430bacffa7092be38513293ecaeaf3a6043/lib/general.lib.php#L263). Settings are then updated by the settings stored by function calls in `install.lib.php`.
2. Then, there is no reason a user should modify the `ampache.cfg.php.dist`.
3. As far as I understood (but I may be wrong, I am a bit tired :), https://github.com/ampache/ampache/blob/develop/lib/install.lib.php#L395-404 is just to install the transcode settings, which will overwrite those of `ampache.cfg.dist.php` and go in `ampache.cfg.php`.
4. Finally, there is no way to edit the settings stored in `ampache.cfg.php` from the UI. None of them can be edited, except at the installation step. This is better stated in another issue, but I cannot come across it at the moment :/

**Comment by producerism** [comment]
The issue is that any modifications to the ampache.cfg.php.dist file should **not** be overwritten by the function calls in install.lib.php. If I manually change the CFG file prior to install, it's unexpected that the install process would negate my changes.

For example, if I set `transcode_flac` to "allowed" instead of "required" it seems that the install.lib.php will just set it back to "required" again. Or am I mistaken?

**Comment by Phyks** [comment]
It should not, it should just overload it. There is a difference between the `.dist` file (default config, overload in install) and the not `.dist` file, which contains the config and is created by the installer.

**Comment by producerism** [comment]
Thanks for the response, I will try again and confirm if the changes in default config are being preserved after the installer.

**Comment by Afterster** [comment]
Thanks for the issue but this is invalid. As Phyks said, .dist file is the default one and shouldn't be modified manually. You should only modify the generated non-dist file.
