### ISSUE TITLE
Catalog permissions

### ISSUE THREAD

**Issue by robinwils** [ampache/ampache#1378]
# Environment
- Ampache version: develop
- Web server + version: apache 2.4.7
- Server operating system: 14.04.1-Ubuntu
- Client operating system: 14.04.1-Ubuntu
# Settings

I just installed a local ampache to test on develop, basic settings, allowed transcoding with libav and user uploads
# Description

Is there a way to modify or create a catalog with specific permissions ? I would like to be able to make a catalog in which the music is not modifiable by anyone and another that can be by Catalog Managers for example

**Comment by Phyks** [comment]
I don't think so, but this is not a 100% sure answer.

@Niols do you have any extra infos on this?

**Comment by Niols** [comment]
Hi. I don't know if this is possible.
Of course, the Unix permissions can prevent users to write in certain catalogs (this is what I'm doing: the web user isn't the same as the user owning the music).

Sorry, I can't say much more :/

**Comment by wagnered** [comment]
Bump (does that work here?)
I think this feature would make Ampache more attractive.  For example what about a catalog rated G, PG, or R that parents want to create for for their childrenwant to create for their children

**Comment by lachlan-00** [comment]
Seems to be a pretty common request and I think this is one thing I can do without much effort.

The ratings filter I added doesn't completely cover this type of situation either.

I'm thinking an option like Catalog_disable called catalog_filter and some UI to allow admins to add/remove users from a catalog

**Comment by wagnered** [comment]
LSorry about that.

As i can't edit or delete the comment on line I'll finish the comment:
I think this feature would make Ampache much more attractive.  For example what about a catalog rated G, PG, or R that parents want to create for their children.  With robust Role Based Access Control (RBAC) a catalog could be created/managed by whoever has the role and permission to do so and can be accessed by whoever has the permission to do so.

If anyone gets the motivation to "refurbish" Ampache, I suggest a RBAC package is included.  There are many on the packagist.org website for composer to install.

I installed spatie/laravel-permissions in the Laravel branch. Very powerful!  ( ; ' >



—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

-------- Original message --------
Subject: Re: [ampache/ampache] Catalog permissions (#1378)

**Comment by mitchray** [comment]
I think this can be closed now that [Catalog Filters](https://github.com/ampache/ampache/wiki/catalog-filters) are in, reopen if still relevant
