### ISSUE TITLE
Watch movies in a Ampache/Ampache-compatible client

### ISSUE THREAD

**Issue by bergercookie** [ampache/ampache#1382]
I have successfully managed to play audio files over both Power Apache, and Subsonic client applications on android. I have also successfully uploaded movie files in the Apache server.

However both Ampache browser program as well as both aforementioned players can't seem to play movie files.
Is there any client application that can read movie files situated in the Ampache server?

Thanks in advance,

**Comment by wagnered** [comment]
These kind of questions should be asked in the Ampache Google Group at
https://groups.google.com/forum/#!forum/ampache.

You really don't give much information.

What system are you running?

What version of Ampache: Release or develop version?

Was a catalog of the videos created?

What video players do you have on your system.

What is the format of the videos(mp4, mkv, etc?)

After logging in to the Ampache server, go to Home->Movies to see the
list of videos in the catalog you should have created.

What happens when you click on play for the selected movie?

On the upper right there is a drop down list to select type of player.

Web player should be able to play mp4s in all major internet browsers.

Other types of videos might need transcoding to something that Web
player can play. 

If you are streaming videos to your local system, set the drop-down list
to stream. One of the video players you have installed on your system
should be able to play the streamed video.

73 From  AA1AD
Ernie D
Federal Way, WA | CN87ug

**Comment by AshotN** [comment]
Movies are out of scope for Ampache.

**Comment by wagnered** [comment]
Since when?

**Comment by AshotN** [comment]
I don't see what movies have to do with music. Ampache doesn't need to do everything. If you guys disagree, feel free to reopen the issue.

**Comment by kuzi-moto** [comment]
I'm not sure that Ampache should be used for movies, but it already does support videos so theoretically I would think that movies do work. Perhaps the OP did not create a 'video' catalog?

I do think there is a case to be made for supporting music videos and I could imagine some really neat features around that.

**Comment by lachlan-00** [comment]
The API can list and retrieve videos. I've not actually played one from there but it seems like it would work as long as someone did the work for it in their client

**Comment by wagnered** [comment]
First off this issue does not need to be reopened. Ampache does (in the past did for sure) play movies, tv shows, etc quite well.

> Movies are out of scope for Ampache

I'm sure @Afterster, @vollmerk ,  et al who took part in Ampache's creation and early development  don't believe that, or they most likely would not have developed Ampache into a multimedia platform.  In spite of the Ampache byline, motto or what ever you want to call it, I've considered Ampache a **multimedia** platform ever since my initial involvement with it 6+ years ago..

I'm sure there is a "silent plurality" who use the multimedia platform for tv shows, etc,.  They are not insanely compulsive and demanding about doing searches as the audiophiles are.

As a few issues reveal, there were feature requests, but as their requests were largely ignored, they remain the silent plurality.

Perhaps podcast support should also be dropped. (I say tongue-in-cheek)

**Comment by AshotN** [comment]
Ampache needs to define a scope of operation, it can't be expected to handle everything.
