### ISSUE TITLE
Ampache's subsonic api authentication protocol is depricated

### ISSUE THREAD

**Issue by mrpurplenz** [ampache/ampache#1389]
# Environment
- Ampache version: 3.8.2-Develop
- Web server + version: Apache/2.4.7 (Ubuntu)
- Server operating system: Ubuntu 14.04
- Client operating system: Ubuntu 16.04

- Client type:
  - SubSonic (mopidy-subsonic via py-sonic) py-sonic version 0.6.1
# Description

I have subsonic clients that work fine on my ampache build. However, When I try to connect with mopidy-subsonic, or more specifically with its subsonic connection library "py-sonic" the connection fails with the following error:
`libsonic.errors.VersionError: Incompatible Subsonic REST protocol version. Server must upgrade.`

I was hoping this issue would be solved by the addition of the `legacyAuth` option in py-sonic. However I guess the ampache version is just too old.

See here for a description from py-sonics end: [https://github.com/crustymonkey/py-sonic/issues/17](https://github.com/crustymonkey/py-sonic/issues/17)

**Comment by Phyks** [comment]
Ampache's Subsonic API implementation is based upon [v1.11.0](https://github.com/ampache/ampache/blob/develop/lib/class/subsonic_xml_data.class.php#L32). That is a quite old version which only support legacy auth, passing hash of password. See [this API doc](http://www.subsonic.org/pages/api.jsp) for extra infos.

So two things here:

* Yes, Ampache should definitely upgrade Subsonic API version to the latest one, this is really starting to be blocking and will only get worse as we will keep diverging from up to date Subsonic API. However, we are very few active maintainers at the moment, and we actively seek community support on such features :/ We are mostly focusing on fixing bugs at the moment. Also https://github.com/ampache/ampache/issues/1352#issuecomment-236358951 is a related issue.

* On the py-sonics (or whatever client) side, they should state which Subsonic version they support. When a user is to use a Subsonic client, at the moment they should check the client supports legacy API version (< 1.13.0 typically). As far as I understand the py-sonics issue, they implemented a legacy auth in their client.

> Technically, the legacyAuth is actually 1.13.0 and earlier.

Then, AFAIK, it should work with Ampache. I know clients working fine with Subsonic in Ampache (I'm actually using Dsub quite a lot). So I would tend to think this is an issue in this lib, rather than Ampache.

**Comment by mrpurplenz** [comment]
mopidy-subsonic uses pysonic. The legacyAuth option can now allow authentication.
In order to get authentication with pysonic and mopidy pysonic one needs to:
upgrade pysonic:
`pip install --upgrade setuptools pip
sudo pip install --upgrade py-sonic`
sudo pip install --upgrade mopidy-subsonic
Then one can either wait for the lagacyAuth option to be implimented in mopidy-subsonic plugin or one can (as I did - not too hard) make the edits required to the files themeselves. They are described at [https://github.com/rattboi/mopidy-subsonic/pull/24/files](https://github.com/rattboi/mopidy-subsonic/pull/24/files)

Unfortunately, however, even once ampache and pysonic are talking, ampache doesnt support "playlists as lists" which causes mopidy to crash out. I'll open a new issue for that issue. Then I'll have a go at adding that functionality and making a pull request as per Phyks comment [https://github.com/ampache/ampache/issues/1352#issuecomment-236358951](https://github.com/ampache/ampache/issues/1352#issuecomment-236358951)

**Comment by Phyks** [comment]
Hmm, what is "playlists as lists"? I cannot find any reference of it through Subsonic API doc.

**Comment by mrpurplenz** [comment]
Sorry, That error message `does not implement playlists.as_list().`  is from mopidy. Given that its not related to subsonic _per se_ I'd have to guess it was an issue with the mopidy-subsonic/pysonic plugin. My bad.

**Comment by lachlan-00** [comment]
i've started updating the subsonic api in pull #1965 

Right now it's just supporting token auth with user + apikey but that's a start!
