### ISSUE TITLE
gui toolbar bug (possible long translated text)

### ISSUE THREAD

**Issue by ftoledo** [ampache/ampache#1461]
Ampache (git master)
The top toolbar text icons are overlaped (at least in spanish).
Maybe wrap long text can solve the issue. 

![dock sud bbs music puro rock inicio](https://cloud.githubusercontent.com/assets/95441/21756974/df8a0544-d606-11e6-9271-7967c086d002.png)

**Comment by ftoledo** [comment]
I suggest to modify translations to prevent this:

Listas de reproducción -> Listas
Nube de Eiquetas -> Etiquetas

example image:
![dock sud bbs music puro rock inicio](https://user-images.githubusercontent.com/95441/36400047-66445026-15ad-11e8-9c17-27f4f3a37d1a.png)

**Comment by ftoledo** [comment]
```diff
Author: Fernando Toledo <ragnarok@docksud.com.ar>
Date:   Mon Feb 19 19:53:40 2018 -0300

    fix toolbar labels due long translation text

diff --git a/locale/es_ES/LC_MESSAGES/messages.po b/locale/es_ES/LC_MESSAGES/messages.po
index 01be739..2d1b6be 100644
--- a/locale/es_ES/LC_MESSAGES/messages.po
+++ b/locale/es_ES/LC_MESSAGES/messages.po
@@ -9010,3 +9010,9 @@ msgstr "Contraseña de Amazon"
 #: Database preference table id 168
 msgid "Amazon associate tag"
 msgstr "Tag asociado a Amazon"
+
+msgid "Playlists-Header"
+msgstr "Listas"
+
+msgid "Tag Cloud-Header"
+msgstr "Etiquetas"
diff --git a/templates/header.inc.php b/templates/header.inc.php
index 1922608..bc77450 100644
--- a/templates/header.inc.php
+++ b/templates/header.inc.php
@@ -400,13 +400,13 @@ $_SESSION['login'] = false;
                 <div id="topmenu_item">
                     <a href="<?php echo $web_path ?>/browse.php?action=playlist">
                         <img src="<?php echo $web_path ?>/images/topmenu-playlist.png" />
-                        <span><?php echo T_('Playlists') ?></span>
+                        <span><?php echo T_('Playlists-Header') ?></span>
                     </a>
                 </div>
                 <div id="topmenu_item">
                     <a href="<?php echo $web_path ?>/browse.php?action=tag">
                         <img src="<?php echo $web_path ?>/images/topmenu-tagcloud.png" />
-                        <span><?php echo T_('Tag Cloud') ?></span>
+                        <span><?php echo T_('Tag Cloud-Header') ?></span>
                     </a>
                 </div>
                 <?php if (AmpConfig::get('userflags') && Access::check('interface', '25')) {
```

**Comment by wagnered** [comment]
@ftoledo 
Thanks for bringing this to my attention.

I think this is more of an HTML/CSS problem rather than a translation problem. My reasoning is that the translation into other languages may render a longer line of text. 

I would like to hear from @Psy-Virus who does the translations. 

I did a quick example with the Firefox web developer. The following shows how it can be done with HTML5"

![image](https://user-images.githubusercontent.com/6115438/36401427-451f8fd0-158c-11e8-81a4-eb4b78a95e70.png)

**Comment by Psy-Virus** [comment]
But what I can say on the first look is: Nearly everything translation-text related can be changed via [Transifex](https://www.transifex.com/ampache/ampache). You can search for strings, you don't like or where you think you have a better opinion.
I think too that we should keep those translations as short as possible. And add a CSS work around to handle cases where it simply is not possible to put it in a short form.

Looking into it now. Maybe I find a compromise for readability and keeping the site style.

12 days delay, I'm really sorry...

**Comment by Psy-Virus** [comment]
All right, I looked into the headers.inc.php. The code style is stuff for nightmares. I'll clean it up and fix the alignment or style of the buttons after I got some coffee and sleep... Not necessary in this order. 😋

**Comment by Psy-Virus** [comment]
I've two solutions:

1:
![ampache top menu](https://user-images.githubusercontent.com/6222200/36946815-2cd33aa8-1fc3-11e8-8c0c-63c172ce5dd7.PNG)
2:
![ampache top menu2](https://user-images.githubusercontent.com/6222200/36946843-9aedea24-1fc3-11e8-9ea6-8359c63f88b7.PNG)

And of course, what @wagnered suggested.

In the first solution, the distance between the symbols are not equal and depending on the translation text.
In the second solution, we have a cut off text. In this case I'd implement a tool tip, so the full text is shown when you hover your cursor over it.

**Comment by wagnered** [comment]
Which would be less of a problem on a small screen? I'm guessing the second example would. There have been a number of complaints about Ampache on small screen clients. I guess Ampache and bootstrap2(?) don't support  "responsive mobile first design" very well. That may be why many users prefer using a Subsonic Client with Ampache.

I would like to leave this as a future enhancement for V4.0.  I've been using [w3-CSS](https://www.w3schools.com/w3css/default.asp) which makes it easy for me to get a rough layout while building the logic.  It does have responsive mobile first design built into the CSS.

My problem is that I have very little "visual organizational" ability which makes even an easier css difficult for me to fine tune. I have learned several variations of jQuery faster than css.

So, @Psy-Virus I'm making you the "Opportunity of a lifetime" :smile: . If you have the time, of course, I would like to have your css/translation talents assisting on the Ampache/Laravel Next Generation.

**Comment by ftoledo** [comment]
"Listas de reproducción" is too large in spanish (i do not know in another language).
If you wrap the text, you must warranty to keep aligned icons .
I think that @Psy-Virus solutions 1 and 2 are fine.

**Comment by Psy-Virus** [comment]
> @wagnered "Which would be less of a problem on a small screen? I'm guessing the second example would."

> @ftoledo "I think that @Psy-Virus solutions 1 and 2 are fine."

Alright then we go with the second. ^^

> I guess Ampache and bootstrap2(?) don't support "responsive mobile first design" very well.

I would say: There isn't any mobile (friendly) design. And if we want to make it mobile friendly, we probably need to rewrite everything and make it scalable and responsive. And maybe declare a minimum resolution.
On a smart phone for example, the nav buttons are not pressable without zooming.
So we probably need a dedicated design for mobiles or find a compromise for desktop and mobile that doesn't add too much complexity to any of them.
Maybe a more or less layered design, where you start on a selection menu and can select for example to go to artists, open the search bar or the settings in something like a tile design.

Ampache is quite complex when it comes to the options you have. To make it mobile friendly, we have to consolidate nearly everything. This also would be a good thing for desktop use.

In my opinion a general navigation bar is more or less obsolete these days. Most applications are going the way to a category based menu structure. Like I said before. A menu point/category for showing artists, albums, songs, genres(?), switchable on the site you get navigated to. For example on the top. So dedicated top nav menus on each category. And that should be standard. we should completely get rid of the old obsolete design and options. We then also need a better way for themes. One general perfect design, users can build their own designs with.
We now have a basic design (`templates/base.css`) - and a basic theme (`themes/reborn/templates/*.css`) that overrides/adds rules from/to the basic design on the client side. This should be done on the server side, before it get's send to the client, to minimize traffic and other resource usage.
Like a template theme/design that can be changed by users and replaces the base/original theme/design.

Just a thought: If we are going through this, we also should get rid of the support for old browsers like the Internet Explorer. And only go for the latest stuff. Refusing updates is something that should not be supported in my opinion.

Sorry for the partly redundant text. 😁

> @wagnered "So, @Psy-Virus I'm making you the "Opportunity of a lifetime" 😄"

You wrote "giving you the greatest headache of a lifetime" wrong. 😜 
Just kidding.

> @wagnered "My problem is that I have very little "visual organizational" ability which makes even an easier css difficult for me to fine tune. I have learned several variations of jQuery faster than css."

Yepp, CSS is stubborn in some cases. Before all if you want a cross browser compatibility.

----

So the question is: Is Ampache/laravel on the latest state or should I stick on your fork? I'm asking because it's better to work on a, more or less, live copy of your work to minimize conflicts and other problems we probably will encounter.

This will be a time eating task. Good thing, we don't have a deadline. 😆

**Comment by wagnered** [comment]
I recloned my fork and updated it from my local repository.

I was thinking that we use my fork. as I would like to keep PR's and comments separate from ampache/ampache hopefully, less confusing.  Github made it easier to push the changes back to ampache/ampache from my fork. I had to re-add you to the collaborator list. :smile_cat: 

Also, I can start a project to actually keep track of tasks, if not deadlines.

w3-css is fantastic :open_mouth:  in my mind as I can quickly layout the pages as I convert the old layouts to be blade engine compatible. There are interesting affects without javascript as you will see.

Anyway, I can go into more detail on my fork.
