### ISSUE TITLE
how install ampache in ubuntu 16.04?

### ISSUE THREAD

**Issue by Mokhless** [ampache/ampache#1474]

**Comment by paul70078** [comment]
You can install a slightly older version by open your terminal typing
`sudo apt-get install ampache`
This should install ampache and all requierements. If you want to install the newest version take a look at the [installation wiki page](https://github.com/ampache/ampache/wiki/Installation)

**Comment by Mokhless** [comment]
it's not work with this installation , white page in browser

**Comment by wagnered** [comment]
From your description, it appears that composer wasn't installed/run properly. It should be run inside the Ampache folder.

You really need to give more information.  IF you installed ampache-3.8.2_all.zip by using the method that paul70087 described above with the apt-get command, you might want to run `composer update` inside the Ampache folder.

Also, I suggest going to https://github.com/ampache/ampache and downloading/installing the zip file: This is the latest development version (3.8.2) but many bugs have been fixed since the release version. Click on the green button on the upper right side of the page.

**Comment by Mokhless** [comment]
what is the default username and password for server?

**Comment by wagnered** [comment]
There is no default username or password. It has to be set when you go
through the setup.  The first page should ask you what language to use,
after that, there will be more questions about the root user/PW of the
mysql database, then it should ask you to enter an Ampache username and
password.


If you get a white page, it usually means that php got an error and that
usually indicates that the full installation isn't complete or it's not
correct.

You need to give us more information:

What version of PHP are you using?

What version of MySQL?

What version of Ampache: 3.82 release or 3.83-develop?

What webserver are you using NGinx, lighttpd, Apache, or IIS, or other?

Also you don't need to CC: me as I will get all messages to this forum
anyway.

73 From  AA1AD
Ernie D
Federal Way, WA | CN87ug

**Comment by Mokhless** [comment]
thanks for all , it's work

**Comment by Mokhless** [comment]
1/ Move the folder ampache to /var/www/html
2/ # sudo chown -R www-data:www-data ampache
3/ start service apache2
