### ISSUE TITLE
how can  set a  catalog to specific user ?

### ISSUE THREAD

**Issue by Mokhless** [ampache/ampache#1494]
# Environment

 * Ampache version: 3.8.2
 * Web server + version: Apache 2.4
 * Server operating system: Ubuntu server 16.04 LTS

 * Client type:
   - Web
   - Ampache
   - SubSonic
   - Plex
   - DAAP
   - UPnP
   - WebDAV

# Description

how can set a  catalog to specific user ?

**Comment by uribes78** [comment]
I have the same question. I have tried changing the User group, but I see no change. Please help us!

**Comment by uribes78** [comment]
One more think, Is it possible to add to a user a filter, and that filter is always applied every time is logged in? example, to set a filter the use X catalog but with Y artist only, and every search will have that filter!

hope this can be done! thanks

**Comment by wagnered** [comment]
@Mokhless and @uribes78,

Someone with more knowledge of Ampache can correct me on this, but I'm
pretty sure the answer is "No".  Although I see evidence  that any user
_uploading_ files can automatically create their own catalog. The
problem with this is that the user would still be able see multimedia
from all system catalogs, but not other users catalogs unless sharing is
permitted.  This depends on the upload settings in admin->System.

I will look for a possible work around. It all depends on how Ampache
handles the uploads.

73 From  AA1AD
Ernie D
Federal Way, WA | CN87ug

**Comment by wagnered** [comment]
There is a way for the user-upload capability for use as requested.

Your installation must be upgraded to 3.8.3-develop and apply the patch from https://github.com/ampache/ampache/pull/1527.patch to fix an upload problem.

- Create a users catalog
- Enable Upload settings in Admin->System.
- In settings, set upload folder to the users catalog.
- Have  users upload a music/audio file to create a user-catalog in the database.
- Sub-folders will be created and named for the user in the users folder.
- The Admin/Catalog manager can move user-specific files into each of the user folders.
- Then do an "Add" on the catalog to include the files in the catalog. 

The users can see their files in Home->Recent->Uploads.

**Comment by wagnered** [comment]
An addendum to a work around:  Create a new catalog for the uploaded
files, but disable it: The ability to disable must be set in
ampache.cfg.php. The new location will remain empty unless users upload
files. In system configuration set the upload destination to the name of
the new catalog, and enable "create a subdirectory per user".

When a user adds a file, It will only be seen by that user because the
catalog is disabled and won't be scanned during normal use.

I will be looking into the  feasibility of allowing the catalog manager
the ability to manually add files to individual user subfolders, run an
"add/clean/update" and have them added as uploads for the respective
user. Hopefully, it won't be too complex.

73 From  AA1AD
Ernie D
Federal Way, WA | CN87ug

**Comment by lachlan-00** [comment]
I'm going to work on this here.
https://github.com/ampache/ampache/tree/catalog_filter

**Comment by lachlan-00** [comment]
@uribes78 there were some filters added into the ui to allow you to filter out artists/albums you don't like but i'll be working on filtering full catalogs this week
https://github.com/ampache/ampache/issues/308

**Comment by mitchray** [comment]
Catalogs can be private as of 5.0 so I think this can be closed now
