### ISSUE TITLE
Itunnorm content displayed as id3tag comment in ampache

### ISSUE THREAD

**Issue by ghost** [ampache/ampache#1518]
Hello,  (this post concerns ampache use of id3tag comment for mp3 files)

I am using ampache v3.8.3 with php5.6 and apache2.2.

The itunnorm content is being displayed instead of the id3 tag comment content. This happens for the comment field in ampache for those mp3 files that seem to have been encoded by itunes.

The mp3 files that do not have itunnorm in them work fine. they display correct comment content.

but those with itunnorm display like this:

00000000 00000210 000005ad 00000000010d3b43 00000000 0030d53a 00000000 00000000 00000000 00000000 00000000 00000000

This is either itunnorm or itunsmbp but it is not id3tag comment as it should be.

Why does ampache display itunnorm/itunsmbp instead of comment as comment and how do i change it so that ampache uses the id3tag comment field rather than itunnorm/itunsmbp field so that the comments for the mp3 files can be searched in advanced search in ampache.

I use kid3. I have id3tag v2.4

Thanks in advance for reply

Mattias

The mp3files are according to kid3 UTF8 encoded. I am using synology dsm.

Do I have to remove itunsmbp and what are the consequences of removing it. Will the audio not be able to play consequtively many audios after each other any more ?

**Comment by wagnered** [comment]
Hello @Matterik

As the ID3V2 tag spec is informal, and allows multiple comment tags. 
Apple went wild and used comment tags to define some mp4/AAC
attributes.  Again, the problem seems to be  that Ampache doesn't expect
to see more than one COMM (Comment) tag and the Apple software seems to
have inserted their comment before all others.

If KID3 or id3tag cannot remove them, I think mp3tag (free download) can
remove the unnecessary comment tags.   It is a Windowz app but can run
on  Linux with PlayonLinux

73 From  AA1AD
Ernie D
Federal Way, WA | CN87ug
