### ISSUE TITLE
Ampache 3.8.3 subdirectory installation is redirecting to root

### ISSUE THREAD

**Issue by GaneshKandu** [ampache/ampache#1584]
# Environment

 * Ampache version: v3.8.3  ```ampache-3.8.3_all.zip```
 * Web server + version: Apache/2.2.31
 * Server operating system: Linux CentOS
 * Client operating system: Windows

 * Client type:
   - Web

# Settings

ampache.cfg.php created by Ampache 3.8.3 itself during installation

[ampache.cfg.php.txt](https://github.com/ampache/ampache/files/1202332/ampache.cfg.php.txt)

# Description

i jsut made fresh installation of Ampache 3.8.3 on my machine but its redirecting to root where as i am installing in sub directory

**Comment by wagnered** [comment]
Hello @GaneshKandu ,

I guess I don't quite understand.  Redirecting when accessing from localhost/intranet IP/internet?  
In your config file, it looks like web_path is set to "" and local_web_path is comment out.

Since I don't have very much information I will offer my thoughts on the issue:

Did this problem exist after adding your patch and filling in the "web path" while installing? 

Where is "root" compared to Apache's Document root?   For example, my Apache document root is /home/ernie/htdocs/Ampache. I've installed it in the same folder as the Apache document root and have no problem.

If you  don't install it in Apache's Doc root, then Apache may need re-rewrite rules enable.

**Comment by GaneshKandu** [comment]
Hello @wagnered 

the issue was ampache installer sets ```web_path``` empty even its installed in subdirectory
that's why its redirect to root ie. https://localhost/login.php where as it should be https://localhost/dir/login.php.
during installation ampache installer doesn't post ```web_path``` in parameter because ```web_path``` input tag was missed place

if i install ampache in root it run fine with no issue
this problem doesn't exist after filling relative url in ```web_path``` after installed

**Comment by GaneshKandu** [comment]
Thanks @wagnered 👍
