### ISSUE TITLE
Tags not deleted on songs from catalags created before update

### ISSUE THREAD

**Issue by manuelglez86** [ampache/ampache#1630]
# Environment

 * Ampache version:3.8.4
 * Web server + version:
 * Server operating system: ubuntu 14
 * Client operating system: windows

 * Client type:
   - Web
 

# Settings

# Description

[
I think I find a bug on 3.8.4 develop.

I recently update from 3.8.2 and i have created some catalogs with 3.8.2, so now on 3.8.4 if I deleted a tag of a song from a catalog created with 3.8.2 the tag reappears if i delete the directly from the mp3 file (on the id3 tag) and after that apply verify catalog the original tag is still present, According to the logs the tag is "delete" but thats not true. This behavior is not present on catalogs created with 3.8.4.

Using the log i track th error to [here](https://github.com/ampache/ampache/blob/00b066f903cc892f9258274d6facbfba9f901bd5/lib/class/tag.class.php#L633) and [here](https://github.com/ampache/ampache/blob/00b066f903cc892f9258274d6facbfba9f901bd5/lib/class/tag.class.php#L711)

eareasing the false from [this line](https://github.com/ampache/ampache/blob/00b066f903cc892f9258274d6facbfba9f901bd5/lib/class/tag.class.php#L633) apparently helps but maybe it affect other things, I really dont understand what are you trying to do with "remove tag maps for current user".

Thanks for your help.

# Logs

**Comment by wagnered** [comment]
@manuelglez86 

The wiki upgrade directions don't really work as changes to tables/columns can be introduced at any time. 

Because there have been many changes to both code and the database tables since Ampache release 3.8.2, I suggest you do a fresh install of 3.8.4-develop by removing config/ampache.cfg.php.  

Yes, that means overwriting the current database/catalogs to install the new tables.

Even ampache.cfg.php has changed since the 3.8.2 release. Writing it back to the config folder as suggested in the wiki would prevent new configuration features from being realized.

**Comment by manuelglez86** [comment]
The ampache.cfg was updated "automatically" when uptade to 3.8.4, so your suggestion is that  I delete and recreate the catalogs again?

**Comment by wagnered** [comment]
First, you could try deleting and then recreating the old catalog.  Even if it works, there may still be problems when trying to use new features that have been added. 

When you installed 3.8.4-develop, you should have enabled Ampache to overwrite the catalog to install/modify any new tables. The fact that you have old catalogs indicates that this was not done. So I will suggest that you do a new install and allow Ampache to overwrite the existing database,

**Comment by stebe** [comment]
I would like to solve similar issues I'm having with my install that has been in place for several years. How do I preserve all the ratings and other statistics that have been generated when I recreate everything?

**Comment by wagnered** [comment]
@stebe 

For ratings the `mysqldump/mysqlimport pair` could be used in a CLI.:

`mysqldump ampache rating -u [username] -p  > rating.sql`

The problem here is that the rating is correlated to the user id. This means that the users would have to be added to the new database in the same order as the old(relative to the 'id' column).

I  believe that statistics are based on the tables:
user_activity, user_flag, user_follower, user_shout

Mysqlimport would be used to import the ratings into the new database.

I suggest that you backup the entire old database as described in the wiki on updating to revert back to 3.8.2 release  if something goes wrong.

**Comment by wagnered** [comment]
@manuelglez86 , @stebe 

The wiki on Ampache update was added early before there were thoughts about needing to add changes to the config file and before making changes to the tables.

The Larvel based version which is in early development, will take into consideration, configuration changes and migration of table changes. Rolling updates should be a nice improvement. 😄
