### ISSUE TITLE
i cant login log said this first time i do this what is this meaning

### ISSUE THREAD

**Issue by JohanvdS** [ampache/ampache#1637]
2017-11-26 12:13:26 [-1] (i18n) -> Setting locale to en_US.UTF-8 
2017-11-26 12:13:26 [-1] (i18n) -> gettext is native 
2017-11-26 12:13:26 [-1] (Login) -> admin attempted to login and failed 
2017-11-26 12:13:30 [-1] (session) -> jl2tl2f31mo44lohkcio3a23v5 has been extended to Sun# Environment

 * Ampache version: Ampache 3.6-alpha6+FUTURE
 * Web server + apache
 * Server operating system: ubuntu 16.04
 * Client operating system: same

**Comment by wagnered** [comment]
I suggest you go to the [Ampache's release page](https://github.com/ampache/ampache/releases) and get the latest release (3.8.3).

Many fixes and features have been added over the last 3+ years since 3.6-alpha has been released. And I am considering the release of 3.8.4-develop.

For your above question, the only suggestion I have is to make sure that the gettext library is installed on your system. 

 If you decide to upgrade, see [The Ampache repository](https://github.com/ampache/ampache/tree/develop) for installation requirements.

**Comment by wagnered** [comment]
Also. ignore the Upgrade information. There have been too many changes to the database: A full installation need to be done.

**Comment by wagnered** [comment]
@JohanvdS 

Dd this solve your problem?  If not you can reopen this issue if the problem continues.
