### ISSUE TITLE
Missing string for translations

### ISSUE THREAD

**Issue by prschopf** [ampache/ampache#1641]
I have translated Ampache to Portuguese-Brazil using Transifex but there is 1 string which Im not able to translate it.

String is "Enable url rewriting" and its in "admin/server config/streaming". May the person in charge of that add this string in Transifex for translations, please?

**Comment by Psy-Virus** [comment]
I'll check that soon, thank you

:-)

**Comment by prschopf** [comment]
Will it be available in Transifex as well?

**Comment by Psy-Virus** [comment]
> After this is merged the proper translation string will also be available on Transifex.

Yepp, that's what I meant with this sentence in my PR ;-)
I guess you didn't take a look. :-D

After it is merged (what depends on when @wagnered finds time), Transifex will pull it from Github and provide the updates. This could also take a while. I don't know actually when Transifex has it's pull rhythm, so I unfortunately can't tell you, when exactly it will be there. And I don't want to update it manually, because sometimes Transifex reacts weird if something interferes with it's update processes.

So I guess, get some coffee and cake and take a seat in the meantime.

:-)
