### ISSUE TITLE
[Resolved]How to: Create playlist

### ISSUE THREAD

**Issue by Cypoun** [ampache/ampache#1692]
Hello,
I'm not sure if there is an issue or just me..
I would like to know if we can create playlist. When I say playlist I mean a list of songs (.mp3) that can be created by a user and played by one or many whenever they want. Like Spotify or any mp3 player, you know ?

Thanks,

**Comment by wagnered** [comment]
@Cypoun 

That's a secret that we charge a lot of money for  :smiley: 

Actually:

When you hold  the cursor over a song, artist, or album, some icons will appear.  The icon that has the tooltip that reads "Add to existing playlist", if clicked, will display a dialog that displays "Add  to new playlist".

I will be changing the tooltip to say "Add to **new** or existing playlist" and will push the change to the develop branch ASAP.

I'm not familiar with spotify.

To switch between listening on the web browser, and a local audio player, it is necessary to select between "streaming" and "web player" on the dropdown list in the upper right of almost any web page.

Streaming might have to be enabled on the Admin->Server Config->Options page.

Also, depending on the music files (mp3, flaac, mp4a, etc, transcoding probably has to be set in config/ampache.cfg.php because the web player only plays mp3 and ogg files.

**Comment by Cypoun** [comment]
Oh thank you @wagnered ! I feel so stupid... As you said it is written "Add to existing", that's why I was confused.
I guess it's solved ! :)
