### ISSUE TITLE
Can't play songs with clementine using the subsonic API

### ISSUE THREAD

**Issue by Gotos** [ampache/ampache#1704]
# Environment

 * Ampache version: current git master and develop branch
 * Web server + version: apache2.4.18
 * Server operating system: Ubuntu 16.04
 * Client operating system: Gentoo

 * Client type:
   - SubSonic (Clementine 1.3.1)

# Settings

Fresh install with community-settings and Subsonic enabled. I think I have reverted all other changes I tried to fix this issue. I already read [the FAQ about problems like this one](https://github.com/ampache/ampache/wiki/FAQ#when-using-an-api-ampache-subsonic-upnp--i-can-browse-my-library-but-playback-doesnt-work-whereas-it-is-working-using-the-web-interface-how-to-make-it-work), but that did not help. Reading through other issues, open and closed, and trying proposed fixes, didn't help either, but the logs mostly suggested different issues anyway.

# Description

I can not play songs using Clementine 1.3.1 via the subsonic API. I can load the catalog I created and see all the songs in it, but if I try to play one, the song is skipped immediately. In clementines logs I see a message about not being able to play the song because the "stream does not contain enough data" (translated from the error message that was originally in German - "Der Datenstrom enthält nicht genug Daten."), but no more details.

Interestingly, I can play music using other clients like Subsonic Music Streamer for android or the chrome app SubFire. Therefore I am not sure if this even is a problem with ampache, but others people successfully used clementine with ampache and because clementine has fewer options I could have wrong, I guess it's more likely that I missed something on the ampache side.

Looking at the logs, I can see a difference between clementine and subsonic music streamer: Only the later accesses /play. I don't know why. The access to /rest/stream.view is also totally different between the two clients, but I think that's because of different API versions?

# Logs

On my server, in the access.log of apache I see the following when trying to play a song with clementine:

```
[ipv6] - - [29/Apr/2018:19:03:05 +0200] "GET /rest/getCoverArt.view?id=300000005 HTTP/1.1" 200 3985 "-" "Clementine 1.3.1"
[ipv6] - - [29/Apr/2018:19:03:05 +0200] "GET /rest/stream.view?v=1.8.0&c=Clementine&u=admin&p=enc:[...]&id=17.225.163.5 HTTP/1.1" 200 3669 "-" "Clementine 1.3.1"
```

For subsonic music streamer, these lines are as follows. No idea why I get the first one twice.

```
[ipv6] - - [29/Apr/2018:19:04:03 +0200] "GET /play/index.php?ssid=[...]&type=song&oid=8&uid=1&client=android&noscrobble=1&player=api&name=[...].mp3 HTTP/1.1" 301 915 "-" "-"
[ipv6] - - [29/Apr/2018:19:04:03 +0200] "GET /play/index.php?ssid=[...]&type=song&oid=8&uid=1&client=android&noscrobble=1&player=api&name=[...].mp3 HTTP/1.1" 200 9317860 "-" "-"
[ipv6] - - [29/Apr/2018:19:04:03 +0200] "POST /rest/stream.view?u=admin&p=enc:[...]&v=1.2.0&c=android&id=300000008&maxBitRate=0 HTTP/1.1" 200 9249986 "-" "-"
```

The ampache logs contains the following lines for every time I try to play a song with clementine. No such lines are appended using subsonic music streamer.

```
2018-04-29 19:50:39 [ampache] (subsonic) -> Missing Subsonic base parameters 
2018-04-29 19:50:39 [ampache] (PHP) -> [Runtime Error] SimpleXMLElement::addAttribute(): Attribute already exists in file /var/www/ampache/lib/class/subsonic_xml_data.class.php(198)
```

There is nothing in the apache error logs.

**Comment by wagnered** [comment]
@Gotos 
I am using the latest 3.8.7-develop commit with Clementine 1.3.1 and have no problems. playing via Subsonic API.

>2018-04-29 19:50:39 [ampache] (subsonic) -> Missing Subsonic base parameters

indicates that username or password, and token, version, action, or clientapp is missing from request URL.

From my http access log:

> 127.0.0.1 - - [29/Apr/2018:14:22:11 -0700] "GET //rest/stream.view?v=1.8.0&c=Clementine&u=admin&p=enc:657863656c31323233&id=300000038 HTTP/1.1" 200 9808644 "-" "Clementine 1.3.1"
127.0.0.1 - - [29/Apr/2018:14:25:53 -0700] "GET //rest/stream.view?v=1.8.0&c=Clementine&u=admin&p=enc:657863656c31323233&id=300000038 HTTP/1.1" 200 15909 "-" "Clementine 1.3.1"
127.0.0.1 - - [29/Apr/2018:14:25:53 -0700] "GET /play/type/song/oid/38/uid/1/client/Clementine/noscrobble/1/player/api/name/Quincy%20Jones%20-%20Dead%20End.mp3 HTTP/1.1" 200 34668 "-" "Clementine 1.3.1"

Something doesn't seem right about the id from your Clementine access.log:  it looks like a URL (17.225.163.5) instead of a proper id number (300000008) as shown in the access.log for your "subsonic music streamer".

**Comment by Gotos** [comment]
Yeah, I wondered why that looks like a IP, too... But I have no idea where it comes from. It certainly isn't any IP used in my home network or for my server... For today, I have to stop working on this problem, I'll get back on it tomorrow or the day after. Thanks for the input so far!

**Comment by markuswernig** [comment]
Hi all

It seems that the wrong id is due to the player being linked against QT5 rather than QT4 (where the same works).

After reporting the same issue to clementine (https://github.com/clementine-player/Clementine/issues/6080) I started hacking a workaround for ampache. With this, clementine now plays the songs from ampache.

<pre>
--- index.php.orig      2018-06-10 17:13:18.385448734 +0200
+++ index.php   2018-06-10 17:51:59.130372496 +0200
@@ -136,6 +136,14 @@
     list($name, $value) = explode('=', $param);
     $decname            = urldecode($name);
     $decvalue           = urldecode($value);
+    // workaround for clementine/Qt5 bug
+    // see https://github.com/clementine-player/Clementine/issues/6080
+    $matches = array();
+    if($decname == "id" && preg_match('/^(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})$/', $decvalue, $matches)) {
+       $calc = (($matches[1] << 24) + ($matches[2] << 16) + ($matches[3] << 8) + $matches[4]);
+       debug_event('subsonic', "Got id parameter $decvalue, which looks like an IP address. This is a known bug in some players, rewriting to $calc", '4');
+       $decvalue = $calc;
+    }
     if (array_key_exists($decname, $params)) {
         if (!is_array($params[$decname])) {
             $oldvalue           = $params[$decname];
</pre>

I'll try to put it into a pull request.

**Comment by wagnered** [comment]
Hello @markuswernig 

After the PR, will it still work with QT 4.8.*? I have Fedora 27: It still has it linked with QT 4.8.* and I'm sure that other distributions also have it built with 4.8.*.  

If so, please remember to run php-cs-fixer -vvv fix before pushing your changes.

Thanks

**Comment by markuswernig** [comment]
Hi @wagnered 
Yes, QT4 still works. Tested with clementine 1.3.1 on Debian stretch.
I added some more log output in the pull request.

**Comment by lachlan-00** [comment]
Closing fixed. If this merge didn't fix anything please reopen.
