### ISSUE TITLE
trying to understand the bin/catalog_update.inc options

### ISSUE THREAD

**Issue by jones1008** [ampache/ampache#1711]
I don't fully know what the gather art option does, when using the [command line tool bin/catalog_update.inc](https://github.com/ampache/ampache/wiki/CLI#bincatalog_updateinc) like so:
`php catalog_update.inc -g`
I think it needs some more transparency in the documentation what it exactly does.
Here are some questions that come to my mind where the documentation doesn't really help:

1. Does the gather art option gather the art on a artist and on a album level?
2. Does it search for a album art even if the album art already exists in the file itself (id3 tag) or in the albums folder (as a 'folder.jpg' for example) and override the old one? If yes, is there a way to prevent searching for album arts, if it already has one tagged to only add album arts to albums which don't have a album art?
3. In general I feel like the [documentation for bin/catalog_update.inc](https://github.com/ampache/ampache/wiki/CLI#bincatalog_updateinc) is pretty outdated... I see a `-t` option, but there isn't anything more documented about it and in the source code you can't even find a `-t` option.
In the source code I also see completely other options like `-m`, `-i`, `-o`. Those aren't documented at all.

**Comment by wagnered** [comment]
@jones1008 
if you run catalog_update.inc with -h (illegal switch) you will get a list of legal switches and their explanations. They do exactly what is done when accessing the functions on the web interface catalog page.  
1. It seems to when searching  on line such as  Google or Musicbrainz.  I'm not sure that it does from the id3 tags but that might be because I have no embedded art labeled as 'artist'.  
2. The config/ampache.cfg.php file explains it this way: "DB should be left as the first method unless you want it to overwrite what's already in the database. The order is set with the `art_order` switch on the config file.
3. The Ampache project development is 100% by volunteers. There has been almost no volunteers to update the wiki. This is complicated by the fact that the Ampache source is so unorganized, it takes long time to unravel the code enough for describing features in a wiki.   As I came late to the project, I do not fully understand all the features.  I usually have to try to recreate the issue and step through the code to resolve the problem and I am the only active developer at this time.

The wiki pages can be edited by any member of github so you are welcome to get  involved. :smile:

**Comment by jones1008** [comment]
thanks for your response!
1. alright
2. this is what I was looking for. Thanks!
3. Alright, I may have a look at the wiki pages and see what we can improve there 👍
