### ISSUE TITLE
Channels play sync

### ISSUE THREAD

**Issue by a7medo778** [ampache/ampache#1713]
Hi,
I am using the latest dev build just updated today, finally i figured out how to operate the channels feature, its AWESOME

But i am having an issue, if i played the stream for lets say 10 min, then opened that same stream in another instance, the two would be minutes apart !
Is that normal behavoir ? I mean opened on mobile i get “live streaming” on the player so shouldnt all instances be synced to the second ?

If the log files are needed i’ll be glad to supply them

**Comment by a7medo778** [comment]
another issue would be that it stops after about 5 hours of playback, i dont if its a php variable i have to extend or something but the channel gets stuck

**Comment by wagnered** [comment]
@a7medo778 
> But i am having an issue, if i played the stream for lets say 10 min, then opened that same stream in another instance, the two would be minutes apart !

Looking at /bin/channel_run.inc.php it looks like it is expected behavior.  This is not a "radio station".  The closest Ampache has to a radio station would be broadcasting what the user is currently listening to.

> another issue would be that it stops after about 5 hours of playback, i dont if its a php variable i have to extend or something but the channel gets stuck

5 hours is a long time to suspect Ampache.  The stream stops because the buffer becomes empty.
Now for why that happens, a log might reveal why.  I suggest you enable the Ampache debug log and maybe the php log.   After 5 hours the Ampache log might be quite long.  The command `tail -n NUM` will display the last NUM lines of the file.

**Comment by a7medo778** [comment]
Really ? How so ? The channels are sure not radio

**Comment by wagnered** [comment]
if you enable `live_stream` in lib/ampache.cfg.php you will then see the "Radio Station" item under the Music menu.  This page allows one to add a new radio station, but I don't know what goes in most of the fields.

**Comment by a7medo778** [comment]
Mmmm interesting, let me poke around in it
It might be just a placeholder for an icecast channel

**Comment by a7medo778** [comment]
i been tinkering around with it with no luck ;/

**Comment by mitchray** [comment]
Closing as Channels are being deprecated
