### ISSUE TITLE
Slow performance because of playlist

### ISSUE THREAD

**Issue by Simounet** [ampache/ampache#1717]
# Environment

 * Ampache version: 4aa6f1332639009d66ba789d4068d611de450c5a
 * Web server + version: Apache 2.4.18
 * Server operating system: Ubuntu 16.04
 * Client operating system: Firefox

Hi there,
I noticed some performance issues since few months and just find out the reason. Any page takes at least 3 seconds to load because of the `Playlist::format()` from https://github.com/ampache/ampache/blob/develop/templates/rightbar.inc.php#L40 .
I kept diving into the code and found [this heavy method](https://github.com/ampache/ampache/blob/develop/lib/class/user.class.php#L1010) called for each playlist created.
I have only 4 playlists created and without this code, the page takes only 0.2 seconds to load against 3s.

I would love to push a PR but wanted to know before if anyone knows why we needed it?

**Comment by Simounet** [comment]
It's called from https://github.com/ampache/ampache/blob/develop/lib/class/playlist.class.php#L134 referring to https://github.com/ampache/ampache/blob/develop/lib/class/playlist_object.abstract.php#L67 .
I will make a PR to show you.

**Comment by Simounet** [comment]
I made a quick one here: https://github.com/ampache/ampache/pull/1718 .

**Comment by wagnered** [comment]
OK, I see what you are referring to.  But:

1 The value of the $details parameter should not be hard-coded like that. There are a number of procedures ("search" for one) that calls Playlist::format($details) with either false or true.  
2. Users  should be able to decide if they want their full name displayed. This would require a config switch for the user to select.
3.  The work would be significant to properly incorporate your change and a policy is in place to not add any new features in order to have time to work on Ampache/Laravel (Ampache-4.0).

I do appreciate your desire to contribute to the Ampache project and don't want to discourage you.  I consider the fact that Ampache is so slow to be a bug and would be happy to include a  PR that speeds up Ampache. see the [coding standards and coding philosophy](https://github.com/ampache/ampache/wiki)

The reason that Ampache is slow is because to get the information needed from the database, each object is created, this takes at lease two additional scripts to create each song, artist, album, etc object. 
Ampache would be much faster if all features accessed the information directly from the database.

Ampache/Laravel will access the database directly and should be much faster than Ampache-3.*

**Comment by bowlofeggs** [comment]
I can confirm this issue - I had about 15 playlists and I was experiencing excruciating page load times (and search too). I removed all but one, and it now loads in about 1-3 second (and search is fast too).

**Comment by wagnered** [comment]
PR #1717 was just merged.  @robled just tested the patch and seemed to be impressed.  I also thank him for bumping this up to my attention :smiley:
