### ISSUE TITLE
playcount increments twice when playing via Stream

### ISSUE THREAD

**Issue by sishrad** [ampache/ampache#1739]
# Environment

 * Ampache version: 3.8.8
 * Web server + version: Apache/2.4.10
 * Server operating system: Raspbian 8 (jessie)
 * Client operating system: Kubuntu 18.04 LTS (Bionic Beaver)

 * Client type:
   - Web Firefox 60.0.2 (64-bit) sending playlist to Audacious 3.9

# Description

When playback is via Stream the playcount is incremented once when generating the playlist (one play for each song in the playlist, clicking "Play" in Firefox) and once more when the song begins in Audacious.

**Comment by wagnered** [comment]
@sishrad,  Sorry I took so long to respond...

I started looking into your issue.

**Comment by wagnered** [comment]
I tried it with VLC, disabling autostart.  No songs had a playcount until I actually started VLC playing them. and songs accrued playcounts only when they were actually played or maybe transferred to the client.

I think it's the way Audacious is handling the playlists/songs.  But I couldn't find a way to prevent Audacious from auto starting when receiving a playlist in order to test it.

**Comment by lachlan-00** [comment]
This is not longer occurring in develop.
I've also recently added a check to not recount songs immediately after playing. (ie repeating a song before it's finished will not record it twice.)
