### ISSUE TITLE
DSub broken after upgrade to 3.8.9

### ISSUE THREAD

**Issue by linucksrox** [ampache/ampache#1752]
# Environment

 * Ampache version: 3.8.9-release
 * Web server + version: Apache 2.4 behind Nginx reverse proxy
 * Server operating system: Ubuntu 16.04.3
 * Client operating system: Android 8.1

 * Client type:
   - Web
   - SubSonic

# Settings

[ampache.cfg.php.txt](https://github.com/ampache/ampache/files/2224681/ampache.cfg.php.txt)

# Description

Things worked nicely with 3.8.8, but after the upgrade to 3.8.9, DSub can no longer play files and I see the logs generated below. There is also a modification I made to /play/index.php based on #1498 because  of noticeable audio quality loss after transcoding a 128kbps mp3 file to 128kbps. I just want to mention that in case this issue may be related.
Another interesting thing is that in the web player, I can play .flac files that are transcoded to mp3, but I can't play mp3 source files in the web player.
There's a chance #1751 could be related to this issue, but I doubt it since the error is different and in my environment things were good with 3.8.8.
Anything else you want me to try for debugging?

# Logs
```

2018-07-24 13:04:40 [eric] (subsonic) -> Stream proxy: https://music.example.com:443/play/ssid/d172757cc767f9551c231bd54c6c5caf/type/song/oid/3796/uid/2/client/DSub/noscrobble/1/bitrate/320/player/api/name/Modern%20Day%20Babylon%20-%20Sleeper.mp3
2018-07-24 13:04:40 [ampache] (play) -> Asked for type {song}
2018-07-24 13:04:40 [eric] (session) -> d172757cc767f9551c231bd54c6c5caf has been extended to Tue, 24 Jul 2018 17:04:40 -0400 extension length 14400
2018-07-24 13:04:40 [eric] (play) -> Playing file (/mnt/freenas/smbshare/music/Public/Modern Day Babylon/Coma/01 Sleeper.flac}...
2018-07-24 13:04:40 [eric] (play) -> Media type {flac}
2018-07-24 13:04:40 [eric] (play) -> Custom play action {}
2018-07-24 13:04:40 [eric] (play) -> Transcode to {}
2018-07-24 13:04:40 [eric] (subsonic) -> Stream error: The requested URL returned error: 500 
```

**Comment by wagnered** [comment]
@linucksrox 

Thanks for creating a separate issue, because it definitely is different from #1751.

The error 500 indicates an internal (500) error returned by curl.  This doesn't seem to be a curl error, but might be a generic response if it doesn't receive an ACK  from the recipient.

I suggest temporarily not loading the php-curl module so Ampache uses http instead to eliminate a possible curl error.

I took a look at your config file and found some problematic settings. but if they worked on 3.8.8 they should be ok for 3.8.9.

I don't have a reverse proxy, just another virtual host set up to monitor port 443.  My problem is that I have a router between the internet and the Ampache server, so I'm having trouble replicating your issue.
I have a DDNS which I can access via HTTP, but not HTTPS.  I will work on that to see if I can duplicate your issue.

**Comment by linucksrox** [comment]
I appreciate you looking into it. I can also create an account for you to access my server, or look into other logs such as Nginx/Apache if you need that kind of info.

**Comment by linucksrox** [comment]
So how can I temporarily disable the php-curl module, is that just done via a2dismod?

**Comment by linucksrox** [comment]
Sorry to have wasted your time, I found a bunch of errors in (/var/log/apache/ampache_error.log) pointing to my mistake where I used debug() instead of debug_event() which was causing these problems. I'll close this for now.
