### ISSUE TITLE
Problem with playing files: no decoders for requested format: text/html

### ISSUE THREAD

**Issue by Locus43** [ampache/ampache#1761]
# Environment

 * Ampache version: 3.8.9
 * Web server + version: Apache2
 * Server operating system: Ubuntu 14.04.1 LTS
 * Client operating system: Windows 10

 * Client type:
   - Web

# Description
After successful installing of Ampache, i uploaded some songs (MP3). The songs have the right permission and were detected by the Ampache catalog manager. But when i click on play, the play icon jumps to playing and after a seconds jumps back to pause. I checked if the files were broken, but they aren't. Also the user has the right permission (I'm logged in as admin). The PHP plugins are installed too. I even tried it at several servers, several versions of Ampache and several Browsers.
In the Ampache log, there aren't issues, also not in the Apache log. But when I look at the Firefoy console, it says: media cannot be play. No decoders for requested formats text/html. Can anybody help me?

**Comment by wagnered** [comment]
@Locus43 

Thanks for bringing it to my attention.  I have started looking into the problem.

**Comment by wagnered** [comment]
It works OK with Chrome/Chromium.

Will investigate Firefox to see what might be causing the problem.

**Comment by wagnered** [comment]
@Locus43 

You don't reveal what version of Firefox is installed.

My system has 61.02 installed from the Fedora repository.

I created a new Firefox profile using `Firefox -P` and started Firefox with it.  I was able to play music through the web player. 

The problem with creating a new profile is that everything is lost: add-ons, bookmarks, etc.

So I tried Firefox 62-b19 and was able to play songs in both the default profile and the new one.

So my suggestion is to upgrade to the latest Firefox too.

**Comment by Locus43** [comment]
@wagnered 
Yes I tried a new Firefox profile. Still the same. Also the version is the right: 62.0b20. On the server itself, I also can't play a song. Even in Internet Explorer (both Edge and 'normal') it's not working. 
So I think, it's no specific problem with Windows.

**Comment by wagnered** [comment]
@Locus43 

I managed to upgrade my Win 8.1 installation to Win 10.

I installed Firefox on Win 10 which created a clean profile.I think it was the first time I played a song from my Ampache server, when I got the error.  I set `Forces Http play regardless of port` in Admin->Server Config->system to 'enable'.  Songs from Ampache started playing.  I then disabled the setting, but Amapche continued to play songs. So I cannot replicate the error anymore.  So changing the preference in Ampache was probably a coincidence.

> Even in Internet Explorer (both Edge and 'normal') it's not working.
 
In I.E do you get the same error in the F12 console? BTW, If I understand correctly Edge is a separate browser from I .E. and doesn't have web tools.

I will try to think of something else that might cause that error, but the fact that I can prevent the error by creating a new profile, or **refreshing** the default one, might indicate that the issue is specific to your system or setup.

**Comment by wagnered** [comment]
@Locus43 

Because the problem is with all browsers on two different OS's,  the only thing I can think of is that the zip 
package has been been corrupted somehow.

The MD5Sum of the zip file should be: 91c3ed650b5a5201499e8ac2f26d27aa.

Or perhaps some files was damaged while being unpacked. (Not unheard of :smile: )

**Comment by Locus43** [comment]
@wagnered 

>  I set Forces Http play regardless of port in Admin->Server Config->system to 'enable'. 

Alright I'll try this. Hopefully that's the solution :). I'll also try to unpack the ZIP with 7zip on my Windows machine and upload the files to my server.

**Comment by wagnered** [comment]
@Locus43 

Sorry to take so long to get back to you.  Has this issue been resolved?

**Comment by Locus43** [comment]
@wagnered 

After a long time and many tries, I fixed the problem. I dont't know the exactly reason, but I think the problem was, that the audio converter were not installed correctly. I deleted them and installed them again. Now all works fine. 
Thanks for your help and time.
