### ISSUE TITLE
Song rating metatdata ignored

### ISSUE THREAD

**Issue by m35** [ampache/ampache#1767]
# Environment

 * Ampache version: master (33e392385d0a88dc48008815baa2de6bafd57565)
 * Web server + version: Lighttpd v1.4.50 with PHP v5.6.37 and MySQL v5
 * Server operating system: Docker version 17.12.1-ce, build 7390fc6 running in Ubuntu 08.04
 * Client operating system: Windows 10
 * Client type: Chrome Version 68.0.3440.106 (Official Build) (64-bit) running in 

This environment was generated using this Docker configuration https://github.com/m35/ampache-docker-compose/commit/abd1032627d4dbc5db26ea775c3094328e17bb65

# Settings

My ampache.cfg.php is unchanged after initial install besides enabling logging.
[ampache.cfg.txt](https://github.com/ampache/ampache/files/2363875/ampache.cfg.txt)

# Description

Add a catalog containing music with various values for the "Rating" metadata.
Create a new "Smart Playlist", add the rule "Rating (Mine)", "is less than", "1 Star". Click Search.
The results contain entries with more than 0 star rating.
![starrating](https://user-images.githubusercontent.com/409923/45260294-1eec3e80-b398-11e8-9297-17ce442aa04b.PNG)

Similar results can be seen when searching for other star ratings. 

I have also seen this when using this Docker https://github.com/idelsink/ampache-docker and using Firefox and Chrome in both Ubuntu and Windows with same results. 

# Logs

Not much is logged when I click Search.
```
2018-09-09 01:42:08 [admin] (ajax.server.php) -> Called for page: {browse} 
2018-09-09 01:42:08 [admin] (browse.ajax.php) -> Called for action: {get_filters} 
2018-09-09 01:42:08 [admin] (Catalog) -> set catalog id: 0 
```

**Comment by m35** [comment]
Unless something has changed since this PR https://github.com/ampache/ampache/pull/950 it's supposed to return unrated songs. But really I used this example because it returned results (demonstrating that there are  songs in my catalog that have ratings that aren't being matched). 

Another example: 
"Rating (Mine)" "is greater than or equal to" "3 Stars" -> No results (from the screenshot there should be at least 2)

Also no results when I try "is greater than", "is greater than or equal to", and "is" against any star rating.

I do get results is when using "less than", "less than or equals", and "is not" any star rating. But the results for all those queries are exactly the same, and contain a mix of songs with all different stars.

Sanity check:
"Title" "contains" "Music" -> 30 results from my library

**Comment by wagnered** [comment]
@m35 
The "Ratings (mine)", PR #1647, was created long after PR #950 and evidently wasn't taken into consideration when the "Ratings (mine)" PR was created.  All of the PR's are done by volunteers who, I'm sure, do not have a complete "picture" of Ampache, as complex as it is.  @Afterster  is probably the only  developer who may have a complete picture of Ampache and he has been too busy to continue contributing.

I'll take a look at the current logic and try to determine the complexity of changes to incorporate PR #950 into PR #1647.  If the difficulty is not excessive, I'll make the changes, otherwise it will wait until the Laravel version is released.  (No time line).

**Comment by wagnered** [comment]
@m35 

I've given this issue and your response much more thought.

You wrote:

> Sanity check:
"Title" "contains" "Music" -> 30 results from my library

Why is this a "sanity" check?

>Unless something has changed since this PR #950 it's supposed to return unrated songs. But really I used this example because it returned results (demonstrating that there are songs in my catalog that have ratings that aren't being matched).

If you are referring to a search for Ratings(average) then this might be a problem because this search doesn't use "user id"  so searching for "no ratings" includes a search for any song without a rating (songs not in the ratings table).

>Another example:
"Rating (Mine)" "is greater than or equal to" "3 Stars" -> No results (from the screenshot there should be at least 2)

I just selected three songs and gave them each a three-start rating.  I then went to search->songs and did a search for "Ratings (mine) where rating is greater than or equal to  3 stars and the results were the three songs I set ratings for.

Granted, I am using a test catalog of only two artists and about 24 songs, but this should be a reasonable test configuration.

BTW: what screenshot?

So I am not yet convinced that a search for ratings (mine) on less than 1 star is a valid search.

**Comment by m35** [comment]
@wagnered Thank you for your consideration. If I may, let's put aside the behavior of searching for songs with < 1 star. I would like to focus on the other issue I was experiencing, namely getting no results when doing a more straight forward search.

> BTW: what screenshot?

The one in the first post. Is it not showing for some reason? https://user-images.githubusercontent.com/409923/45260294-1eec3e80-b398-11e8-9297-17ce442aa04b.PNG 
It shows that I have unrated songs, a song with 4 starts, and a song with 3 stars (there are also hundreds more with no ratings and between 1 and 5). I can consistently reproduce the issue where when searching for `Rating (mine)` with `>= 1 star`, `> 1 star`, `= 1 star`, `>= 2 stars`, `> 2 stars`, `= 2 stars` ... `> 5 stars`, `>= 5 stars`, `= 5 stars` I see no results. On the flip side, when I search for `Rating (mine)` with `< 1 star`, `<= 1 star`, `< 2 stars`, `<= 2 stars` ... `< 5 stars` I see every song in my library.

These are the steps I took:

1. Take a song and use any other program to set its rating in its metadata
2. Add the song to the Amapche catalog
3. Search for the rating of the song using a smart playlist.

But if I change the rating of a song in Ampache, it seems to start working as intended.

**Comment by wagnered** [comment]
@m35 

Sorry to take so long. I finally had time to take a closer look at the issue with a clear head :smiley: 

> 1. Take a song and use any other program to set its rating in its metadata
> 2. Add the song to the Amapche catalog
> 3. Search for the rating of the song using a smart playlist.

If you used Rating(mine) for the search, there can't be any results because you didn't rate them on the Songs page, you used the **system** to import the POPM ratings. If Rating(average) is used, there are results as expected.

**Comment by lachlan-00** [comment]
Metadata ratings are imported for user -1 (system)
* When using Rating, you get the average for all users.
* When using Rating (Mine) you get only ratings for your user.

The search results will show a star rating average when you haven't set one. This is intended.

So for your picture above when you search for things you haven't rated.
* If system has a rating of 4 and you haven't rated it. the 4 will show.
* If system has a rating of 2 and you rate it 5, the 5 will override the 2

The names of these have changed in develop recently too
![image](https://user-images.githubusercontent.com/1305249/60222206-cdc62080-98bf-11e9-931d-c8691add3d46.png)

So what you're seeing is intended behaviour.
If you override any of those system ratings it will show yours instead.
