### ISSUE TITLE
[Installation] : Debian stretch and dependencies php-gettext

### ISSUE THREAD

**Issue by electro575** [ampache/ampache#1770]
Hi,

I have tried to install ampache on my debian stretch.

With apt-get install ampache, ampache-common have a problem with dependencies php-gettext.

Actual version of php-gettext on my debian stretch is 1.0.12-0.1

The installation ask php-gettext version of debian jessie 1.0.11.0

>> ampache-common : Dépend: php-gettext (< 1.0.11.0~) but 1.0.12-0.1 is installed

Problem : i don't arrived to display a sheet on firefox

http://localhost/ampache -> http://localhost/ampache/test.php although we asked index.php

Logs :

2018/09/13 19:12:52 [error] 8483#8483: *21 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Class 'Gettext\Translator' not found in /var/www/ampache/lib/i18n.php:36
Stack trace:
#0 /var/www/ampache/test.php(66): load_gettext()
#1 {main}
  thrown in /var/www/ampache/lib/i18n.php on line 36" while reading response header from upstream, client: 192.168.1.1, server: 192.168.1.120, request: "GET /test.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.0-fpm.sock:", host: "serv.domaine.fr:5030"

Have a nice day

Thank you so much

**Comment by wagnered** [comment]
Hello @electro575 

I think you have an incomplete install with an old version of Ampache.  Also it might be because the Debian package is a "development" version and needs to have composer installed and run. You could follow the [installation instructions](https://github.com/ampache/ampache/wiki/Installation) to install and run composer.

Or

I suggest you get the latest Ampache version  [ampache-3.8.9_all.zip](https://github.com/ampache/ampache/releases). Replace the existing Ampache version.  This is a complete package with the latest fixes and the Composer packages are already installed.

**Comment by electro575** [comment]
Just keep on this website https://github.com/ampache/ampache/releases

ampache-3.8.9_all.zip not the source code

Thank's

**Comment by wagnered** [comment]
@electro575 

Has this issue been resolved?

**Comment by MarcoGiorgi** [comment]
PLEASE! write as you have resolved to help other to fix the same issue!!

**Comment by wagnered** [comment]
@MarcoGiorgi 

What version of Ampache: release or debug?  Please install the latest release version: [ampache-3.9.0_all.zip. ](https://github.com/ampache/ampache/releases).

Execute `php -m` from a command line.  The list should include "gettext".  If it doesn't, php-gettext needs to be installed from your system's repository.

**Comment by electro575** [comment]
Done.

Have a nice day. Bye
