### ISSUE TITLE
sshfs didn't visible to ampache

### ISSUE THREAD

**Issue by DrDimedrol** [ampache/ampache#1774]
# Environment

 * Ampache version: 3.8.9
 * Web server + version: nginx 
 * Server operating system: debian
 * Client operating system: ubuntu linux

# Description
I trying to add local catalog, that mounted by sshfs, but ampache didn't see my files. I got this error message:
"Error: /music/collection is not readable or does not exist".
When I copy some folders to local machine, ampache successfully add them to catalog.

**Comment by wagnered** [comment]
Hello @DrDimedrol 

The music folders/files must be "owned" by the same user/group that owns the web server process. Or the folders/files must  have public rw access. " /music/collection" is probably owned by root unless you set a  different user/group with `chown` command.

Are you sure that the sshfs is mounted? What happens if you do a `dir /music/collection` from a CLI terminal?

Can you see it mounted when the command `df -h` is issued?

**Comment by DrDimedrol** [comment]
Hi, the problem were with mount point. Adding  -o allow_other option to sshfs command resolve the problem. Thanks!
