### ISSUE TITLE
Gravatar URLs should be HTTPS regardless of the server setting

### ISSUE THREAD

**Issue by roobre** [ampache/ampache#1797]
# Environment

 * Ampache version: 3.9.0
 * Web server + version: nginx/1.6.2
 * Server operating system: Debian 8.11 3.16.0-6-amd64
 * Client operating system: Firefox on Linux

 * Client type:
   - Web

# Settings

Served over plain http, then a reverse proxy which exposes it under https tpo the world

# Description

HTTPS is a client feature and should not be enabled or disabled depending on wether the server is using it or not. This behavior causes issues when the web server ampache runs on is using plain http, but a reverse proxy exposes it as https.
There is no reason to prefer the plain http version of gravatar.

## Foot note

Just wanted to state I'm a fan of this project and want to thank you all for your great efforts on this. Also I'm really hyped about the upcoming 4.0!

**Comment by wagnered** [comment]
@roobre 

Thank you for being a fan of Ampache.  Being the only active developer and chief "cook and bottle washer", I wish I could give a precise release date for 4.0, but solving issues on the current version is of top priority.

> HTTPS is a client feature and should not be enabled or disabled depending on wether the server is using it or not.

I beg to differ.  https is a **security** feature.  I'm not quite sure of what you are trying to say.  What problem does it cause?

Because https is a security feature, Ampache's Gravitar plugin does check for the server using https and from that determines which protocol to use.

If the client is sending the request using http, the web server should not be forcing https, unless it is configured to do that.

Also, I'm not sure why a system would require a reverse proxy for SSL communication, except to force https. Apache can be configured to do that by itself using rewrite rules. I use Apache and have a virtual host set to monitor port 443: I can access Ampache with both http and https.

Thanks...

**Comment by roobre** [comment]
Hey @wagnered.

No worries about the release date, after all, these are things we all do on our free time, so no pressure at all.

Yes, https is a security feature, but it depends on the client. Wether the server ampache is using is capable of https or not (or even, wheter if it is *actually* using it or not) has nothing to do on the client (browser) ability to support https for a completely different website (gravatar). I think this is fairly obvious. Now, leaving that aside, there is no reason to think a web browser without https support still exists nowadays (or even ten years ago), and https should *always* be preferred when it's available since plain http has well-known security issues, as client traffic can be leaked, manipulated, and logged.

I think preferring http has zero advantages over the good practice and benefits https provides.

That being said, of course it's your project and your decision, so perhaps we can reach a middle ground here. What about a config option for it? Like  `Use HTTPs for Gravatar URLs: Auto/Always/Never`.

**Comment by roobre** [comment]
Hey again,

My point is that ampache's own ssl configuration should not be related to the plugins using http(s) to connect to external sites, and that these plugins should use https by default since it offers some advantages over http with literally no downsides.

Sorry if I didn't make myself clear, and thanks fro taking the suggestion into account!
