### ISSUE TITLE
Is it possible to use relative path ?

### ISSUE THREAD

**Issue by restanrm** [ampache/ampache#181]
Hi, 

I would like to use ampache behind a reverse proxy and I've got problem with absolute path in the pages. My host is not accessible from internet and the resolution is not possible from an external point of view.
With relative path this is not a problem.

I've tried to comment the line : 
 $results['web_path'] = $http_type . $results['http_host'] . $results['web_path'];
from file « lib/init.php » and it work's perfectly on the login page but after login I've got a blank page…

**Comment by cavebeat** [comment]
hi,
i am facing a similar problem with a reverse proxy. 

ampache runs on LAN http://192.168.1.10/ampache
openVPN tunnel to my WebServer with a public ip and subdomain pointing at it. 
10.8.0.9 is the IP address which routes from the WebServer to the Ampache Host on my LAN


i have an Apache2 vHost with a subdomain with proxypass reverse proxy

```
        ProxyRequests Off
        <Proxy *>
                Order deny,allow
                Allow from all
        </Proxy>
        ProxyPass /ampache/ http://10.8.0.9/ampache/
        ProxyPassReverse /ampache/ http://10.8.0.9/ampache/
```

The subdomain https://amp.example.org/ampache shows the login page, but tries and fails to load other stuff from http://10.8.0.9/ampache/... 

> "Blocked loading mixed active content "http://10.8.0.9/ampache/themes/reborn/templates/default.css""

when i change the http_host variable to amp.example.org, i can see in FireFox in the Network Monitor it tries to find ressources on "http://amp.example.org/ampache" <-- and fails, because there is no port :80 serving http 

"Blocked loading mixed active content "http://amp.example.org/ampache/themes/reborn/templates/default.css""

http_host does also break my LAN usage, when i am at home and it tries to load all from amp.example.org/ampache instead of http://192.168.1.10/ampache

any idea how to fix the reverse proxy, (ProxyPreserveHost Directive only changes the ip to the hostname, but the https/http is still wrong)
maybe @restanrm can tell how he solved the problem? 

with LetsEncrypt it's cheap to run several services behind reverse proxy's
for example: http://fomori.org/cherrymusic/ is already working in this setup. but it's not comparable to Ampache! 


Any chance to have relative paths working?

**Comment by cavebeat** [comment]
I have a solution for the reverse proxy:

added a ssl vhost for https://192.168.1.10/ampache, now i can point the proxypass to https://10.8.0.9/ampache/ 
ignore all the certificate checks which pop up because of the self signed certificate. 

now i can use the config http_host = "amp.example.org"

`
	ProxyRequests Off
	SSLProxyEngine on
	SSLProxyVerify none
	SSLProxyCheckPeerCN off
	SSLProxyCheckPeerName off

        <Proxy *>
        	Order deny,allow
        	Allow from all
        </Proxy>

	ProxyPass /ampache/ https://10.8.0.9/ampache/
        ProxyPassReverse /ampache/ https://10.8.0.9/ampache/
`

ampache creates all static urls now as "http**s**://amp.example.org" instead of "http"

maybe there could be an elegant solution to add a host_protocol = http|https be added so ampache can run on http and it stills looks like https after the reverse proxy.


still ampache on LAN is now unuseable on http://|https://192.168.1.10/ampache because all URL look now like http://|https://amp.example.org/ampache

**Comment by Afterster** [comment]
Mhh I have to give some try with latest version, but as far as I remember this could be done by removing `http_host` setting. By doing that Ampache will automatically define host according to the request.
I will give a try later just in case it changed due to other features.

**Comment by mbrandis** [comment]
I know that this one is long closed, but I just stumbled over the same problem. I'm using Ampache now via a reverse proxy and in the HTML source I only see absolute URLs. 
I'm using Ampache 3.8.3 and tried the http_host option (on and off). Any more advice what I could try?

**Comment by wagnered** [comment]
@mbrandis ,

Setting url rewrite rules on the proxy might help, but I'm not familiar enough with reverse proxies to offer a suggestion.

Please open a new issue giving as much detail as possible: is your Ampache server directly connected to the internet or proxy server which is directly connected, or is it  behind a router connected to the proxy server? 

I may be able to find the time to look into the issue.
