### ISSUE TITLE
Multiple vulnerabilities in Ampache 3.9.1-develop 

### ISSUE THREAD

**Issue by TarlogicSecurity** [ampache/ampache#1872]
Hi!

We found multiple vulnerabilities that, chained, could lead to a full compromise. The product affected is Ampache 3.9.1-develop. Can you provide us a mail address where we can send you the details?

As a summary:
- SQL injection
- Account takeover via stored XSS + CSRF
- Few other security related issues

Best regards

**Comment by vollmerk** [comment]
@TarlogicSecurity - I'm not longer involved in the project, but I care about it (that's why I still pay for the domain name personally) If you don't hear from someone quickly feel free to reach out to me at karl.vollmer@gmail.com and I'll see if I can help.

@Afterster - are you still involved, I haven't paid attention... I just pay the domain bill haha :)

**Comment by lachlan-00** [comment]
I can help out with a pull but I don't have merge.

**Comment by lachlan-00** [comment]
@vollmerk the only active person this year with merge has been @Psy-Virus

**Comment by TarlogicSecurity** [comment]
Hi!

We just sent to you (@vollmerk ) a mail with the details. We hope this can be helpful for you.

**Comment by lachlan-00** [comment]
@TarlogicSecurity I've started working on the security issues in Ampache. Thank you for bringing this forward and I'll be working fast as I can to bring Ampache up to scratch.

Here is my new codacy repo where i'll be working on the project
https://app.codacy.com/project/Ampache/ampache/dashboard
![image](https://user-images.githubusercontent.com/1305249/57112936-aeaa8700-6d85-11e9-8c7f-7d1117ee8d02.png)

VS the current codacy.
https://app.codacy.com/project/afterster_2222/ampache/dashboard
![image](https://user-images.githubusercontent.com/1305249/57113009-e7e2f700-6d85-11e9-9266-30e3a3bf4190.png)

**Comment by TarlogicSecurity** [comment]
Hi!

We just received a mail from MITRE with the CVEs assigned:

- CVE-2019-12385 for the SQL Injection
- CVE-2019-12386 for the persistent XSS

Maybe you want to include them in the changelog when you release a new version.

Best regards.

**Comment by lachlan-00** [comment]
Thank you, i'm bugfixing now so we can hopefully close these holes soon.

**Comment by stebe** [comment]
Now that core is in develop, are these security issues resolved?

**Comment by lachlan-00** [comment]
The issues @TarlogicSecurity found are fixed but I was just keeping it open till I can double check the list tonight

**Comment by lachlan-00** [comment]
Double checked, this CVE can be closed.

Changes made to resolve this are:

* mail_enable required in config to allow lost passwords/resets and all email features (ALL users will need to enable this setting once they are on 4.0.0-develop)
* admin accounts can't have passwords reset from this page
* password generation is random and longer+random length
* social is disabled by default.
* filtering requests in search as well as private messages has been tested with the other CVE that is open for ampache.

**Comment by jdelta-RBS** [comment]
@lachlan-00 Is there a specific PR / commit(s) that addressed these CVEs? Also, when is 4.0.0 slated for release? Thanks.

**Comment by lachlan-00** [comment]
The large initial core commit had all the changes for this. It's probably going to be unreadable for the specific changes but this is where it all went in.
https://github.com/ampache/ampache/commit/006480b5320b265f5009c4df41eb98260ef5b6af

Specifically changes that resolve this are:
* Filtering the search class and other user input areas
* Filtering of url variables.
* PM text filtering
* Disabling Admin password reset from the lostpassword page
* Disable all email enabled pages by default (Requires mail_enable in the conf to be set)
* Disable social by default (PM's require this)
* Generate password of random length and random characters instead of a predictable length/arrangement

Enabling email/social is also safe but disabled by default as it's not something many people use.

The release of 4 will happen once we've had enough time to test in the wild.
I've made so many changes that i would like it to have at least a month or two in testing while other people use it. There have already been a few things i missed as i don't use those setting regularly.

**Comment by TarlogicSecurity** [comment]
Hi!

The reported SQL injection vulnerability is still present. You provided more character filtering, however, the problem is that the reported injection does not require using single quotes. Since the problem only affects the input data provided via "last_play" and it's of type "days", a quick fix would be to edit this line in _mangle_data(), forcing the variable to be an integer:

`if ($type == 'numeric' || $type == 'days') {`

lib/class/search.class.php

Best regards.

**Comment by lachlan-00** [comment]
@TarlogicSecurity that line doesn't exist in the search class?

**Comment by TarlogicSecurity** [comment]
Hello, 

We are approaching the agreed date for disclosure. Can we publish an article with the details next week or should we wait a bit more?

Regards

**Comment by lachlan-00** [comment]
There's a lot more work before develop goes stable due to other factors but I don't think you need to delay because of that.

**Comment by rcsanchez97** [comment]
@lachlan-00 I am working on the Debian LTS team and would like to understand if you might be able to provide specific commits or patches separate from the single large commit so that we can patch these CVEs in Debian.  After spending some time trying to determine which changes correspond to the list which you posted on 24th June, it is clear that the only way to feasibly address the vulnerabilities for ampache in Debian is with your assistance.  Are you able to help?

**Comment by lachlan-00** [comment]
I can help. Which version is debian on? I can provide a patch based on that version until v4 is released

**Comment by rcsanchez97** [comment]
Thanks!  That would be fantastic.  The version in Debian is 3.6-rzb2752.  That version was first uploaded to Debian around 27th August 2013 with the changelog entry `New upsteam snapshot.  Contains important bug fixes to the installer.`  Prior to that, the Debian version was 3.6-git408e713, uploaded to Debian around 31st May 2012 with the changelog entry `New upstream git snapshot, using commit 408e71344ade84685c181cd326e2ec5e79c9157b`.

I mention the earlier entry since I find it unusual that the snapshot went from git to "rzb" (which is "bzr" reversed), in the event that the upstream history is split.

**Comment by lachlan-00** [comment]
That's fine. I'll work out which commit and make a branch for it. I still have the docs I worked from so it shouldn't be too hard to resolve.

**Comment by wagnered** [comment]
Lachlan,

I've been working on this comment waiting for the right time to send it.  This seems to be the right time. ; ' >

The Ampache project is very fortunate to have you as an active developer.  You have accomplished so much more in the last 10 months than I had in the last 4 years.  Keep up the good work.

I don't remember if the following is in the wiki, but it should be. I would like to pass on some Ampache design philosophy from @afterster shortly after I joined.

His rationale was that there should be only  one enhancement/fix per PR.  This allows more keywords to search for similar problems or fixes. This is especially useful if someone needs a patch while waiting for the next release. A squash/merge on a PR or direct rebase/push to source will lose much history. This also keeps the history cleaner and easier to follow.

He also requested that the number of commits per bug fix/enhancement be kept to minimum. One should not be in a hurry to push changes to your remote branch.  Do a squash and merge or a rebase on the local branch before pushing to your remote

If a user refers to additional problems, ask the person to create a separate issue for each problem: makes tracking easier.



-------- Original message --------
Subject: Re: [ampache/ampache] Multiple vulnerabilities in Ampache 3.9.1-develop  (#1872)

**Comment by lachlan-00** [comment]
It looks like debian is using a manual zip/tar patch

I've pulled the last commit into a new branch and applied the debian source package over the top.
https://github.com/ampache/ampache/tree/debian-3.6-git408e713
https://github.com/ampache/ampache/commit/88f798b87844417109ec37c7a9551b6b2a2ea082

There was only one file difference so i'm not sure what the Debian version actually patched but that's where i'll work on this for you.

**Comment by lachlan-00** [comment]
@wagnered this has been the most exciting and scariest time in my life.  You were the one who merged my first pulls before i even knew what i was doing so it's all thanks to you!

I do need to spread out these pulls more though. To help that i'm changing my tactics a bit more and i'm hoping that will work better. spreading my dev over multiple branches and rebasing against develop after each pull
