### ISSUE TITLE
What is the future of this project?

### ISSUE THREAD

**Issue by kuzi-moto** [ampache/ampache#1876]
Hello! I'm just wondering what's the status of the Ampache project right now? I know that last year there was more focus on developing V4 with Laravel but it looks like the primary developer working on that hasn't been as active.

I noticed a new Project being headed by a newer contributor with a focus on making Ampache more secure. Will the V4 release still have Laravel, or will it just be focusing on updating the existing code-base?

I understand that this is a free project, and will be happy with whatever the path forward will be. Thanks a lot to everyone that has worked on this, it's one of my most used and favorite open source project.

Lastly, what can be done to help out? I don't have a lot of programming experience, but if there is anything that can be done to speed things up I would be interested.

**Comment by lachlan-00** [comment]
Hi,
I'm running the modernization project. The purpose of this project is to bring the existing master/develop code to a higher standard and fix a lot of aged code issues. You can follow the initial work in my personal fork and on the project page.

https://github.com/ampache/ampache/projects/2
https://github.com/ampache/ampache/tree/core

I have been an Ampache user for about a decade and my first code contribution was in 2017. When wagnerd dropped off the radar this year I was really worried about the status of project (to the point that i forked it entirely) so i'm really focused on keeping the code-base i use every day supported and maintained. 

The laravel branch will not be used and will not be updated unless wagnerd comes back. if he does and continues to work on the laravel branch i will be staying on the php version.

I've also set the next version to 4.0.0 on purpose. if the laravel branch comes back it will be fairly diverged from the ampache code in my branches so there would actually be 2 separate versions of ampache. (ampache-core, ampache-laravel) The existing code also suffers from a lot of issues relating to general bugs and security so the next release of Ampache is going to be massive.

Right now i'm working on the core branch in my personal fork, when i merge this into ampache i will start pinging all the open bugs and pulls to move onto this branch instead of develop.

Existing branches will move when the modernization project is completed:
master -> master-3.9.0
develop -> develop 3.9.1
core -> develop -> master -> 4.0.0 release!

If you are scared of jumping into the code (I couldn't do much when i started!) I understand how you feel. One of the modernization goals is to make the code easier to get into. 
* There is also a load of documentation that needs to be updated. 
* Anyone can update the Ampache wiki and even things like wikipedia or other sites that have ampache information need to be updated.
* I want to merge all the changes from my fork into the core branch then i'll start creating issues for anyone to join in.

Thank you for keeping an eye on Ampache!

**Comment by kuzi-moto** [comment]
Awesome, thanks for the great response! I'm glad that Ampache has a dedicated developer to continue making it even better. In hindsight I initially sounded a little rude, so I hope I didn't come off like that, as it wasn't my intent!

I'm looking forward to whatever changes you have coming. Thanks for your work and effort towards this. I would like to help with the documentation as I know there are some important things missing, and room for improvement. So hopefully I'll have some time to add a few things.

Thanks again! Closing this for now as my questions have been answered.

**Comment by gerroon** [comment]
@lachlan-00 

Do you have a rough timeline for v4 release?

**Comment by kuzi-moto** [comment]
Maybe I'm way off, but I would think it will be ready within a couple months. There seems to be pretty steady progress being made.

**Comment by lachlan-00** [comment]
The big changes left i want done are:
* Strings for translation https://github.com/ampache/ampache/pull/1957
* Subsonic 1.13 https://github.com/ampache/ampache/pull/1965

But there are a lot of little problems that have been reported since becoming more active. The API needs a bit more work before we loose that as well.

There are also some security issues with using master over develop with means it needs to happen as soon as possible.
