### ISSUE TITLE
Problems with duplicate playlists

### ISSUE THREAD

**Issue by mbrandis** [ampache/ampache#1904]
# Environment

 * Ampache version: 3.9.0-release
 * Web server + version: apache2 2.4.25-3+deb
 * Server operating system: Debian Stable
 * Client operating system: Several (Linux, Windows, ...)

 * Client type:
   - Web

# Settings

Default installation, not using any special features. I can attach the config file if necessary.

# Description

I created a library with playlists. Some of these playlists are regularly (nightly) recreated by beets. Also every day a cronjob is executed which updates the catalog and with that imports existing playlists. I just noticed, that every day the changed playlists (even if the content hasn't changed) are added again. Now I have multiple thousands of playlist with 99% of them being duplicates.

1. Is this a bug? Or do I use the catalog update wrong?
2. Is there a way to delete the duplicate playlists?

Thanks in advance,
Mark

# Logs

**Comment by lachlan-00** [comment]
I don't fully understand. Is this when importing m3u playlists into Ampache?

What's the update command you're using?

The easiest way to clear them would be by using MySQL commands to clear the table or phpmyadmin

**Comment by mbrandis** [comment]
Yes, I use m3u playlists from a directory which I create and edit outside of Ampache, but would then like to use with Ampache.

There are two cronjobs:
4 4 * * 1-6 /usr/local/share/ampache/bin/catalog_update.inc -a -c -i -m
4 4 * * 0 /usr/local/share/ampache/bin/catalog_update.inc -a -c -g -i -m -o -v

I will have a look at the MySQL databases regarding the playlists.

**Comment by mbrandis** [comment]
I looked into the database tables and found playlist and playlist_data. Do I need to clear both of them?

**Comment by lachlan-00** [comment]
If you don't want any playlists because they're all dupes or it's too confusing to manage you can safely empty those two tables.

Playlist gives the playlist an ID and a name
playlist_data points object_id's to the playlist.id

These are separate from smartlists so if you have any of the they are safe.

**Comment by lachlan-00** [comment]
Thanks for your commands, i don't do playlists outside of Ampache so this will help me test out whats happening.

**Comment by lachlan-00** [comment]
I've followed the trail and found the function in the catalog class.

import_playlist will just import the full file without checking for names or duplicates.

definitely a bug as it should at least import into a matching filename playlist.id

**Comment by lachlan-00** [comment]
Fixed in my branch, will close this issue in the next core update.
![image](https://user-images.githubusercontent.com/1305249/58677639-20cfb500-83a0-11e9-87ca-2d88ad9b15c6.png)

The catalog update will now:
* Look for playlists that match the name or create a new one. (e.g. 'm3u - 5star')
* Add songs that aren't in the playlist if it already existed. (1000 in the playlist but 2 new songs.)

This doesn't REMOVE them from the existing playlist, only add. i'm not sure i want to do a removal as well.

**Comment by lachlan-00** [comment]
closing, this fix is in core now.

Thank you for your help and contributions to Ampache!
