### ISSUE TITLE
Use Composer to manage dependencies

### ISSUE THREAD

**Issue by Afterster** [ampache/ampache#191]
We should think to use Composer for dependencies management instead of making copies to /modules

**Comment by wagnered** [comment]
I started looking into this using cakePHP.  I looked at several frameworks and cakePHP seems the most comprehensive with its documentation. 

They are all capable of MVC/rest architecture.

Yii might be good because one of the structures it provides is a separate backend/frontend which allows for separate development. The documentation was sketchy, but might not be so bad now that I am more familiar with tthe MVC concepts.

**Comment by arnaudbey** [comment]
Symfony2 or maybe silex would be a good choice too. Anyway, Cake, sf2, etc. would make us rewrite the whole application. Composer would be a good start to manage dependency which is the point of this "issue"

**Comment by wagnered** [comment]
Hello Arnauld,

If you think that it is not necessary to utilize a whole new framework
to implement Composer for dependency management, please give us your
thoughts as to how to do it with minimal changes to Ampache and I'll
take the idea about using a new framework to a new topic.

But first, let me fill in the large gap in logic that I left in my last
message.

The following discourse implies that I am for using Composer, but a more
in-depth discussion is required to determine what course of action
should be taken to implement Composer into Ampache.

Ampache does need a new architecture along with a new dependency
management system. The reason: Composer utilizes PSR-4 autoloading specs
with PSR-0 fallback, but Ampache requires several different autoloaders
to try to get various classes loaded.  I've stepped through the code and
watched at least three fallback autoloaders fail until I re-arranged the
folders in some of the modules. None of the existing autoloaders could
handle the PSR-4 type module(vendor) structure.

To even use Composer as-is with Ampache, would take a significant logic
change if not an architectural change to Ampache. Why not adapt Ampache
to the MVC model/Composer and make the app much more efficient and
expandable? 

The MVC architecture would require more of a re-organization than a
re-write although the rewrite would simplify the logic flow and a lot of
functions could be left to the framework working "behind the scene" to
accomplish what, perhaps, a half-dozen modules accomplish now in
Ampache.

So, My logic is "Why go only half-way?"  Ampache needs to be upgraded to
a more modern architecture anyway, so why not redo the whole project
instead of only a small part of it now and wait until the remainder
becomes deprecated for whatever reason.

Regards,

-- 
73 From Ernie D

AA1AD | CN87ug 

-----Original Message-----From: Arnaud Bey <notifications@github.com>
Reply-to: ampache/ampache <reply
+005d506eeb1e6ef88e354120c6904f28b76a431c4eca697692cf00000001117cacd692a169ce02074781@reply.github.com>
To: ampache/ampache <ampache@noreply.github.com>
Cc: Ernest Wagner <wagnered@comcast.net>
Subject: Re: [ampache] Use Composer to manage dependencies (#191)
Date: Tue, 26 May 2015 14:51:18 -0700



Symfony2 or maybe silex would be a good choice too. Anyway, Cake, sf2,
etc. would make us rewrite the whole application. Composer would be a
good start to manage dependency which is the point of this "issue"

**Comment by arnaudbey** [comment]
Hey Ernest.

First of all, I'm really interested in using composer. I won't come back on all the benefits it can bring. Without reorganizing Ampache, the benefits wouldn't be many... it could be usefull for external js library for example, or facilitate installation (launching scripts, etc.).

Reorganizing ampache would make sense too (even more actually) with composer. I love that idea, really (whatever frameword is used), but, when I read that https://github.com/ampache/ampache/issues/449 , which is already 8 months, and is more js related than about backend architecture, I'd say it's not the ampache team priority (maybe I'm completly wrong), but if you come with a nice PR it would be really appreciate (once again, I may be wrong)

To finish, I'd really love to see a backend framework here. Symfony2 for exemple :-p I maybe insisting on that it's because it's the only one I've used for now... But I'd enjoy the opportunity of playing with another one)

:hamster:

**Comment by Afterster** [comment]
Well it's why things was not really done yet, it's a bit related to #449.
Since the beginning we wanted to move Ampache to a PHP framework, but this takes time. Every week bugs are still reported in Ampache and this always delay 3.8.0 release. We don't have any hurry here, but it would be good to release it one day :)
After that, 3.9.0 will be the release of architectural and UI review. Including a PHP framework and Composer support I hope so. This is heavy and will put develop branch in unstable state for weeks. To be clear we don't want to loose feature on the review.
Be sure any help would be appreciated of course, but architectural review is generally an one-man job.

**Comment by Afterster** [comment]
I started to migrate Ampache to Composer for dependency management.
Should be good enough now if someone want to review it (just commited on develop branch) as I don't have many experiences with Composer.

It still needs:
 * more testing to check nothing got broken
 * automatic update process should be improved
 * find a way to automatically provide an additional release file with embedded dependencies on github releases
 * ...

Thanks.

**Comment by arnaudbey** [comment]
I don't have many time tonight but it seems you have to have so many duplicates between your require and repositories section. I'll try to look a bit more tomorrow.
