### ISSUE TITLE
Subsonic Php Error with Ultrasonic client and Ampache LAMP

### ISSUE THREAD

**Issue by douglasriper** [ampache/ampache#2064]
## Description

**Describe the bug**

Ultrasonic can't connect to my Ampache instance.
The client tells me that the password is wrong.
If I look in the Apache2/error.log I have the errors at the bottom of this message.

I used the htacces provided in the git, I tried with or without url rewrite enabled.
With old Dsub no problem.

I don't know if it's the same problem as ngix so I opened a new bug "in doubt".

**Screenshots**

## Environment

* Ampache version: 4 dev
* Web server + version: Apache2
* Server operating system: Ubuntu Server 18.04
* Client operating system: Android 9
## Logs

In Apache2 error log
`[Thu Oct 03 17:52:39.450388 2019] [php7:error] [pid 485] [client 37.170.12.115:42547] PHP Fatal error:  Uncaught Error: Call to a member function set_preferences() on string in /usr/local/bin/ampache/lib/class/plugin.class.php:262\nStack trace:\n#0 /usr/local/bin/ampache/lib/class/user.class.php(927): Plugin->load('2')\n#1 /usr/local/bin/ampache/lib/class/subsonic_api.class.php(1785): User::save_mediaplay('2', Object(Song))\n#2 /usr/local/bin/ampache/rest/index.php(167): Subsonic_Api::scrobble(Array)\n#3 {main}\n  thrown in /usr/local/bin/ampache/lib/class/plugin.class.php on line 262`

**Comment by lachlan-00** [comment]
So ultrasonic seems to not use just token auth, the password error is because it tries to use token and password auth in tandem. Subsonic and Ampache have different password implementations so for an api client you need to use your api key,

For ultrasonic use your api key as the password
![Screenshot_20191004-064324_Firefox](https://user-images.githubusercontent.com/1305249/66164768-be9cfe80-e676-11e9-944d-2e8c012a0f0d.jpg)

OR

Enable the LDAP user support which forces the old password only method
![Screenshot_20191004-064009_UltraSonic](https://user-images.githubusercontent.com/1305249/66164773-bfce2b80-e676-11e9-9f71-6f46cdbc4601.jpg)

**Comment by lachlan-00** [comment]
The errors are probably not related though. but i need to check them out.

**Comment by lachlan-00** [comment]
Separate bug but a good find.
I've updated develop with a fix for those plugin errors. That was really helpful!

**Comment by douglasriper** [comment]
Thank you,٩(◕‿◕｡)۶ 
 it works again for me. For authentication issues I activated old-time authentication in ultrasonic.
