### ISSUE TITLE
debian git patches branch

### ISSUE THREAD

**Issue by lachlan-00** [ampache/ampache#2091]
@rcsanchez97 the branch https://github.com/ampache/ampache/tree/debian-3.6-git408e713 has been updated.

The difference in code is quite large and a lot of the tarlogic report doesn't actually apply to 3.6.

There was another cve but I'll need to check for the number. The one I posted was wrong

**Comment by lachlan-00** [comment]
https://github.com/ampache/ampache/issues/1806

This one. I need to close this one out but I think that's actually closed too

**Comment by lachlan-00** [comment]
@rcsanchez97 i don't have access to a php5/debian lts box for testing but this branch has the fixes for the CVE's that were open.

Just rename this from txt to patch and apply
[debian.txt](https://github.com/ampache/ampache/files/3732421/debian.txt)

**Comment by rcsanchez97** [comment]
@lachlan-00 Thanks so much for your effort on this.  I'm taking a look now to integrate the patch and I will try to see how much I can test this, not being an ampache user myself.

**Comment by rcsanchez97** [comment]
@lachlan-00 Sadly, this patch does not apply to the Debian package I have to work on, with most of the hunks failing to apply altogether.  I think that 408e713 might not be the correct base commit.  I've been looking at the repository state of the commits around 27th August 2013, including going back to the archive of the old Gitorious project from that time period, but I have not managed to locate something that matches precisely.  When I checked the closest ancestor of that date (a201a05d067b7beb191b5e2ce660dabd3c137560, which has author/commit dates of 22nd August 2013) and compare it with the Debian package I am working on, the diffstat summary line looks like this:

`187 files changed, 62713 insertions(+), 42 deletions(-)`

If there is a way I can help locate the right base commit, please let me know.

**Comment by lachlan-00** [comment]
I could revert the branch back and paste over with the Debian package first?

**Comment by rcsanchez97** [comment]
You can find the current Debian source here: https://sources.debian.org/src/ampache/3.6-rzb2752+dfsg-5/

If you would prefer it in tarball form, the dget utility can be used with this link: http://deb.debian.org/debian/pool/main/a/ampache/ampache_3.6-rzb2752+dfsg-5.dsc

Note that the Debian package has some patches carried under the `debian/patches` directory, so if you don't have a Debian or Ubuntu system with the right utilities on it, let me know and I can supply a tarball that already has the patches applied so that additional patch you create will be compatible with those.

**Comment by lachlan-00** [comment]
yeah, if you could upload one with deb patches applied then i can patch that

**Comment by rcsanchez97** [comment]
Sure thing.  Here is the link: https://people.debian.org/~roberto/ampache-current-debian-lts-source.tar.gz

(I probably should have just gone ahead and done that rather than asking and waiting for an answer.)

Again, your help is most certainly appreciated.

**Comment by rcsanchez97** [comment]
@lachlan-00 I finally found some time to take a closer look and it seems like with only two or three exceptions the differences were all spaces/tabs.  The remaining instances where the patch you provided would not apply was because the changes were already present in the Debian version.  Would you mind reviewing this modified version of the patch which I have prepared?  I'd be interested to know if you find anything I might have missed.  If you give me the OK, then I will go ahead with this patch.


[04_CVE-2019-12385_CVE-2019-12386.txt](https://github.com/ampache/ampache/files/3827866/04_CVE-2019-12385_CVE-2019-12386.txt)

**Comment by lachlan-00** [comment]
oh, that's awesome. i'll look tonight

**Comment by lachlan-00** [comment]
I've gone through and the fixes to scrub_in, search, dba::escape, password reset rules look correct to me.

The biggest change in this code is that the admin users can not have their password reset from the forgot password link. i know the CVE's are not related specifically to this version but the areas of attack still existed here.

So a short summary of the changes is
* filter raw variables in a safer way
* escape and filter search data
* escape database variables
* generate less predictable passwords
* only allow non-admin users to use lost password to reset access

**Comment by rcsanchez97** [comment]
The review and assessment are much appreciated.  I will proceed with publishing the patched version and advisory later today.

**Comment by rcsanchez97** [comment]
I have just published the updated package: https://lists.debian.org/debian-lts-announce/2019/11/msg00008.html

I believe this issue can be closed.

**Comment by lachlan-00** [comment]
glad we got there! i'll keep that branch open just in case
