### ISSUE TITLE
Selecting `Add New...` does not prompt for Artist or Album on save

### ISSUE THREAD

**Issue by NatureMuncher** [ampache/ampache#2140]
## Description
Many of the songs in my collection are unknown so are stuck with the `Unknown (Orphaned)` labels for Artist and Album name. I am unable to update them.
### Describe the bug
I select Edit and then select the drop-down for `Add new...`. I click Save hoping for a prompt or something but nothing happens. The Artist and Album are simply blanked out.

### To reproduce
1. Open a song in the Unknown album and click Edit
2. Attempt to change Artist or Album details from Unknown to Add New... 
3. Click Save

### Expected behavior
Guessing that when `Add New...` is selected that either a popup would prompt for the new Artist/Album name, or when clicking `Save` another screen would prompt me to enter relevant details

## Environment

* Ampache version: Develop
* Web server + version: Apache/2.4.6
* Server operating system: CentOS Linux release 7.7.1908
* Client operating system: Fedora release 31 (ThirtyOne)

### Client type:

* Web

## Settings

https://pastebin.com/SvT80nzm

**Comment by lachlan-00** [comment]
I can safely say I've never actually used this feature so there probably is an issue here. Will need to test

**Comment by lachlan-00** [comment]
I didn't realise this was even a feature but will need to work out what it's supposed to be doing.

**Comment by NatureMuncher** [comment]
How else would I set the artist/album correctly? Rename the file perhaps?

**Comment by kuzi-moto** [comment]
> How else would I set the artist/album correctly? Rename the file perhaps?

I believe the best way would be to edit the ID3 tags on your music. There are many programs to do this, but Musicbrainz Picard is a good one that can auto-tag. My personal favorite is beets, which can be fast depending on how you use it.

**Comment by lachlan-00** [comment]
What's annoying is that I have been through pretty much every line of Ampache and I don't think there is any facility of adding an artist outside of tags.

So why it's even there I'm not sure but we should also be providing this function as well

**Comment by manuelglez86** [comment]
Yes it is in previous versions you can Add New artist (or Album) manuelly from the web interface, is usefull when you only need to edit 1 or 2 songs so you dont have to Verify the entire catalog, and I think is realated to #2212

**Comment by lachlan-00** [comment]
it is related. i'll need to install the older versions and have a look as i've never used it before.

**Comment by lachlan-00** [comment]
I just installed legacy-develop and it doesn't show up in the lists. is there an option for it?

**Comment by lachlan-00** [comment]
looks like it's JavaScript. i can see the issue now.

**Comment by lachlan-00** [comment]
something in tools.js. i'll compare the old vs new version and get it working.

**Comment by Rhythm-of-Time** [comment]
Playing around with Firefox's debugger and tools.js, at line 335 I found the function 
check_inline_song_edit(type, song). It is not in the older version of tools.js, but it looks like here should be the place where a new artist is born? Anyway, we get here by clicking on the Edit icon in Songs view, and then clicking on Add New... artist in the artist dropdown.

But line 339 never gets called. This is because `<option value="-1">Add New...</option>` the "-1" is a string. Then  ` if ($(source + " option:selected").val() === -1)` in line 337 does not evaluate to true because strict comparison with === is used. Replace it by ==, and a New Artist is born!

This is very fast to fix, so I'll practice the pull requests later and get some sleep now.

The Console still is complaining about the following:
TypeError: resp.lastChild is undefined       tools.js:261:38
success https://ampache.tld/lib/javascript/tools.js:261

**Comment by lachlan-00** [comment]
testing your pull now and will merge tonight

**Comment by mitchray** [comment]
Appears to have been addressed in a5ece29, reopen if that is not the case
