### ISSUE TITLE
4phun my pet project

### ISSUE THREAD

**Issue by lachlan-00** [ampache/ampache#2195]
Example my pet project at https://launchpad.net/waver (already incorporated the new Ampache API). This plays tracks automatically, without requiring user to select/create a playlist. The aim is to play randomly, without repetition until all tracks are played, then start over. There are some fine tunes to this process, for example "loved" a.k.a. flagged songs come into rotation more frequently, but you get the point.

So if you start out with fresh collection. All songs never played at that point. Then as you go through the songs, more and more will be played at least once. Then eventually you reach the point where all songs are played at least once. At that point unplayed flag becomes useless.

I know this isn't an ordinary situation from Apmache's point of view, and I could create workarounds in my client to achieve my goal. Just want to keep API calls as low as possible.

_Originally posted by @4phun in https://github.com/ampache/ampache/issues/2193#issuecomment-557939069_

**Comment by lachlan-00** [comment]
So lets split this out into steps

You want to search:
Loved
Recent
Forgotten
Unplayed

and rotate from these items depending on value of that list (e.g. 50% loved, 20% recent, etc)

**Comment by 4phun** [comment]
Yes, I'd say if you order all tracks like you said (except for loved, that's handled separately):
Recent
Forgotten
Unplayed

then for each call I'm interested in the bottom n elements of this list. n is less than 10. But there should be an element of randomness too.

**Comment by lachlan-00** [comment]
So that sounds like a different mode instead of a flag which is fine. I think playlist_generate is a good place to keep this function.

The list is shuffled and sliced by the limit before going to the xml_data class so that's pretty random.

**Comment by lachlan-00** [comment]
oh and if you don't set a limit it will get everything so you could use the large list client side if needed.

**Comment by 4phun** [comment]
OK I'm looking at the code in the meantime. Yes, shuffle and slice completely satisfies the randomness thing.

So if there was another mode which worked exactly as "forgotten", except --if I'm reading the code correctly-- would skip this part:

```
//played songs
$array['rule_' . $rule_count]               = 'myplayed';
$array['rule_' . $rule_count . '_operator'] = 0;
$rule_count++;
```

Then I believe I would be a very happy camper.

**Comment by lachlan-00** [comment]
I'll work on it from develop.

myplayed with operator 1 searches for "played by me is false."
![image](https://user-images.githubusercontent.com/1305249/69504750-47e2fa00-0f71-11ea-8f4d-72e751fb4a5b.png)

**Comment by lachlan-00** [comment]
unplayed added in develop api 400002.

This will come in to 4.1.0 once we've had some time for the new version to go out to people and collect any further issues.

**Comment by 4phun** [comment]
Man you're the best. Thanks a ton! Promise not to bother anymore. Appreciate all that you've done.

**Comment by lachlan-00** [comment]
Don't worry about it, I want the API to get more people using it so any extension that makes it better is always helpful.

There are a few new things I want to do in the API this run as well. This version I want to have scripts to monitor file changes with inotify and make updates using the python API library I made.

**Comment by wagnered** [comment]
Sorry, I didn't realize the limitation of inotify. There is a drawback to using php inotify: it is not recursive.  A large number of folders might be problematic.  A watch would need to be created for each subfolder.  The Linux command `inotifywait` can monitor recursively. It's output could probably be piped to another script.  Because it is a separate process, it shouldn't affect Ampache's performance.

I envision starting the script when the catalog is created and when the system is rebooted.  When the catalog is created, a script starts by scanning the folder tree and imports the files' metadata then when finished it starts the Linux `inotifywait` command.  Scan status could be an added column in the catalog table. Theoretically, after initial scan, the folder tree should never need further scanning. But if a large number of files are moved into the catalog path simultaneously, some events might be missed, which would warrant an update scan.

Of course this feature would be disabled in Windows.

And I'm sure the logic for the importing of metadata could be redesigned to be more efficient.




-------- Original message --------
Subject: Re: [ampache/ampache] 4phun my pet project (#2195)

**Comment by lachlan-00** [comment]
i've got this in progress with a local bin file called file_update.inc i'm going to test it out with python/shell scripts but the individual file works. (except for add. i need to reverse search by the catalog path first)

![image](https://user-images.githubusercontent.com/1305249/69523238-1b4dd300-0faf-11ea-9a77-12628f786264.png)

**Comment by a7medo778** [comment]
we need a way to get this to work with ampache radio feature 😅

it's really an intersting idea, kinda like smartplaylists i guess

**Comment by lachlan-00** [comment]
I still want to make a jukebox page. This would be the way to do it

**Comment by 4phun** [comment]
Hi

Just an idea: Another standard way of doing it is to create an "inbox" dir.
Users can copy/upload to that dir. The server monitors that dir only.
Whenever there's a new file/subdir, move it to the final storage dir and
process it there.
