### ISSUE TITLE
[Feature Request]Dynamic Smart Playlists organized by Skip to Play ratio. 

### ISSUE THREAD

**Issue by jaddel** [ampache/ampache#2288]
If we could get smart playlists based on the skip to play ratio, we had a perfect dynamic playlist, that adjusts to our momentary listening Habits.

Lets say i have 6 root playlists :

Pacing: calm, active, neutral
Style: acoustic, electronic, mixed

All my music is sorted into these lists.

Now i do a smart list from calm and acoustic, which is dynamically updating by the skip to play ratio. Then songs with a ratio of < 1 will be played more often and songs with a ratio of > 1 will be played less depending on the factor. 

If some one can recommend any other client based server, where i can do this please let me know.

**Comment by lachlan-00** [comment]
First thing is to add 'skip' to object_count. currently only 'play' recorded is only for started songs.

This would be good to add for recording stats on the server within the webui when you finish a song early.

I'm thinking if <50% of time since song started, record as skip.

**Comment by jaddel** [comment]
I think the best would be if the users can define themself what is a skip and what is a play.

I would prefer to do it in seconds, but why no offer both :)

**Comment by lachlan-00** [comment]
it might be better for seconds as the existing code makes this pretty simple to add. i can add a config setting to the config file as well to make the default (20s) changeable.

**Comment by WisdomCode** [comment]
I would also love to see this feature. Not an expert in PHP, but with a little layout on how this could be implemented I'd love to help on this one!

**Comment by lachlan-00** [comment]
I've been working on the api a lot over the last 2 weeks but this is actually not too difficult.
Off the top of my head this is the pseudo operation (in the web ui)

* play song.
* if song.played within limit (20s now)
* Write 'skip' to that song last played
* write the current play to dB as a 'play'
* if you skip that too. (Include skips when checking) write 'skip' again.
* eventually after you skip 10 tracks you let it go long enough to record a 'play'.

Right now the server will just not write the next track. It will write a track after 20 seconds have passed. Even if you skip it again at 25 seconds.

The reason why we should do the pseudo above is that you actually skip current track -1 so we should reset the count and write that the song was skipped.

The api will set this when using record_play, scrobble or stream. They should also all allow you to write 'play' and 'skip'.

I still like seconds over % in the web ui but if this is done correctly server side api clients will be able to do whatever they want. I also think I can do both based on time/% of track but first stage is the hardcoded 20s.

In the other issue @jaddel started, the skips vs plays are part 2.

Part 3 is custom time and % values

I've been a bit slow in the main repos lately but I'm trying to get the api squared away before moving into everything else. (Nearly there!)

**Comment by WisdomCode** [comment]
I'll try to keep some progress here
I've lovated the writing of a played record, all three methods work by calling external scrobbler (uninteresting for us) and calling set_played. Problem is, this only inserts the stats of this latest playtime into the database (via stats::insert), but there is no incrementing function the stats function. Where is the actual playtime evaluated and the value updated? Does anyone have an idea?

**Comment by lachlan-00** [comment]
The check is done in stats.class get_last_song
song.class is where it's decided.

I would put and extra method in stats to use the id from get_last and replace play with skip in a query
![Screenshot_20200211-084606_ConnectBot](https://user-images.githubusercontent.com/1305249/74197394-26112d80-4cab-11ea-8b6e-186817149500.jpg)

**Comment by lachlan-00** [comment]
The thing that doesn't happen here is it should also check the client when making a skip. You can play from multiple sources and Ampache doesn't check that in the get last song query

**Comment by WisdomCode** [comment]
Ah, thank you for your help, you are right, I've overlooked that function!
Also good point with the last song query, probably the user and agent should be identical to the current one to verify the playing on the same device.
I think I can work with that part, however what still confuses me is the missing increment of the played song. One should assume that this is done in the stats::insert, but nothing is incremented when calling the function nor in the function itself. Neither is it done when the post_activity is updated. 
Maybe I get it all wrong, is this maybe done by creating a new value in the SQL for every playback and therefore the number of entries in the according table show how often it i played? In that case, every entry should propably have a boolean determining whether this playback was skipped or not.

**Comment by lachlan-00** [comment]
Don't rely on ID of the rows to identify the last song. (look at date | user | agent) the search will look in the last 20 seconds for any plays by the user and if it returns an id it doesn't record the stat.

Stats::get_last_song returns details for the last play in the last 20 seconds. if it finds something we should then pass it on to a new function to update the rows that were found.

so something like 
```
if ($diff < 20 && !$this->time < 20) {
    debug_event('song.class', 'skipping the last song played ' . $previous['object_id'], 5)
    Stats::set_count_type($previous['object_id'], $previous['date'], $previous['agent'])
}
```

take out the return false because we want the song that's being checked to be imported as a play as well

**Comment by WisdomCode** [comment]
Thats how I understood it, exactly. My problem right now is not how to determine that (at least we seem to be on the same page for that), but how ampache knows how often the song has been played. There is now incremental function of any sorts, so my current theory is that there is an entry in the sql for every playback ever, is that correct?

**Comment by lachlan-00** [comment]
object_count table is where playback is stored and read from. it records all file actions like playback history

it would also need to update user_activity when setting the skip. user_activity is used for recording user actions as well but the point of truth is always object_count

**Comment by WisdomCode** [comment]
But if I get it correct, there is no direct value saving how often a song is played. Instead, the amount of entries in the object count table is counted that match the song id. Is that correct?

**Comment by lachlan-00** [comment]
yup, it counts the object_count table to get that value

**Comment by WisdomCode** [comment]
Alright, now I get it, thanks again for your patience!
So I'll put the skipped value into the object_count as a boolean. I'm going to the coding then.

**Comment by lachlan-00** [comment]
you don't need to add another column, just change count_type from 'play' to 'skip' when you find one.

then get_last_song needs to be updated to check for 'play' OR 'skip' in the sql. (as well as agent)

Then i can add skips into search.

**Comment by WisdomCode** [comment]
ah, clever, I'll do that

**Comment by WisdomCode** [comment]
Ok, I've written it together, however, it doesn't work in the slightest. This alone would get me back to the sketchboard, however, it seems like i cannot even trigger the event of skipping in under 20 seconds in the original code (there is a debug message that should be coming, but I'm not getting one). Anyone able to trigger that? because without it, there is no way I can trigger a skipping and therefore I cannot know whether my code is actually functional.

**Comment by lachlan-00** [comment]
do you have it up somewhere? i can start working on this now

**Comment by WisdomCode** [comment]
like stated in my ps, it is in my fork. However, there are some tweaks I would like to make (like the percentage instead of the 20 secs). But like I said, I am confused about the lower than 20 secs not triggering at all in my server, so maybe check if you have issues with that as well before checking functionality on my code.

**Comment by lachlan-00** [comment]
cool, grabbed the changed files. ill start playing about with your commit and i'll put up anything i change.

**Comment by lachlan-00** [comment]
here @WisdomCode use these in your fork.

still have to update the album and artist row in object count and a few other things but this is at least a working start for you.
[changes.zip](https://github.com/ampache/ampache/files/4189690/changes.zip)

**Comment by lachlan-00** [comment]
things to do for this
* update the album/artist as well as the song in object_count
* delete or update the user_activity table
* check out the other functions like is_already_inserted and how this affects the stats.

That's just off the top of my head but i've got to go, I'm flying to sydney for work for a few days so if you make a pull request after playing around with these i can fix more up from my hotel.

i'll need something to do!

**Comment by jaddel** [comment]
**please correct me if this is the wrong way bring this in, but here is an update about the general idea:**

The general idea it that if one has large playlists that one listens to often, it would be nice to filter out the songs that have already been played or skipped in the recent past. To further refine this, the period for which each song is filtered out can be varied by how much one likes the song. This would mean that one's favourites are being played more often while songs that one likes but doesn't want to hear every day are being played more rarely. 

To filter out a song, one needs to know when it was last played or skipped to define something such as "not played in the past two days and not skipped in the past four days"

To define how much a song is liked, two approaches are possible: either manually, by giving each song a star rating or by automatically by operationalizing liking as a quotient of play count over skip count. The latter approach means that no active input of the user is required and that liking can organically vary over a period of time. 
For this, the skip and play count of a song are required. Ideally, these counts are specific to each playlist, as one might like a song better in one playlist as opposed to another depending on how well the song fits the rest of the playlist. 
A resulting filter might then be: "for songs with a play/skip ratio > 2: not played in the past four days and not skipped in the past eight days; for songs with a play/skip ratio > 4: not played in the past two days and not skipped in the past four days"

**Comment by WisdomCode** [comment]
@jaddel For now, we try to provide a value in smart playlists that can work either by a ratio or a skipping rate (skipped below x times, ratio below 2, whatever). I'd advocate for integrating both, as it is rather easy to create such database requests. "Not skipped in x days" is no problem as well. The only reason I see against it is offering too many options, which I would not advocate for in such a complex and multi-supporting project like ampache. So, sounds good to me. Just let us provide the infrastructure first 😄

**Comment by WisdomCode** [comment]
@lachlan-00 Thanks again for looking into it! I will probably do a bit less the next two days, but I will look at your code and refine it further. 
So you think we should also set a skip to albums and artists? This sounds to me a bit counter intuitive, as we are only skipping the song, not the entire album or the artist. For example, skipping Pink Floyds "Meddle" doesn't mean I don't want to hear their "Echoes". But for what its worth, this would be saved then as information. Basically, the skip ratio of albums and artist would give you how good an overall album/artist is, which is kind of interesting, but of no use when creating a playlist, as the artist or album would not keep their integrity (for example, "Dark SIde of the Moon" would have a pretty good skip ratio, but due to the choosing in the smart playlist, it would be mixed in with other good albums which don't exactly keep the theme of the album, therefore rendering the overall rating of the album invalid).
Also, yes, the activity table, together with an adjustable skip time are my next goal, so simply remove it from the table would be the way to go, right?
Checked on them already, the other functions only read information, but do not write it. The only thing left there are the external scrobbler and that the song is then set as played. I would count those songs as actually played, as you listened into them and decided to skip, so they are not new to you, right? And external scrobblers should still get the same info I presumed.

**Comment by WisdomCode** [comment]
@lachlan-00 Alright, I looked through your Code, looks good, however, I'm a bit confused about the SQL request changing for setting to skip. You use the object id instead of just the id. You have the structure of the database in your head more clearly than I do of course, but wouldn't it be more secure to use the key of the entry to make sure we don't accidentally set other values? 
If not, in the song.class, you still call the function with the id value (the way I wrote it basically), which will very likely not work, or am I missing something? I can change it of course, just making sure I understand what you did.

**Comment by lachlan-00** [comment]
Object_id might just be late night confusion.

I forget what I was doing then but play around as it should be the object_count I'd as you said

**Comment by WisdomCode** [comment]
@lachlan-00 ok, nvmnd, I've got it running now, it was actually necessary because the entry given from last_song is not an object_count but a song entry, meaning there is no id matching. However, it works in my current setup, at least in the browser. Having problems with dsub though, but more on that when the rest is working.

**Comment by lachlan-00** [comment]
Ah yes! Haha limit 1 desc?

My laptop doesn't have a full library so I didn't notice that yet

**Comment by lachlan-00** [comment]
Subsonic does have a check in there somewhere. I put it in the subsonic code to add the client but only tested in the browser.

**Comment by WisdomCode** [comment]
@lachlan-00 exactly, date and limit 1, otherwise there would have been an unpleasant suprise 😄 

I updated my fork again, not a great function, now the webinterface actually shows how often an object gets skipped so you don't have to get into the db all the time... It will be shown when you have the play counter activated to be shown as well. Probably we need another setting or at least rename this one in the future, but I didn't want to decide that, also because I found the structure of those values a bit complicated in the code. This should do it for now. Doesn't show for podcasts etc yet.

So to elaborate again on the user_activity, you say a skipped song shouldn't be shown there? In that case thats what I'm doing next. 

And lastly, I am still not convinced about a skip counter for entire albums or interprets. Maybe you could explain why this is of use? See 3 posts from me earlier on why I think it's not really a good idea.

**Comment by WisdomCode** [comment]
@lachlan-00 Well, I'm afraid I know now why DSub is not working. It's not sending scrobbling data that often. In fact, it sends it only after a certain time has passed either half the song or 4 minutes, (check it out [here](https://github.com/daneren2005/Subsonic/blob/9dc25397072fd00ea73bdbeed9b46afdce366349/app/src/main/java/github/daneren2005/dsub/service/Scrobbler.java) Line 26ff)
This makes it basically impossible to get back info on whether the song is skipped or not sadly. I'll open an issue there to ask if this could be changed or made optional. It's only two lines, I could do it myself, but if its somehow disturbing last.fm, that would complicate things greatly...

**Comment by WisdomCode** [comment]
Or wait, we could simply subtract that amount of time from the date, right?
So basically when a request comes from the subsonic api, it will have to be delayed backwards a bit. That could be done by recognizing the agent.
I'll try that!

**Comment by lachlan-00** [comment]
In subsonic it should go into now_playing. You might be able to query that when a new song starts. You might miss that because it cleans the row when the song is finished

Subsonic makes a unique now playing row with the username and clears when the song is finished so you could select into object count from now_playing.

There will be a new setting for this but you can just focus on the functions until later. I'll add in config options and work out that part.

**Comment by WisdomCode** [comment]
now_playing? Interesting, I'll take a look if I can find something that helps. Is that something in the database or available as a function?

Another update, I added the variable skip threshold (with a local variable we can later replace by one from the settings). It takes a number, betweens 0 and 1 as a percentage of the song, all numbers above 1 are interpreted in seconds.
Additionally, the user_stats get cleared now. 

So I think, depending on what your stand is on the skipping of albums and interprets, we can start with the actual smart playlist now. I looked around a bit and it seems to me like the search class is the place for that, but maybe you can explain a bit where the interface gets its choosing options.

**Comment by lachlan-00** [comment]
Now_playing is a table.

Skip should only be for song but delete album and artist if the date/agent/user line up. Object count can put up to 3 rows in so insert should return false when a skip is sent with album or artist

**Comment by WisdomCode** [comment]
Alright, I'll try to find out how it is accessed, from there we can surely find a way to trigger the rest.

So you want me to remove the according object_count entry entirely? I can see that.
Is album or artist something that is written into the user activity, or is this solely derived from the 'latest songs'?

**Comment by lachlan-00** [comment]
Song is written to object_count and user activity.
Album and artist are just written to object_count.

If we write skip song to object_count don't do the insert for album, artist.

There are 3 lines of stats::insert to do this. In song::set_played.

To me that says look for where set_played is set and just write the skip instead of set_played

**Comment by WisdomCode** [comment]
No, thats not how this is gonna work, but I've got it now. We set to skip the LAST song, not the one thats currently worked on with set played. Therefore it has to be done in the method that sets the song to skip.

**Comment by lachlan-00** [comment]
Oh yeah I forgot. Well then it definitely has to delete the album and artist rows.

**Comment by WisdomCode** [comment]
Tested, working and pushed. But that will be it for today. Next the smart Playlists options then? Maybe you could tell me where they are saved so I can start on them tomorrow.

**Comment by lachlan-00** [comment]
Keep search separate from this. It needs to go in first and search can go after

**Comment by WisdomCode** [comment]
ok, so I implemented a way to recognize the subsonic songs with now_played, it was suprisingly easy and made the code actually shorter. It's also merged and works on my server like a charm. As this seems to be everything except the playlist itself (which you wanna have seperate) and the settings (which you wanna look into) I requested a pull under #2299

**Comment by lachlan-00** [comment]
okay i'll move over to the pull request until i'm ready to add it in to search

**Comment by jaddel** [comment]
Hello Devs, may i ask how is the status on this and if it has already added to the docker container? 

Thank you!

**Comment by lachlan-00** [comment]
Not in search yet. I'm working on some code quality right now.

It's not a big addition but I'm not looking at the search class yet

**Comment by jaddel** [comment]
> Hello Devs, may i ask how is the status on this and if it has already added to the docker container? 
> 
> 
> 
> Thank you!

**Comment by lachlan-00** [comment]
i'm going to skip this search addition for 4.2.0 it's a bit more time consuming than i want it to be for this period

just need to spend more time on it to do it correctly

**Comment by jaddel** [comment]
Ahoi, any news on the skip count? :)

**Comment by lachlan-00** [comment]
The good news is I cut down on code issues so hard this is the season on new features

**Comment by jaddel** [comment]
> The good news is I cut down on code issues so hard this is the season on new features

well that sounds promising :)

**Comment by lachlan-00** [comment]
I've got this in as (stream/skip)*100. The value then is a percentage of how valuable the ratio is.

* ```0``` = no plays, maybe some skips
* ```> 0 + < 100 =``` skipped more times than played
* ```100``` = 2 plays, 2 skips
* ```> 100``` = played more than skipped.

![image](https://user-images.githubusercontent.com/1305249/89840722-554e1c00-dbb4-11ea-9abb-3e4a2497ed3d.png)

This will go in as a numeric search called something like played/skip ratio
![image](https://user-images.githubusercontent.com/1305249/89840984-15d3ff80-dbb5-11ea-9948-598feea916bf.png)

does that cover everything?

**Comment by lachlan-00** [comment]
added in 26f3cca0b

**Comment by jaddel** [comment]
Looking good, thanks for updating me! 
Do you know how cases where some plays, but zero skips occurred will be handled? I hope diving by zero will not cause issues. 
Thanks again for you efforts and kind regards,
Max

**Comment by lachlan-00** [comment]
you just end up with a ridiculous percentage.

because I have a really old database from 2005 I get scores I'm the 50000 plus range

**Comment by jaddel** [comment]
^^
seems not to be a bad base to start from. :)

**Comment by lachlan-00** [comment]
This is why I put so much time into Ampache it's been a big part of my music life for years.

If you keep your searches within the 0-100 rules it's pretty simple.
I've also made > 100 and > 1000 to see some of the really popular ones.

Later I'm going to add the ability to ignore skips and keep this option out of the UI but I think this should cover all you want now so let's close it and you can enjoy a new feature. :)

**Comment by jaddel** [comment]
It should be in the current master 4.2 right? 
I don't see the ratio anywhere in the dropdown menus?

**Comment by lachlan-00** [comment]
> It should be in the current master 4.2 right?
> I don't see the ratio anywhere in the dropdown menus?

it's still in develop right now but i'll be doing some more fixes to master in probably another week or two.

Before it goes into master i want to allow people to ignore skips in the config which will hide this option. shouldn't be too long if you want to use master as i've got a few more bugs to fix.

**Comment by lachlan-00** [comment]
i've actually just decided to hide it behind the show skip preference
![image](https://user-images.githubusercontent.com/1305249/90588311-a72f1b80-e21e-11ea-9ca1-413e847d2087.png)

i'll be updating master in probably a week to resolve a CVE

**Comment by jaddel** [comment]
> I've got this in as (stream/skip)*100. The value then is a percentage of how valuable the ratio is.
> 
> * `0` = no plays, maybe some skips
> * `> 0 + < 100 =` skipped more times than played
> * `100` = 2 plays, 2 skips
> * `> 100` = played more than skipped.
> 
> ![image](https://user-images.githubusercontent.com/1305249/89840722-554e1c00-dbb4-11ea-9abb-3e4a2497ed3d.png)
> 
> This will go in as a numeric search called something like played/skip ratio
> ![image](https://user-images.githubusercontent.com/1305249/89840984-15d3ff80-dbb5-11ea-9948-598feea916bf.png)
> 
> does that cover everything?

Hey Lachlan,
I found the #skipped and #play in the search. Is the skip/play ratio available now? 

Br. Max

**Comment by jaddel** [comment]
I just gave it a try again. It's there now, thanks a lot for adding this.
