### ISSUE TITLE
Albums are getting separated based on track release year

### ISSUE THREAD

**Issue by a7medo778** [ampache/ampache#2326]
hey guys, i have 2 questions
1- in some of my albums the year tag isnt correct for the tracks in it, so the album tag is correct, but some tracks have year tag and some done
before i upgraded to the latest 4.2 this used to be fine, but now i am seeing 2 instances of the albums with the only change being that year tag

i checked the album grouping options, didn't see anything related

(another side question is that i am unable to change the tags from ampache, even in the gui i change, click save, refresh and its the same old value. am i missing anything? )

**Comment by lachlan-00** [comment]
Year is a column in the album table which is why they are being grouped by year.

I don't agree that albums should have multiple year values as well. All music databases (discogs, musicbrainz, etc) follow this process. And there is actually no official tag for songs having a year.

Compilation and mix tapes that are released with multiple years should actually be corrected to their release date.

For example one album released in 2000 and rereleased in 2020 are separated as unique objects. Even though they are technically the same thing they are 2 separate releases.

A best of compilation or unofficial mix using tracks from 1980, 1984 and 1989 is released in 1997. The album year is 1997.

**Comment by a7medo778** [comment]
so how can i resolve this ?

**Comment by kuzi-moto** [comment]
We don't really have an official best method, but the one I highly recommend is using a tool such as [beets](http://beets.io/) or if you're a GUI type, [MusicBrainz Picard](https://picard.musicbrainz.org/) to run through all your music to ensure that it's tagged properly. Ampache works best when music is tagged properly and the aforementioned tools are great at that.

Afterwards run a catalog update.

**Comment by lachlan-00** [comment]
You can change in the ui but automated tools like picard from musicbrainz are wayyyyy simpler.

I will be looking at extending the ability to edit tags in the api and Ashot will be able to implement that in the new client ui.

**Comment by a7medo778** [comment]
so right now when i click "edit" in the album properties, and it shows me all the metadata files editable
it doesnt actually work ? i am pretty sure i used to edit those fields on albums and tracks once

**Comment by wagnered** [comment]
As @lachlan wrote:

> Year is a column in the album table which is why they are being grouped by year.

This means there is a one-to-many relationship, albums to songs.  I remember this being the way it was in Ampache versions 3.* when I was working on Ampache.  I think this was left over from the previous ID3V2.* versions which had only TYER to record a date.

Id3v2.4 has both TDOR, Original release time and TDRL, release time, which would work in your favor, but probably would take some effort to implement.

I would consider this a feature request.

BTW: The ID3v2.4 group suggests using TCON with "RX(remix) or CR(cover) to deliniate the original from the later published work.

null

**Comment by juanalexei** [comment]
I'm using year as a track year, more like record year (which for my use, the musical one, is much more interesting) than release year. Unfortunately iTunes does not have another year tag. Also id3 did not specify what year was for, so I guess that's why there so much confusion. I'll patch the catalog class for my use as I can't and don't want to enforce my view ;)

**Comment by mitchray** [comment]
> so right now when i click "edit" in the album properties, and it shows me all the metadata files editable it doesnt actually work ? i am pretty sure i used to edit those fields on albums and tracks once

Closing due to original issue being resolved, but if this is still happening in the most recent version open a new issue
