### ISSUE TITLE
Artist Picture not always showing

### ISSUE THREAD

**Issue by Meinux** [ampache/ampache#2338]
### Describe the bug

After upgrading ampache to newest release the artist art is not showing correct. 

### Expected behavior

It should show every artist picture. 
### Screenshots

![Bildschirmfoto vom 2020-03-30 11-31-18](https://user-images.githubusercontent.com/58363515/77897795-730c8b80-727a-11ea-8fc4-1fb0c2dc95b5.png)

## Environment

* Ampache version: 4.1.1
* Web server + version: Apache 2.4.29
* Server operating system: Ubuntu 18.04
* Client operating system:Any browser and play:sub (ios App)

### Client type

* Web Firefox 74
* play:sub 4.7

## Settings
[ampache.cfg.php-github.txt](https://github.com/ampache/ampache/files/4401937/ampache.cfg.php-github.txt)

**Comment by yusaiku** [comment]
I have the same Error Version 4.1.1 and nginx 1.16

**Comment by AshotN** [comment]
I have a similar problem working with the API, where it doesn't pull the artist information until I open the artists page on the Reborn Interface.

Try opening the artists page and then checking if the image gets populated.

**Comment by lachlan-00** [comment]
Art search is generally broken, especially for all the online gather types.

gather_lastfm - Looks broken because last.fm removed images from the api as far as i can tell. the api details are there but the calls don't return any actual art.

This image means it 'Found' the artist using lastfm and that's what their api returns
![image](https://user-images.githubusercontent.com/1305249/78219091-36eb5c00-7502-11ea-8aad-ff4bb74ef4a4.png)

gather_google doesn't work because the search page has changed.

i don't think there are any other configured methods for pulling art.

**Comment by lachlan-00** [comment]
the audiodb has a field for strArtistThumb
that might be worth looking at

**Comment by lachlan-00** [comment]
i also want to be able to define an artist cache folder and use that.right now art from files is only searched for albums.

**Comment by Meinux** [comment]
Thanks. 
Can I help in anyway?

**Comment by xekon** [comment]
@Meinux are you a coder? my idea was to add the ability to use locally stored images for artist, I posted about it here: https://github.com/ampache/ampache/issues/2304

**Comment by Meinux** [comment]
Hi, 
no iḿ  not a coder. 
But i would like to improve ampache :-)

**Comment by AshotN** [comment]
Submitting issues is very helpful. If you'd like you can join our Telegram chat and whenever I need some testers for what I'm working on you can help with that.

**Comment by Meinux** [comment]
Hi, yes that would be nice.

**Comment by mitchray** [comment]
Closing as version referenced is 4.x

Please reopen if this still affects version 6+
