### ISSUE TITLE
trouble with path name on mac when adding local catalog

### ISSUE THREAD

**Issue by lipalong** [ampache/ampache#2381]
When I try to add a local catalog from my mac via the Ampache web client, I get "The folder couldn't be read. Does it exist?" I've tried /home/Users/(user name)/(file path...), and /(user name)/(file path...), and /(file path). Am I entering it wrong? Is it a permissions thing? Do I need to change something other than the settings below?

<img width="267" alt="Screen Shot 2020-05-09 at 2 25 46 PM" src="https://user-images.githubusercontent.com/13445722/81485330-1f8a4780-9201-11ea-9cb8-761638ac0536.png">

**Comment by kuzi-moto** [comment]
I think for Macs it's `/users/username/...`? I don't have one at the moment to test, but that's what I've seen from screenshots. Additionally you should be able to use the "get info" option when right clicking on the music folder which should show the full path.

**Comment by lipalong** [comment]
I tried "/Users/(user name)/(file path...)" and I still got "The folder couldn't be read. Does it exist?"

**Comment by wagnered** [comment]
Hello @lipalong,


The ampache server expects to see the full path starting at the root.  If /home is at the very top (root) of the file path, ampache has to know that.

What is the document root of your web server? That has to match the path to your music.  Otherwise the webserver will not permit ampache to access it.

Webserver processes have a user and group as owner of the process.   If the user of the webserver process doesn't own the folder path it can't access it.  The folder path would have to be given the "everyone" permission for read, write and execute.  The problem with doing so is that anyone can access the music files and do harm.

How you do this on the mac, I don't know.  You should be able to become superuser and make the changes. Also you give us very little information such as what is the web server (apache?)


For testing purpose, I wold start my webserver with my own user name and the music path would be my own home folder.

**Comment by lipalong** [comment]
Thanks!
