### ISSUE TITLE
Can Spotify art search return more results?

### ISSUE THREAD

**Issue by barcoboy** [ampache/ampache#2522]
Is there somewhere that I can adjust to get more art results returned from Spotify?  If I set art_order = "spotify" in ampache.cfg.php  to only download art from Spotify, for artists I usually get up to five or so images returned, and that's okay, but for albums, I always get just one or two, where if I do a search for albums in Spotify directly or using the API and Curl, many more results are returned.

**Comment by wagnered** [comment]
Hello @barcoboy 

Actually according to the Spotify documentation, what is returned is: "The cover art for the album in various sizes, widest first". This may be as few as one and I rarely saw more than three. This is what I experienced when the album art is edited on the album details page.

I'll take a look at it.

**Comment by wagnered** [comment]
It just occurred to me: are you looking for covers for different releases (US vs GB, cd vs 12")?  Possibly Musicbrainz can do this, but I've not tested it. If not, could you give me an album name and artist that gives many cover image returns for a give album name? The artist name must be included to filter out unrelated items. I have a php cli script I can test it with.

**Comment by lachlan-00** [comment]
If there's a limit it's not 5 it could just be that the search itself only found 5 images.

I thought I set a limit somewhere of like 20+ but I can't see it from my phone

**Comment by wagnered** [comment]
I just checked the code  `public function gather($options = array(), $limit = 0)` in the Art class and as can be seen, it has a parameter for passing in a limit. But two places that call the function, arts.php and catalog.class.php don't include a limit (ie: ` $images = $art->gather($options)`.  Also, I forgot to account for a limit when working on the `gather_spotify` code. 

I thought I remember a limit being set in ampache.cfg.php, but I couldn't find it in the file or on the Ampache Debug page.

Also,   when I designed the function, I assumed that there would be only one album/artist combination returned in a search in Spotify.  I'll rethink that and  assume otherwise, but it would help having  an artist/album combo that will definitely return more than one item.

**Comment by wagnered** [comment]
The Spotify API defaults to a limit of 20 or maybe it's the composer package.

Anyway I'm just about ready to submit a PR for the fix.

**Comment by barcoboy** [comment]
Sorry for the delay in getting back to this, things have gotten busy for me the past couple of days.

Here is an example of an artist and album with two different covers available on Spotify:

Artist: Vince Guaraldi Trio
Album: A Charlie Brown Christmas

The two albums returned are the original and a 2014 remaster.

Here is the query I used for the search:

curl -X GET "https://api.spotify.com/v1/search?q=artist:vince%20guaraldi%20trio%20album:a%20charlie%20brown%20christmas&type=album" -H "Authorization: Bearer  <access tolken>"

I'm also wondering is searching for an album cover including the artist a requirement?  True it does limit the results returned and will be most apt to return the correct cover, but perhaps the user doesn't care if the image displayed is the actual cover of the album and would rather have a larger number of covers to select from.

Maybe a config setting could be used to toggle if the artist is included as part of the search?  And possibly another config option to adjust the limit on the number of search results returned?

**Comment by wagnered** [comment]
Both suggestions will be included.

**Comment by wagnered** [comment]
But that means I gotta change the lastFM search algorithm:  "artist" is hardcoded into it.  Oh well.

**Comment by wagnered** [comment]
Oops can't do that. The lastFM api requires the artist name for the album search.

**Comment by wagnered** [comment]
Is the number "46" available for  the config file in this PR I'm ready to do?

**Comment by lachlan-00** [comment]
no changes are in config since 45 so 46 is free for this

**Comment by wagnered** [comment]
Ok.

Another question on topic.

When the setting icon on the album image is clicked,  the logic goes out to gather images even before given a chance to check/alter the search data.

I want to change the logic to display the dialog first.  The reason is that I added a spotify filter selection to the dialog.  It shows only when spotify is in the `art_order`Switch.  Also the admin should be given a chance to modify any data before issuing the search.

**Comment by lachlan-00** [comment]
I think that would be fine, add in a search/refresh button?

**Comment by wagnered** [comment]
I don't understand.  The dialog has "get art /cancel buttons the same as before.  The only difference is that now it doesn't go out and search for art before the "get art" button is clicked.

**Comment by lachlan-00** [comment]
crude i know but now because it's changing behaviour a button to refresh the page and a button to set the art
![image](https://user-images.githubusercontent.com/1305249/92557948-cd415c00-f2b0-11ea-94c2-f04274a733e9.png)

**Comment by wagnered** [comment]
Maybe it's because I don't see the whole picture yet, but I still don't understand why a third button is necessary.  The way it's been done seems very crude to me.  This is probably because of the loading of the gathered images before
 the dialog appears.

I'm still trying to understand the cancel function: `onClick(Navigate to(burl)`. Burl being a base64 encoded url. The encoded url isn't used in any other code I could find, having done a grep of "NavigateTo".

And there are two(2) `NavigateTo(url)` functions in header.inc.php:

```      
 function NavigateTo(url) // line 115
    {
          window.location.hash = url.substring(jsWebPath.length + 1);
      }
```
```
function NavigateTo(url) // line 137
     {
         window.location.href = url;
     }
```
The several languages i'm familiar with don't permit this in the same scope.

I've been afraid to do  a forensic examination of Ampache's code and now I understand what I got myself into.☹️

**Comment by lachlan-00** [comment]
you can set this now!
