### ISSUE TITLE
Flac audio support

### ISSUE THREAD

**Issue by arnoldvdm** [ampache/ampache#2551]
Hi all,

I would like to use the FLAC audio format.
Maybe it's a good suggestion to add FLAC support.

Thanks in advance.
Arnold

**Comment by AshotN** [comment]
Ampache supports FLAC. I use FLAC. What issue are you having with FLAC?

**Comment by arnoldvdm** [comment]
Thanks,
I clicked play and it didn't play.
Maybe it's because the file size is slightly larger. 77 MB FLAC instead of 5 MB MP3.
Don't know why it didn't work but I've already converted the files.

**Comment by AshotN** [comment]
I would check the browser console for errors.

**Comment by lachlan-00** [comment]
you'll need to expand on the issues you have but flac is definitely supported and working in all areas.

It's usually an issue with transcoding / ffmpeg /config when these sort of playback issues arise

**Comment by philiposD** [comment]
I encounter the same issue

**Comment by freitagdavid** [comment]
Same issue here I get this console output when I try to play flac files. I've been tinkering with this issue off and on for about 3 years it's the only thing that's kept me from using Ampache.
[10.0.0.101-1685726749998.log](https://github.com/ampache/ampache/files/11639004/10.0.0.101-1685726749998.log)

**Comment by lachlan-00** [comment]
Some people have trouble with chrome/edge and flac files but it's not something code related i think i can change to fix that.

**Comment by lachlan-00** [comment]
I think this is fixed in
ampache6 with d37bda7d4
ampache5 with 30c958574
develop with 17903bca7

if you want to replace your jplayer files with the raw files this should fix you
```
public/lib/modules/jplayer/jquery.jplayer.js
public/lib/modules/jplayer/jquery.jplayer.min.js
```

https://raw.githubusercontent.com/ampache/ampache/d37bda7d4f00280810e4338903f94a50b53fe5b2/public/lib/modules/jplayer/jquery.jplayer.js

https://raw.githubusercontent.com/ampache/ampache/d37bda7d4f00280810e4338903f94a50b53fe5b2/public/lib/modules/jplayer/jquery.jplayer.min.js
