### ISSUE TITLE
How does the Podcast feature work

### ISSUE THREAD

**Issue by memen45** [ampache/ampache#2591]
Looking at the podcast methods described in the API it is unclear to me how the functionality could be used. I could not find anything regarding podcasts in the UI. Key questions I have:

- does the episode list `podcast_episodes` contain all existing episodes of the podcast or only the ones that are downloaded to the Ampache server?
- what is the sync strategy followed for the `update_podcast` method? Only latest episodes for each podcast? Or all episodes that have not been played?
- how can a client obtain and update listening progress (like 'mark as played' or the minute mark if not finished yet) from the server?

Also the [Wiki](https://github.com/ampache/ampache/wiki/Podcasts) is not very clear about this.

**Comment by kuzi-moto** [comment]
Podcasts are definitely an area that could use more love. Though I don't know much about the internals, @lachlan-00 can probably assist when he's up.

**Comment by lachlan-00** [comment]
I'll answer all this soon in better detail (5mins awake) but 

podcast_episodes are all episodes on the server including not-downloaded. doesn't  include remote episodes without a sync

update_podcast is an api version of catalog update using -a (add). sync episodes list and download the new ones if you set that in your preferences.

there is not a good bookmarking/location of current playback in ampache for anything which is annoying but is a todo

I'm looking at a new table to do that where a client can just send a bookmark for any playback type and retrieve it based on client name

**Comment by lachlan-00** [comment]
> does the episode list `podcast_episodes` contain all existing episodes of the podcast or only the ones that are downloaded to the Ampache server?

it will select everything in the Ampache server. if you haven't done a sync there may be remote episodes missing but this method returns everything, because i usually grab all episodes immediately (settings below) the server will generally always have playable files


>  what is the sync strategy followed for the `update_podcast` method? Only latest episodes for each podcast? Or all episodes that have not been played?

sync of new episodes
![image](https://user-images.githubusercontent.com/1305249/97238464-37986680-1835-11eb-802c-79398ba6ac09.png)

then add episodes to the server
![image](https://user-images.githubusercontent.com/1305249/97238533-5860bc00-1835-11eb-9dfc-ed9b41aea223.png)

then after importing all the new episodes, download them
![image](https://user-images.githubusercontent.com/1305249/97238586-6dd5e600-1835-11eb-9ad1-761339cedd97.png)

There are config options separate from the api that are important. 
I configure these to 0 to sync and keep everything in the RSS feed.
![image](https://user-images.githubusercontent.com/1305249/97238632-94941c80-1835-11eb-9e7a-eab42f1ad22e.png)

i think that old pending/unsynced episodes will **not** be downloaded, only new episodes from the last sync. i should probably extend that to allow grabbing all missing episodes.


>    how can a client obtain and update listening progress (like 'mark as played' or the minute mark if not finished yet) from the server?

The current database does not allow podcast playback recording. (now playing recently played, etc) I did put in but reverted before 4.2.3. this will change in the next database updates and Ampache 5.

as above i'll be implementing a bookmark table with api methods to save this. something like:
``` Api::bookmark_create('podcast_episode', episodeid, 'clientname', userid, timeinseconds)```

which can then be retrieved by a client.
```Api::bookmark(('podcast_episode', episodeid, 'clientname', userid)```

which we will allow clearing
``` Api::bookmark_delete('podcast_episode', episodeid, 'clientname', userid)```
``` Api::bookmark_delete_all('clientname', userid)```

> Also the [Wiki](https://github.com/ampache/ampache/wiki/Podcasts) is not very clear about this.

I just read the wiki and there's clearly need to improve that, i've spent a lot of time on just getting methods into the api but will be able to write a lot more now.

I hope this explains what you want to know. It can be hard when you don't have intimate knowledge of the code so let me know what else i can expand on as i would really like to make better documentation for everything. (forever in progress)

**Comment by lachlan-00** [comment]
i also see we do set if an episode is played but don't actually put it in the all. rectifying that now

**Comment by lachlan-00** [comment]
835b4107c has new methods for bookmarking playback to objects per client.

* Api::get_bookmark (See if you've previously played the file)
* Api::bookmarks (List all bookmarks created by your account)
* Api::bookmark_create (Create a bookmark to allow revisting later)
* Api::bookmark_delete (Delete a bookmark by object id, type, user and client name)

I'll be adding a user_queue table to allow saving current playlist by client as well.

**Comment by memen45** [comment]
Thanks for your elaborate answer! If I understand correctly, the client cannot know whether an episode is downloaded to the server or not, since this is set in some config file on the server. That raises the question what would happen if the stream method is called for some podcast id? Does it always provide a stream?

With regards to the bookmarking, I also looked at the gpodder.net API and that seems very thought out: [Episode Actions](https://gpoddernet.readthedocs.io/en/latest/api/reference/events.html) (maybe - parts of - this API could be implemented in Ampache?). Main issue I see is that a device might be offline, then records some play time event, then comes back at the server some time later to update the bookmark. However in the meantime the user might have finished listening to the podcast already, and the new bookmark would be overwritten by the old offline bookmark. The gpodder.net API solves this by requiring a timestamp to be sent with the bookmark_create request.

**Comment by lachlan-00** [comment]
in the response you have a state
```
<state><![CDATA[Completed]]></state>
```

pending means not on the server.
completed is downloaded

**Comment by lachlan-00** [comment]
you can send a timestamp in record_play to set an offline play later

**Comment by lachlan-00** [comment]
sorry for being on mobile and many comments but ill also take a look at the podder api as well to see what else can be included

**Comment by memen45** [comment]
> 
> 
> you can send a timestamp in record_play to set an offline play later

I could not find this in the docs (yet?). However, the problem is more with the bookmarking you proposed. Let's say the user listens an episode up to the 5th minute on an offline device. Then, before the device could sync this progress to the server, the user listens to the rest of the episode in the browser. Now the server will have the correct progress (`100%`). If the device would sync with the server later on, the progress would be set to 5min, since there is no way of knowing which of the two (server or device is actually outdated. Is that correct?

**Comment by lachlan-00** [comment]
* you're right record_play doesn't support a timestamp (it's scrobble). i'll add that.
* if you listen in different places your client name will probably be different as well so that requires the ability to not include client and just the user.

my general thought is that when you listen and stop you will either come back to it later, or continue on a new device. (eg in the car then at your desk) so at a minimum the above 2 would make that easier.

In most cases i wouldn't really consider offline for anything other than future scrobbling/plays at this stage due to extra complication.

**Comment by memen45** [comment]
Ah okay thanks. I looked at the code for the bookmarks class and I see that `update_date` is already stored, but always set to current server time(). I think if the update_date was an optional parameter instead, it could solve the problem already. For now I hope the `update_date` property is at least returned from the 'get_bookmark' method, such that a delayed synchronization will not override newer bookmarks.

Thanks for the additions and looking forward to see them in the next version!

**Comment by lachlan-00** [comment]
yeah the current bookmark class is very limited. besides subsonic it wasn't really used so I'll be expanding on it for sure. i also need to get a current queue saved as well

**Comment by TheNomad11** [comment]
Thanks for working on the bookmarking issue. Just installed Ampache, everything working fine and less ressource hungry than Airsonic and others. I am listening to lots of podcasts and audiobooks, and am therefore looking for a way to resume playback later on a different device. Thanks!

**Comment by lachlan-00** [comment]
> 
> 
> Ah okay thanks. I looked at the code for the bookmarks class and I see that `update_date` is already stored, but always set to current server time(). I think if the update_date was an optional parameter instead, it could solve the problem already. For now I hope the `update_date` property is at least returned from the 'get_bookmark' method, such that a delayed synchronization will not override newer bookmarks.
> 
> Thanks for the additions and looking forward to see them in the next version!

@memen45 i think that `update_date` is the correct one to work on. i'll get on that now

**Comment by lachlan-00** [comment]
will be making this optional today

**Comment by lachlan-00** [comment]
bookmark edit in api5&6 is optional. in subsonic it doesn't look to be an option so closing this now
