### ISSUE TITLE
Installation on hosting

### ISSUE THREAD

**Issue by hopfrogsalerno** [ampache/ampache#2639]
I am trying - without succeeding - to install Ampache in a subdomain of my main site. I have a VPS managed with a Control Panel (Hestiacp) and root access. 
I found endless guides but none related to the installation on a hosting (on a dedicated server or VPS obviously I have no problems). Can someone tell me if it exists and where to find it? Or tell me how to proceed? 
Thank you

**Comment by hopfrogsalerno** [comment]
No, Hestiacp does not contain the automatic installation of Ampache (such as Softculous, etc.). On a "clean" machine I can do the installation but on the VPS with the panel I can not install in sub.domain.ltd. If I copy the Ampache files from the clean machine to the subdomain I have "Access Denied" if I place myself in "cd sub.domain.ltd/public_html" and try the installation nothing happens. I don’t know how to do it. Is there a specific guide for hosting? Thank you for your answer

**Comment by stebe** [comment]
For permission denied, if you copied the files as root then you need to change ownership of the ampache files and subfolders to the web server user.

**Comment by kuzi-moto** [comment]
Unfortunately we likely don't have any guides for hosting, as due to the number of different control panel software it would be pretty challenging to create a "one size fits all" guide, and likely a guide would have to be created for each software. 

On looking at the Hestia CP documentation, it appears that you can configure templates per each domain. It would be good to know which templates you're using (Nginx vs Apache, and with/without PHP FPM). if you put a minimal 'index.html' file in the public_html folder for your subdomain, would it allow you to view at least that file?

Also, what stebe said about permissions.

**Comment by lachlan-00** [comment]
Your VPS probably has Softaculous?

http://softaculous.com/

They do app installers and are pretty good at keeping Ampache updated. The official demo pages are on a cPanel that has the app installers
![Screenshot_20201205-090823_Firefox Nightly.jpg](https://user-images.githubusercontent.com/1305249/101224120-7b567980-36d9-11eb-81a6-23a25a4bb680.jpg)

**Comment by hopfrogsalerno** [comment]
OK, Stebe! The indication is right (I hadn't thought about it). Thanks

**Comment by AshotN** [comment]
> OK, Stebe! The indication is right (I hadn't thought about it). Thanks

If your problem isn't resolved feel free to re-open this issue.
