### ISSUE TITLE
Question: About prettyphoto interfering with widget

### ISSUE THREAD

**Issue by wagnered** [ampache/ampache#2643]
I'm not experienced with the subtleties of js, so I'm hoping someone with more experience can help

I'm working on using a Creative Commons widget to help manage licensing. The problem is that if jquery.prettyphoto.js script is loaded  in the header the widget gets suppressed.  If it is moved  to the footer and made async the creative Commons widget is displayed.

My question: Would loading jquery.prettyphoto.js in the footer be a problem for Ampache? 

If it might help I can include the widget code in a gist for examination.

Thanks..

**Comment by kuzi-moto** [comment]
I don't think it matters too much, and actually I think it's preferred to load JS last. Otherwise, I think if it's tested thoroughly without issues then it shouldn't matter too much.

**Comment by wagnered** [comment]
I think it is used only when displaying thumbnails during art gathering.  Maybe @lachlan-00  can tell me where else it might be used.

Thanks.

**Comment by lachlan-00** [comment]
it's used in the art display function
![image](https://user-images.githubusercontent.com/1305249/101420569-397a3d00-393e-11eb-812b-f534eb131e18.png)

which is then used for the little overlay parts using "item_art_actions"
![image](https://user-images.githubusercontent.com/1305249/101420421-d4bee280-393d-11eb-9f50-28d53cec3ea1.png)

I did think it was used for all overlays like the play button but it looks to me like it's only in the display part for the actions.

I think the reason it's in the header is because there isn't always a footer?

**Comment by wagnered** [comment]
> I think the reason it's in the header is because there isn't always a footer?

Which begs the (rhetorical) question: why isn't it in the body of the pages that require it?  😄Never mind, I'll check the art display later.

Thanks

**Comment by lachlan-00** [comment]
Yeah I think the situations it's used are very minor so it could be taken out of the header pretty easily.

Even the display function could be rewritten to take that part out at it seems a bit convoluted
