### ISSUE TITLE
[Feature Request] Increase the range of the volume slider, so that I can set the volume even lower, so I can still hear discord users.

### ISSUE THREAD

**Issue by Jieiku** [ampache/ampache#2896]
I am hoping to be able to set the volume just a bit lower, at the lowest setting its still not low enough to hear the users on discord:

![2021-04-25_19-46](https://user-images.githubusercontent.com/106644/116022370-ebb95500-a5fe-11eb-8088-0bf23c7e2f10.png)

Would really appreciate this feature :)

**Comment by mitchray** [comment]
Interestingly the feature you're talking about (logarithmic volume) has been a part of jPlayer [since 2017](https://github.com/jplayer/jPlayer/pull/374
), unfortunately though there hasn't been an official release since v2.9.2 in 2014 so it hasn't been included in Ampache via Composer.

**Comment by xekon** [comment]
oh, that is very neat, I noticed when i migrated from ampache 4 to ampache 5 that the composer command was used. Is the newer jPlayer part of ampache 5 now?

**Comment by mitchray** [comment]
Sadly no, still no release from jPlayer and I wouldn't hold your breath there...

I haven't used it myself but AutoDuck might be a solution for you in the mean time: https://auto-duck.com/

Alternatively my [Ample client](https://github.com/mitchray/ample) has it :)

**Comment by xekon** [comment]
> Alternatively my [Ample client](https://github.com/mitchray/ample) has it :)

Would love to see screenshots that show the layout of the main sections: albums, artists, genres.

Does Ample support podcasts if enabled in ampache? (did not see podcasts in the ample screenshot)

Is Ample responsive? meaning if I shrink the page width the layout adjusts instead of truncating off or adding a horizontal scrollbar.

I did not even know that Ample existed, will check it out for sure, very curious about any differences between Ample and the stock UI of ampache.

**Comment by mitchray** [comment]
Its music only and very desktop focused, not intended as a replacement for the Ampache UI

**Comment by lachlan-00** [comment]
i've aded it to the demo

https://develop.ampache.dev/ample/
+ FOAM
https://develop.ampache.dev/foam/

**Comment by mitchray** [comment]
The latest version of jPlayer has been 'forked' into Ampache so I believe this feature is now live
