### ISSUE TITLE
Create and stream Ampache to a WP page

### ISSUE THREAD

**Issue by aagej** [ampache/ampache#2996]
How to stream the music to my WordPress webpages. I tryhave to set up a "Radio Station" - how to create the stream URL?
As a novice I do not get it -looked at https://demo.ampache.dev/index.php#browse.php?action=live_stream - sorry do not understand but would love to get this working - Please assist

**Comment by lachlan-00** [comment]
if you want to create a continuous stream you need to create a channel.

https://github.com/ampache/ampache/wiki/Channels

Icecast is better at streaming than Ampache though and while it works the channel stream will eventualy die due to not closing all the connections and disallowing new ones requiring a channel restart

**Comment by aagej** [comment]
Thank you for your reply and guiding - Hve one problem though my hosting services will not install Icecast on the "small" account I have.

**Comment by stebe** [comment]
Before I ran my own icecast server i used  [Listen2myradio](http://listen2myradio.com) and their free service. There were limitations but good enough for a small ampache setup.

**Comment by tomchiverton** [comment]
This can be closed ?

**Comment by aagej** [comment]
Yes, go ahead please.

**Comment by lachlan-00** [comment]
there's also this page i've been writing regarding using playlists with icecast

https://github.com/ampache/ampache/wiki/Ampache-Icecast-and-Liquidsoap

it works much more reliably as a channel/stream
