### ISSUE TITLE
Podcasts

### ISSUE THREAD

**Issue by Baggypants** [ampache/ampache#30]
Ampache is pretty good at dealing with albums. But Podcasts should really be stored or sorted in date order. I probably shouldn't be storing Podcasts in Ampache.

**Comment by Afterster** [comment]
Wanted to close this latest 2013 issue before going on 2016. First implementation with commit baaceca250ea608c2c13bf0a6200f1edb7deab04.
Thank you for your patience :)

**Comment by Jucgshu** [comment]
This first implementation of podcasts is really cool. Once again, thanx for your great work @Afterster 

Merry Xmas & happy new year :-)

---

For reminder, some features to think of later on :
- Add streaming of episodes ability (without having to dowload them).
- Add auto-download of new episodes.
- Add option to delete old and/or played episodes that have been downloaded.
- Add more options :
  - Rules on how long keep episodes before automatically delete them.
  - Auto sync on podcast page refresh.

**Comment by Afterster** [comment]
Thanks for the feedback and merry Christmas too @Jucgshu :)
 * About auto-download, this is already the case, it is done in case of catalog update. If you're running a cron for catalog update then it is already the case.
 * You can already delete downloaded episode if you enabled `delete_from_disk` on ampache.cfg.php
 * Rule to automatically delete episodes is Ampache system setting `Podcast: # latest episodes to keep` coupled with `delete_from_disk`

**Comment by Jucgshu** [comment]
Woops, i didn't see the new option on web ui :-)

And thanx for the tip on catalog update !

**Comment by Nicocys** [comment]
Installed and tried since yesterday. I quite like it :)
A few minor issues: the track info doesn't show in the recently played list, and when downloading an episode you have to reload the list of episodes page to have it appear as completed instead of pending.

A bigger issue I have at the moment: it seems the list of episodes is populated once, and once only. As in: it doesn't show new episodes, whether I click on "sync" or if I update the catalog. In the logs it just shows "(podcast) -> Syncing feed http://radiofrance-podcast.net/podcast09/rss_12283.xml" and that's it, no error, no new episodes even after updating the catalog.

**Comment by calcmandan** [comment]
I have the same issue. It ampache won't download new podcasts for those already subscribed after the initial download. I attempted catalog update, add, and verify and nothing happens.
