### ISSUE TITLE
[Feature Request] Ability to limit specific catalogues to users.

### ISSUE THREAD

**Issue by ghost** [ampache/ampache#308]
I have a few users that don't care for my music library, and I theirs - it would be nice to be able to have each user set up with certain catalogues so that they don't have to deal with all of my music.

**Comment by dhsc19** [comment]
Voting this one up.  My wife and I both have our own destictive collections and would like to have something that can keep our libraries separate.

**Comment by AsavarTzeth** [comment]
Glad to see this getting some attention. At the moment I am happy just playing with Ampache myself & using it as a personal Google Music replacement.

But soon enough I would like to be able to share this with people & that pretty much requires this.

**Comment by mirage335** [comment]
This would also make it easier to separate duplicate tracks processed for special effects, as with AudioPreprocessor. https://github.com/mirage335/AudioPreprocessor

**Comment by toptnc** [comment]
+1 on this.

**Comment by minnesotags** [comment]
Agreed, it is also important for copyright/performance. If you had a catalog of public domain music, being able to share that with a category of user would be huge.

**Comment by ou-li** [comment]
+1

**Comment by nasask8r** [comment]
Another vote here for this feature!

**Comment by ragolz** [comment]
This would be an excellent feature as I have just started to use ampache. I found that i need this feature, for example i have a a list of catalogues, dance,trance,house,pop etc, and unsorted, the unsorted is just a list of albums i have not categorised as of yet but would like to be able to listen to them but would not want all users to have access, this also applies to my DJ mix sets, I would not want every user to have Access so some form of catalogue ACL would be good. maybe just an extra column in the db to say what catalogue it's from and if xx user can view it.

+1

**Comment by starblessed** [comment]
+1 here too.

I'd like to limit the access for my kids to specific catalogues, so only allowing them to watch or listen to kids shows.

**Comment by Mokhless** [comment]
+1

**Comment by aslmx** [comment]
Where are we with this feature?

I installed Ampache mainly for myself, but my Wife is now interested as well.
But she doesn't want to see the thousands of songs that i have...

Would be nice to separate libraries as requested above... This is a real usecase!

**Comment by lachlan-00** [comment]
I agree. 
As another husband with a wife uninterested in darkwave and ebm I've put a simpler solution into the core branch.

While we don't share all music. Couples probably do share some music so this is what I've added.

In the config there are options for rating_browse_filter

If you enable this and set a star rating below this is what happens.

All artists and albums that are <= to that rating. (Eg 1,2 for 2.) Will not show up in random, mashup or album of the now.

They will still show up in search and full browse but I've found it keeps my viewing clear. When you rate something poorly it should still be findable but just slightly hidden.

I'm going to work on it a bit more but this way I can ignore her music I hate and she can ignore mine. It also will never show up in random selections for me or her.

The hiding of libraries from other users will be added but not until after the first 4 release

**Comment by lachlan-00** [comment]
For those waiting for separate libraries the process will probably be:
* An option in the catalog settings page (comma separated list of user ID's to deny access to catalog)
* A config setting (even if you set the deny list ensure that the server admin is allowing this)

**Comment by lachlan-00** [comment]
Hi all, I'm going to work on this to put into the next release.
https://github.com/ampache/ampache/tree/catalog_filter

It will be a comma separated id list for filtering users. that user will not be able to see any content in that catalog. We do a lot of filtering for when catalogs are disabled so this will probably be the easiest way.

**Comment by lachlan-00** [comment]
who's ready to get excited?
![image](https://user-images.githubusercontent.com/1305249/70884343-82e0c680-2021-11ea-809e-b0ea4593f888.png)

This was actually pretty easy to implement in the browser pages. I might even do the rating filters!

**Comment by a7medo778** [comment]
niceeeeee
looking forward to it 😁
now we have the ability to limit the catalogs access, and upload/edit only his uploads, now we need to be able to limit the tag choices by the admin

**Comment by lachlan-00** [comment]
I'm just about done. This feature will have a config option called catalog_filter and filters on song, artist, album, video browses.

i want it to block anything from a filtered catalog showing up so it's going to take a little bit more but it's mainly just the sql functions now.

**Comment by ou-li** [comment]
Great to see  that you are implementing this. 
Let me know if I can help with testing.

**Comment by lachlan-00** [comment]
I'm not far away from merging it in.
The only real issue i see from this is that it's slow.
It's fast for songs but slower for albums and artists because it has to check against the songs.

Artists are slowest so i might take them out and only filter album,song. Artists can be across multiple catalogues while albums/songs usually aren't. but that will give empty artists.

I think i'll also expand the ratingsfilter into the browse functions because those are assigned to each object but that means you have to do the ratings first.

**Comment by rsbc3483** [comment]
Hi lachlan-00,

I know you have been discussing this option for user/per catalog.   Is this feature available in the latest release?

**Comment by lachlan-00** [comment]
This is now done in a3054310a

It has relied on a lot of the ampache5 work but i think it's done in such a way that will be usable for most people who want this. previously each time i've tried to fit this in it's been far too slow to use especially when we got to artists due to the need for a lot more SQL columns and tables to map this information.

Enable catalog_filter in the config file and then assign a catalog to a single user (Public by default) Once enabled this will restrict everything that connects to that catalog (check out `Catalog::get_user_filter()` for an idea of how much filtering there needed to be)

For me i don't think it's a great idea but it works and has been running on my personal server where i have opened every single link in the webUI/API and ensured that the queries are working.

There may be a possibility of empty results but i've been through every possible option i can find and ensured that when i expected results they were returned.

**Comment by lachlan-00** [comment]
I tried to close the bug bounty but it doesn't let me (or needs time to resolve)

Please feel free to close it and refund anyone who backed as the money isn't needed.
