### ISSUE TITLE
Cannot play anything. Files are all empty (0 bytes).

### ISSUE THREAD

**Issue by hell001** [ampache/ampache#3093]
### Describe the bug
The following reproduction steps seem to completely break Ampache as far as playing music (for me?). Files are not playing, and all downloads produce 0 byte, empty files. The solution is unknown.

### To reproduce

From a fresh installation:

1. Add a catalog
2. Download a song (just as a test, should download fine)
3. Edit the config, uncomment the option `enable_custom_metadata` to enable it
4. Show Catalogs > [new catalog you made from step 1] > UPDATE FILE TAGS option
5. Show Catalogs > [new catalog you made from step 1] > UPDATE option
6. Try to play and/or download a song (does NOT work)

Some of the steps above may not be necessary to yield the same results. They are just the exact steps I took, and every time it broke. (Your music files may need to actually have custom metadata tags embedded for this to happen? Unsure.)

### Expected behavior
Updating file tags and updating a catalog should not break Ampache and prevent you from playing and downloading all files.

### Screenshots
n/a

## Environment

* Ampache version: 5.1.1
* Web server + version: 2.4.51
* Server operating system: Linux
* Client operating system: Web, iOS, etc (all)

### Client type

* Web
* Ampache
* SubSonic
* DAAP
* UPnP
* WebDAV

## Settings

Default config for a fresh install, with the exception of enabling `enable_custom_metadata` in step 3 in the reproduction steps.

## Logs

Logs show nothing

**Comment by lachlan-00** [comment]
i'll see if i can recreate in a few hours

**Comment by hell001** [comment]
@lachlan-00 Were you able to recreate?

**Comment by lachlan-00** [comment]
haven't had time to check yet, but did the major work i wanted today and will hit this tomorrow

**Comment by douglasriper** [comment]
It looks like #3027 .
Is Ampache on Ubuntu 20.04?

**Comment by hell001** [comment]
> Is Ampache on Ubuntu 20.04?

No it is not. @lachlan-00 how did it go when you tried to recreate?

**Comment by lusum** [comment]
Ok, i have tried to test this bug.
The bug is real. In the database the field size of the song is zero, so we have this kind of problem.

The only steps necessary to trigger this bug are:

* Edit the config, uncomment the option enable_custom_metadata to enable it
* Add a catalog

My suspect is that activating the option, if the custom metadata in the file doesn't include a file size or they include a wrong size, ampache overwrite the size field

This code make me suspect that this is the behaviour:
Module/Song/Tag/SongTagWriter.php:70

`           if ($this->configContainer->isFeatureEnabled(ConfigurationKeyEnum::ENABLE_CUSTOM_METADATA) === true) {`
`                foreach ($song->getMetadata() as $metadata) {`
`                    $meta[$metadata->getField()->getName()] = $metadata->getData();`
`                }`
`            } 
`

**Comment by lachlan-00** [comment]
that must be it, i should be able to fix this up pretty quickly now that i don't have to look for it!

i've got a half day free tomorrow from work to fix it

**Comment by lachlan-00** [comment]
with d42459c i was able to clear my 0 files after enabling custom metadata

**Comment by lusum** [comment]
Tested, the bug seems fixed.

**Comment by lusum** [comment]
Bug to close
