### ISSUE TITLE
ampache ample demo outdated, login no longer works

### ISSUE THREAD

**Issue by xekon** [ampache/ampache#3098]
ampache ample demo outdated, login no longer works: https://develop.ampache.dev/ample/

**Comment by lachlan-00** [comment]
i saw this morning, the develop branch isn't returning data which i need to look at asap

**Comment by lachlan-00** [comment]
@mitchray i've fixed this on https://develop.ampache.dev/ample/

`/server/json.server.php?action=handshake&auth=12345&version=350001`

haven't documented this all yet but version is now determining the api version you return. so when you send v350001 api requests you get nothing because json didn't exist for apiv3.

what i might do is default that to api5 instead which will fix that (if the app supports api5)

**Comment by lachlan-00** [comment]
double fixed with 0174f73c8

i made the call that handshake version and ping version determine return format. (will update details about json for api3 though.)
![image](https://user-images.githubusercontent.com/1305249/142989092-97669655-9f7e-4d4d-9e84-a735d3db94fe.png)

**Comment by mitchray** [comment]
Sweet, I've hardcoded the API version properly now

https://github.com/mitchray/ample/releases/tag/0.20.0

**Comment by xekon** [comment]
Awesome!
