### ISSUE TITLE
API clarification: `download`, `stream`, `record_play`, and `scrobble`

### ISSUE THREAD

**Issue by paulijar** [ampache/ampache#3935]
Reading the API documentation, it's unclear to me if downloading or streaming a song automatically increments the play count of the song, or should the client always call `record_play` or `scrobble`. Looking at the source codes, I didn't find a place where such automatic increment would happen, but apparently, many clients are assuming this happens and it has worked fine for them.

IMHO, it would make more sense if there was no implied song count increment and the client would tell this explicitly. But if the design has always been the other way around, then it isn't necessarily practical to change it. Either way, it would be good to clearly document this in the specification.

**Comment by paulijar** [comment]
As an idea, if recording the play automatically on `download` is the established behavior, then maybe the API should provide an optional argument to opt out of this. Because sometimes, the client might download a song without playing it immediately.

**Comment by lachlan-00** [comment]
This might be a bit long but lets go.

There are 2 basic playback functions stream and download.

## Stream

When you play a song stream will:

* Record a play in the database which is recorded as a 'stream'
* If you stream a new song too quickly the last song will be marked as 'skipped'
* Play count is incremented **up** for a stream and back **down** for a skip

It is very important to note that play history is compared to the client string. You can play a song on a browser, start a subsonic stream and then an api client stream right after and all 3 plays will be recorded as streams because they are different clients.

## Download

When you download a song:

* Record the action as a 'download'
* A download is not a stream and does not affect skip checks when playing new songs
* Play counts are **not** incremented.
 
Download is used for caching files without the server thinking you've played 40 songs in 3 minutes.

## Playback process

Stat checks happen every time you call a stream/download **url** (including part stream content-range calls) in the PlayAction and Play2Action classes.

e.g. `music.com/play/index.php?action=stream&etc`

When you use the api stream/download calls they redirect to these urls

The checks are there to stop duplicate recording in the stats class.

I make the server check everything for you so you should not have to worry about anything if you always use stream actions.

## Scrobble

Scrobble and record play are used for recording plays from saved information/data. They're generally not used during playback as the stream action manages that process.

Scrobble uses parameters similar to last.fm (which is why it's called scrobble.)

The idea is that if you are using a different player where aren't able to get the object id you can scrobble to your Ampache server.

![image](https://github.com/ampache/ampache/assets/1305249/cb4ce7c1-9e2c-4d73-8826-272f9a7514da)

I use scrobble when playing from rhythmbox (i wrote a plugin but haven't used it in a while https://github.com/lachlan-00/rhythmbox-ampache-fm) so i don't need to access my library and can directly play the files without knowing the song id's.

## record_play

Record_play does the same thing as scrobble but only requires the object id which is useful with playing cached/downloaded songs from an api client that has access to the id

If you are playing a downloaded file or a cached version of the file and want to record a stream you would call record_play as there is no stream or download action happening.

e.g. I cache song with the id 1240 and i play it from the mp3. that mp3 play isn't a stream so i use record_play to set the stream in the database.

## new method: player

There is a new method for 6.4.0 called player which i'll release with 6.4.0. it's more about giving the server an active status of what the client is doing.

![image](https://github.com/ampache/ampache/assets/1305249/e91257a1-5640-4685-a56e-039a3b3dc2b9)

Player does a bit more than scrobble and record_play allowing me to do a few more things

* Update now_playing data (remove on stop add it back on play) (you can get that information in the api with now_playing)
* Shift last item play time on resumption of playback (e.g. i pause a song at 20 seconds for a day and restart the song. the item will shift to NOW - 20 seconds as i haven't played any other song.)

it's similar to scrobble/record_play but the play/stop parameter gives me a bit more information about what you're doing

## cleanup

sorry for dumping all this in a pretty long text. does that answer everything?

The idea is that you shouldn't have to think about anything when you stream. The server will do all the checks and updates for you.

When you download, you need to tell the server that you're playing a cached file so use scrobble/record_play/player.

Once you tell the server that you're playing with stream/scrobble/record_play/player methods the server is able to update the play status/history depending on your data.

I could probably put this kind of info into the .org api site too as well so if you want me to expand on this with a new page or expand the method documentation i can do either/both depending on the info you need.

**Comment by lachlan-00** [comment]
Is there any information you might want on this topic @icefields ?

**Comment by paulijar** [comment]
Thanks, this is very informative, and just the kind of explanation which I would like to see in the API specification.

**Comment by lachlan-00** [comment]
that's great then!

I think i'll combine these methods into their own section so i can write about them all under one heading.

**Comment by icefields** [comment]
Excellent summary! 
Maybe I'd just add that there's a timeout between scrobble api calls to take into consideration. That timeout should be pulled from the server settings, but for now I'm just hardcoding it to 20/25 seconds (I found that to be a good sweet spot).

I use scrobble for when downloaded songs are being played from Power Ampache 2, and to batch-scrobble all the songs played while in offline-mode once the user comes back online. For PA2 batch-scrobble is going to be a best-effort action, since the timeout makes batch scrobble unreliable. I shall try `record_play` instead for recording songs played in offline mode.

**Comment by lachlan-00** [comment]
okay that's good, i'll flesh it all out into the api docs and see if i can install npm/docusaurus on my work laptop

**Comment by lachlan-00** [comment]
First docs uploaded now.

Now i just need to install npm...

https://github.com/ampache/ampache.org-api/blob/master/docs/api-media-methods.md
