### ISSUE TITLE
feature request: prevent double add to playlists

### ISSUE THREAD

**Issue by stonie08** [ampache/ampache#397]
I think there should some kind of dialogue that asks the user if he wants to add a song already existing in the playlist again.
An exception to this could be the temporary playlist. But when using the "add to new playlist" option or "add to existing playlist" it would be nice to get asked if you even want double add the songs.
I think it would be sufficient to get asked on a "per add" basis, specifying if you want to add all the duplicates or not.

**Comment by gylgamesh** [comment]
Any chance of this ever happening?

Or maybe a foobar component that would do it, please?

Many, many thanks.

**Comment by wagnered** [comment]
Hello @gylgamesh,

Back on 11/14/2014 @afterster added an action to remove duplicates from a playlist in commit 29a062d, that's why this issue is closed.  But Ampache is dynamic with many features so it is possibe that the feature might have been broken during the development process. :smile:

If the action no longer behaves properly, please open a new issue describing the problem.

Regards....

**Comment by lachlan-00** [comment]
The API has the option to not add duplicates. In the web UI it just adds but I think a user option to force it would be better.

**Comment by lachlan-00** [comment]
INCOMING, this can be double closed after this merges
![image](https://user-images.githubusercontent.com/1305249/82775371-df76c600-9e8a-11ea-8fb4-e95e26061fbc.png)
