### ISSUE TITLE
track_user_ip does not work as expected

### ISSUE THREAD

**Issue by fufroma** [ampache/ampache#3980]
In the configuration file, the "track_user_ip" option is to log for user login :

https://github.com/ampache/ampache/blob/e85360e1d5948de4112819757a3e0d450be468e2/config/ampache.cfg.php.dist#L375-L376

The ipHistoryRepository->create() function is called by trackIpAddress() 
And trackIpAddress() is not only in login function, but also in Play function :
```
src/Module/Application/Login/DefaultAction.php:            $this->userTracker->trackIpAddress($user);
src/Module/Application/Playback/Play2Action.php:            $this->userTracker->trackIpAddress(Core::get_global('user'));
src/Module/Application/Playback/PlayAction.php:            $this->userTracker->trackIpAddress(Core::get_global('user'));
```

Result : instead of having ip_history of people logging in, we have an entry for every music played by an user, logged or not.

There is two way to fix this bug:
- we want to log IP when someone play music, but we 
  - must fix the documentation
  - add feature to be able to differentiate login and play in the ip_history log
- we want to log only logging, we must fix the "bug"

**Comment by lachlan-00** [comment]
it should proabably go in the api handshake or ping instead of play. not really sure of the value of play ip tracking?

**Comment by lachlan-00** [comment]
the show ip history doesn't work very well either. `users.php?action=show_ip_history&user_id=2`

it looks like it shows the opposite values
![image](https://github.com/ampache/ampache/assets/1305249/0481c9d3-f2eb-47f6-b0b9-cb5b21ea9149)

And unique seems to only show 1 ip instead of the unique ones
![image](https://github.com/ampache/ampache/assets/1305249/9629cca3-595f-401b-8f6a-90b19d40627e)

**Comment by fufroma** [comment]
Tbh I didn't look in the UI : I'm using ip_history to detect bot account ^^

But yes, look like a lot of things don't work as expected

**Comment by lachlan-00** [comment]
I think it should be reduced to login and handshake to start with. the data for stream just goes wild after that.

The sql in the pages is all over the place too so i'll have to look into that as the data isn't helpful

**Comment by lachlan-00** [comment]
made a few changes to the process, in the last few commits

8b512b1dfe4bcb777bee50a25978a4eeda86dc1e
ea33ee97ddc1773d660b2b7afdae5d503908b177
b9cf0e0e794ae9246a81248391de9db9c1a9b195

* track on handshake, ping in the api
* remove from play urls
* default to 100 most recent ip's
* show all now will show all
* renamed default items to 'recent' instead of show unique which didn't make sense

**Comment by fufroma** [comment]
Changes looks great! :)

About

> default to 100 most recent ip's

This could be a good idea for the `user_ip_cardinality` : storing the 100 last IP instead of a specific number of day.

Another idea could be to have an option to store only the 24 first bits of an IP. It allow to detect change of country or ISP (useful for debug and investigation purpose), but it's more compliant with GDPR. In this case, we would store 203.0.113.0 instead of 203.0.113.42

**Comment by lachlan-00** [comment]
it is meant to be days, the sql didn't do that before but i can add days into the sql for limits again.

The ip is logged in the webserver multiple places before getting to the application log so i'm not sure how strict the GDPR would be on that if it made apache/nginx wipe all logs for a user

**Comment by lachlan-00** [comment]
b1e446a8d sets it to a day limit (time() - (cardinality * 86400))
