### ISSUE TITLE
Let admin of public instance of free/open licensed music the possibility of manually setting the order of suggested licenses in the Upload dropdown box

### ISSUE THREAD

**Issue by shangril** [ampache/ampache#4038]
Currently when uploading music on such sites, the musician sees the licenses sorted alphabetically. 

Letting the admins of the instance sort the display order of the licenses would be a nice way to avoid unaware musicians to publish under a license that, by definition, grants in a non-revocable manner rights on the music. By defining an "open" one that doesn't gives away much as the default, it would prevent unaware musician to abandon rights on their music without actually knowing that they are doing so. 

Adding this option to the Admin webUI would be quite useful.

**Comment by lachlan-00** [comment]
license priority number and sort by that?

just an extension of the license table but that's easy

**Comment by lachlan-00** [comment]
i'll also make order 0 = hide

**Comment by lachlan-00** [comment]
In develop you now have an order
![{A4BF6E29-068B-431B-8D30-FF94A5D3AB9A}](https://github.com/user-attachments/assets/e25bdb99-ff29-4d31-80be-6a4424138951)

which allows hiding entirely instead of deleting
![{7295DF80-4D48-4DF7-AE66-2A3E05B0C039}](https://github.com/user-attachments/assets/a06ddddc-e357-4125-b5f3-88c55243036b)

Then when you edit a song it's shown in the desired order
![{3261C69A-55FE-4E39-AA5B-D732331C6D94}](https://github.com/user-attachments/assets/6724333d-e0dc-4d98-adb1-cf0494320153)

**Comment by fufroma** [comment]
@shangril I think you can close this issue
