### ISSUE TITLE
Multiple albums of the same name grouped together

### ISSUE THREAD

**Issue by apastuszak** [ampache/ampache#415]
Ok, so I have three albums all called "Greatest Hits" by three different artists.  When I go to Artist A, I see "Greatest Hits" listed and it tells me the album has 46 tracks.  When I click on it, it has the tracks for Artist A, B, and C all lumped together.

Is there a setting which will turn this off?

**Comment by chylex** [comment]
I organize my music based on folder structure with different artists but sometimes same album names. I turned off "ID3" and then spent a while searching for a bunch of the albums, thinking they were missing, but it turned out they were all clumped under one item (and apparently with a randomly chosen album cover, which made it even more confusing). An option to turn this off would be nice, but I guess renaming the folders will work too. Just posting to explain my use case where the current behavior doesn't make sense.
