### ISSUE TITLE
Browse Catalog in File explorer mode

### ISSUE THREAD

**Issue by eephyne** [ampache/ampache#528]
Somes music players allow that mode and I found it especially useful in some cases. (like showing every songs in a particular folder even if they do not have the same artists or come from the same album. Or for songs who don't have any tag.

I was wondering something similar could be achieve in ampache ?

**Comment by Afterster** [comment]
After several discussion, it will not be done (out of Ampache scope). But if you find a clean way to implement it, feel free to suggest a PR ;).

**Comment by blausand** [comment]
Too sad. I spent the last decade sorting and browsing my music by folder and although i maintained thousands of ID3-tags, i always stuck to this navigation. 
_(Mainly because i feel comfy using a dozen genre subfolders while the genre tag tells about 50 subgenres.)_
So, i hope you or you or you will author a nice plugIn to "**Browse by folder structure**" ;)

**Comment by TimoJohn** [comment]
+1

**Comment by ftoledo** [comment]
+1

**Comment by AshotN** [comment]
I agree with @Afterster that this is out of scope. Ampache expects proper tagging so it can handle organization. It's a decent bit of work to add to Ampache, and Ampache already doesn't have a tremendous number of active.

**Comment by lachlan-00** [comment]
This is set after f01fd183c627bbe0eb508c2842b2c338dd93c75e
