### ISSUE TITLE
Filename pattern not working 

### ISSUE THREAD

**Issue by systems-rebooter** [ampache/ampache#591]
Hello,

Looks like filename pattern borked in latest dev. It gives back Artist - Year - Title.mp3 all the time.

Thanks.

**Comment by systems-rebooter** [comment]
@SUTJael @Afterster sorry guys, have been sidetracked. Wasn't working for me that days still. 
I will grab the latest dev and give it one more try. Will update you soon. Thanks.

**Comment by systems-rebooter** [comment]
Tried with latest build. 4f60766437b5d0dd778181a39d51d341cb06fc9a.
Issue seems to be still there. Filename pattern works strange while downloading tracks:

Catalog A (old one): 
Artist - Year - Title.mp3

Catalog B (new one):
Artist - Track-ID - Title.mp3 

Where can I change this, besides catalog options?

Thanks!

**Comment by Afterster** [comment]
Any chance to give a zip with some of your files / directory, and a screenshot of your catalog settings (pattern configuration, ...) so I can test properly on my side?

**Comment by Afterster** [comment]
Oh I got your issue randomly. You was missing an important information on this thread, it's filename pattern when **downloading a song**. In develop branch, it is always *Artist - [Tracl ID -] Title.ext*
If you have Year instead of Track ID, then I believe you have wrong metadata on your files. It doesn't looks like a bug for me, please confirm.

**Comment by systems-rebooter** [comment]
Hey,

Ampache version `3.8.0-beta1`
Song name structure: `YEAR - ARTIST - TITLE`
Filename pattern: `%t`
ID3 tags missing `TRACK-ID` (so Ampache using `YEAR` instead of it)

In develop branch, it is always Artist - [Track ID -] Title.ext
:)
