### ISSUE TITLE
Stream gets 403 when using external auth?

### ISSUE THREAD

**Issue by kcalvert** [ampache/ampache#596]
My config is:

auth_methods = "external,mysql"
external_authenticator = "/usr/sbin/pwauth"
auth_password_save = "true"

...basically, I want an actual system account for users, but fallback to mysql for the ootb admin user.

The login piece works fine but when I go to stream I get the 403.

I've tried changing auth_methods to mysql,external, with the same results.

I've also created a ampache only user to confirm, and stream works for it.

**Comment by Afterster** [comment]
Ok I got some time to test it and found the root of your issue.
Users automatically created after external authentication are created as guest by default. When authentication is required, guests are not authorized to stream media. You should create the users as 'user' level instead of guest using `auto_user` setting in ampache.cfg.php.

**Comment by kcalvert** [comment]
Ah, thank you. Makes sense, not sure how I missed that.

Confirmed that this was the fix.


*Kevin*

Eleven Three Labs LLC
eleventhree.com
