### ISSUE TITLE
Error with same name albums

### ISSUE THREAD

**Issue by robertocarlo** [ampache/ampache#610]
There's an error on how same name albums are shown, sometimes (i.e. "greatest hits") it shows different artists with same album name in same folder and organises it like "Various Artists" compilations.
![screen shot 2014-11-29 at 13 30 15](https://cloud.githubusercontent.com/assets/7412863/5235131/c434a414-77cd-11e4-919d-d319177bb752.png)

**Comment by mcladyz** [comment]
Doesn't work for me. I have added MBID -tag to the files of both albums and updated both catalogs (Yeah, the albums are in different catalogs).

**Comment by SePHTaN** [comment]
Haven't tested a complete catalog update for this reason for a long time.

Only changing the Songs Tag's (adding MBID for example) and afterwards updating the Catalog (complete or better only respective folder) didn't work for me since at least 3.7.0.

My Way is to remove the respective Albums completely from Catalog (folderdelete, catalogclean) and afterwards catalog add only that respective folder (for time reasons, large catalog 35000+Songs).

Haven't tested with latest releases to see if the problem with identical named albums further on exists, but that's the way it definitly works at least for me.
@Afterster 
Adding New or corrected Albums that way works flawlessly, no incorrectly mixing of identical named albums. Doing a complete Catalog update results in grouping albums with identical names together disregarding different release years, only adding MBID for identical named Albums helps.
Is there a reason not to regard the release year ?

**Comment by Afterster** [comment]
The problem with release year is that is not a perfect match. The release year is for the song release, so album release date is basically determinate on song year. Some albums has songs released in different years. If we add release year in the album grouping logic a legitimate album without mbid and with songs from different years will be split into multiple albums ; which is not acceptable (and it was an issue on version <= 3.7.0).

**Comment by mcladyz** [comment]
> Ampache now (version >= 3.7.0) have an additional constraint based on unique IDs from MusicBrainz metadata that will split them correctly if the albums were tagged using a tagger that writes the MBIDs to the file (such as Picard or Beets).

**Comment by Afterster** [comment]
Yes it means that.
I believe there is no issue here and the discussion can be closed. Otherwise please continue the discussion on google group.

**Comment by mcladyz** [comment]
The is a issue for me, at least. As described above, adding the album's MBID to the files didn't work.

**Comment by Afterster** [comment]
Ok I didn't understand like that  sorry. Re-opened.
Could you send me two test files to afterster@gmail.com? Thanks.

**Comment by mcladyz** [comment]
Ok, mail sent

**Comment by Afterster** [comment]
Thanks for your file. Ok you should noticed your mbid tags are not imported into Ampache :)
This because you use *album_mbid* instead of *mb_albumid* tag.
How/with which software did you tag your files?

**Comment by mcladyz** [comment]
Ah, great. That works, thanks.

Can you update the wiki to specify which tag must be used? I tagged these files manually, so I needed to know the actual tag name. 

Here's the "pull request" (Since wikis don't support pull requests):

> Ampache now (version >= 3.7.0) have an additional constraint based on unique IDs from MusicBrainz metadata that will split them correctly if the albums were tagged using a tagger that writes the MBIDs to the file (such as Picard or Beets. **The album's MBID must be written to the *musicbrainz_albumid* -tag in each file of the album**).

**Comment by Afterster** [comment]
Well the tag depends of the file format, this one is only for vorbiscomment. Better to refer to the format documentation.
Good it works now, can I close this?

**Comment by mcladyz** [comment]
Okay, this can be closed.
