### ISSUE TITLE
Tags show up as single letters instead of words.

### ISSUE THREAD

**Issue by florihupf** [ampache/ampache#654]
Hi there,

I think this used to work and now is broken.   Some of my tagged mp3s have tags in them.

For example one has: "Dance & Noir".

However ampache reads them as:

'&', 'D', 'N', 'a', 'c', 'e', 'i', 'n', 'o', 'r'.

Is this something I do wrong on my end when tagging? Or is this a problem of the ID3 library?

Thank you!

**Comment by SUTJael** [comment]
Any chance to retrieve the raw data to see how your tag is encoded? Which software do you use? I think it's related to recent update on tag processing.

**Comment by florihupf** [comment]
I am using TagScanner 5.1 on Windows.

It used to work great in version 3.7.0 of Ampache. So I agree, it must be a
recent regression.

Is there another way I can help?

~ Florian

**Comment by SUTJael** [comment]
Would be great to give us a sample file :)

**Comment by Razrael** [comment]
@florihupf I will look into this issue in #662 
Would be great if you could give us a file where the problem occurs, so we can reproduce and fix this.

**Comment by Afterster** [comment]
Must be an encoding issue again. Could be related to #628 and https://github.com/JamesHeinrich/getID3/pull/39 pull request.

**Comment by Razrael** [comment]
Possible. If we can get a file with an error we can simply do a regresson test.

**Comment by florihupf** [comment]
Will send a file today.

**Comment by florihupf** [comment]
Here is a file: http://www.nid-nad-nud.org/seafile/f/9de42c3d60/

The genre is encoded wrongly.

**Comment by florihupf** [comment]
The genre comes out as:

/, A, b, c, E, i, l, M, n, p

Where is should be:

Abstract/Minimal/Experimental

**Comment by Razrael** [comment]
Thanks for the file.
I tested this on my dev server. On latest development branch I got no weird behavior, though the tags were parsed as one single string, including the delimiter.
When I test it on the branch from Pullrequest #662 the tags are splitted properly.
I assume you checked the tags in the tag cloud and on the song page in Ampache? Just to avoid misunderstandings :-)

I would suggest you to get the latest development branch again and update your music library. Support for updating tags is included since a few days. Maybe a other developer can double check this, could possibly 

After that we could continue with your Ampache settings file, just to be sure.

**Comment by florihupf** [comment]
Ok, I think I am on latest greatest, but I will update just to make sure
and fully rebuild my catalog.

Yes, the broken output is visible in the tag cloud and in the song page in
Ampache.

Will report back.

Thanks for looking into this.

**Comment by florihupf** [comment]
Oh, and I see broken output for "Tags" or for "Genre".

**Comment by florihupf** [comment]
Hi there,

I updated my catalog after "git pull" and now all works.

Thanks everyone and sorry for the noise.  The time I will try that before
filing an issue.

~ Florian

**Comment by Razrael** [comment]
Great to hear this :-)

So I recommend you to keep an eye on #662 
After merging you can update Ampache again and update your music to finally get your genre tag splitted.
Can you please close this bug?

**Comment by florihupf** [comment]
Thanks will do! Closing this one out.
