### ISSUE TITLE
add videos into a playlist

### ISSUE THREAD

**Issue by SurvivalHive** [ampache/ampache#675]
dont sure if i´m right here - dont find forums or something else for ampache...

i have many music tracks as video but i cant add them into a playlist.
nothing happends - not important which video file it is...

it will be awesome if you can add videos in a playlist so u can play the complete list automaticly.
at the moment it is not possible - only step by step...

master branch (3.7.0 version)

**Comment by Afterster** [comment]
Indeed, video in playlist is not currently supported. Marked as en enhancement.

**Comment by SurvivalHive** [comment]
thx - this will be awesome - 
do u know how/where i can learn more about the code from ampache? found not really helpsome stuff...

**Comment by Afterster** [comment]
Unfortunately code architecture is not well documented. The best way is to open your php IDE and start looking on /lib/class and /templates files. But this change is not the simpler one :)

**Comment by SurvivalHive** [comment]
by the way - only with trouble i get mp4 video files in ampache...
it was helpfull if mp4 are setted as video files - not music -

if i set mp4 to video - then i get the files but with no informations about the video.
only titel. think mp4 for video is not currently supported as well?

**Comment by Afterster** [comment]
It is, but on develop branch. You should try develop branch for the video feature to report accurate information on development. Thanks!

**Comment by wagnered** [comment]
SurvivalHive,

In earlier 3.7.* branch mp4s could be imported as movies, TV shows or
clips(music videos with only their recording date added as tag info.)

It's been awhile since I've worked on the video portion of Ampache
(early 3.7 branch), but in the earlier revision, music videos were meant
to be imported as clips and very little tag information is grabbed from
the mp4 video. Movies and TV shows had problems with incorrect
conversion of getID3 information and some coding errors in transferring
the data to the database.

My time has been redirected to higher priorities, but as there seems to
be increasing interest in the video portion, I think I can resume my
work on correcting the importing of mp4 info into the database. But this
wouldn't include working videos into the play list.

That is unless someone else has been working on this aspect in the
current development branch.

It would have been nice if Ampache began by pursuing the
Model-View-Controller (MVC) principles but I think it's beginnings may
have preceded the now well-organizing concepts of the MVC framework.

This conversation might be better carried on in the Google discussion
forum.

-- 
73 From Ernie D

AA1AD | CN87ug 

-----Original Message-----

**Comment by Afterster** [comment]
That would be great if you have time to work on the video part @wagnered, your previous work was really helpful.
I personally focus myself to close all remaining issue for 3.8.0 release (I don't have much time this past months so it is slower than I want but it progress).

You're right about Ampache, the core architecture was developed when MVC wasn't popular yet. We all agree that it should have a review and there was already several discussion about a better code architecture, better framework, and even some working PoC ; see #112 and #359. It is also important that an architecture review doesn't remove features we implemented this past years.

**Comment by wagnered** [comment]
Back to SurvivalHive's complaint:

If the mp4 was imported with the  Music button selected, then it probably was imported as a music file. If Movie, TV or Clip is selected than it will be imported as a variety of multimedia file. I don't know what would happen in that case.

@Afterster, Shouldn't that be determined by the config file?  If mp4 is not set in the "catalog_file_pattern" setting, shouldn't the process ignore mp4 files if the radio button is set to "Music" when creating/updating a catalog?

**Comment by Afterster** [comment]
Both condition are required, the catalog must be marked as Movie / TV / Clip, and mp4 files defined in *catalog_video_pattern* setting.

**Comment by wagnered** [comment]
What I understood SurvivalHive to indicate was that mp4 multimedia files
were being imported into a music catalog.  Could that happen if the mp4
extension was added to 'catalog_file_pattern' And if so, perhaps that
was what he unintentionally did.


-- 
73 From Ernie D

AA1AD | CN87ug 

-----Original Message-----

**Comment by Afterster** [comment]
He is on 3.7.0 version in fact, so yes. Otherwise with develop this cannot happen if the catalog wasn't marked as `Music`.

**Comment by SurvivalHive** [comment]
i download yesterday the last dev build ( Ampache 3.8.0-develop) but now i cant see my video files in ampache anymore...
i created a new cataloge with music clip or film... with all possible things there -
by scanning he found the files but they dont be shown in list if i click on music clips or somewhere else.

**Comment by Afterster** [comment]
Mhh there was a little issue on music clip depending on your configuration, but movie should have been fine. Could you try with latest commit and if the problem remains, post some logs of your catalog update? Thanks.

**Comment by SurvivalHive** [comment]
ok downloaded for 5min the last dev - my mp4 videos are back in list / *perfect*

only open for me  - add videos in a playlist so i can play musicvideos step by step automaticly ;)

ps... i love your work ^^

**Comment by Afterster** [comment]
Ok great thanks.
Adding video into playlist is indeed important.
No more improvement for 3.8.0 except the ones already in the roadmap (we really should release it one day ^^), it will be for the next one ;)
