### ISSUE TITLE
Question re: catalog updates?

### ISSUE THREAD

**Issue by rvonder** [ampache/ampache#690]
Hi -
I'm a former Subsonic user with a reasonably large library (87k tracks), and recently discovered Ampache. Am running the latest 'develop' branch code under WAMP and it looks great so far. I do have some basic questions about catalogs - have searched all over and can't find answers:
1. Often I'm just adding a new album, or have updated the ID3 tags for a specific album. Is there any way to limit a catalog operation like Add or Update to only a specific subdirectory, vs. having to wait 7 hours to reprocess the entire library needlessly?
2. The 'Show Catalog' dialog has two fields that appear to allow entering directories for Add and Update, respectively, with an 'Update' button beneath them. These are not mentioned anywhere in the documentation: What are they for? I tried entering a lower-level subdirectory in these boxes (e.g., my catalog is `e:\music`, and I entered `e:\music\downloads\b`) - when I clicked 'Update' the screen cleared and just said 'Done'. I then ran a Catalog Add, but Ampache still processed the entire library structure, so I must not be understanding how these fields are used.
3. My library already has fairly complete basic tags and album art. Is there anything I can try that might reduce these seven hour nightly catalog runs?

Any suggestions welcome, and many thanks!

**Comment by Afterster** [comment]
Hi @rvonder. As you have some experience with Subsonic, don't hesitate to compare both solution, feedbacks / recommendation are always appreciated ;)

About your questions:
 1. *Add* should be faster than *Update* as it just look for new files instead of all files metadata changes. But it could still takes time. 3.8.0 release is on his way and the documentation will also be reviewed for the release ; I will create a topic later on how to automatically update the catalog for changed files only (inotify, ...).
 2. That's it. Normally it should work as your describe. Maybe your php configuration makes something to fail, you can try to enter e:/music/downloads/b instead. I just committed few changes to have more accurate messages on this process result.
 3. Album art search is time consuming, if your tags already embed the album art, you can disable external album art and metadata search with `art_order` (recommended to keep at least db,tags) and `metadata_order` / `metadata_order_video` (recommended to keep at least filename,getID3)

**Comment by rvonder** [comment]
Hi @afterster,
Thanks for the feedback - I'll give your suggestions a try.

Yes, I've been using Subsonic for several years now. To answer your question, I think the biggest problem with Subsonic is that it assumes your library is organized with a very specific directory and file naming convention. It relies much more on metadata derived from that physical structure than it does from ID3 tags. So I've actually been running a fork of Subsonic called MusicCabinet that is based on tags, much more like Ampache. It's a great solution, but is based on a much older version of Subsonic and the MusicCabinet developer appears to have abandoned the project. Also, some of the Subsonic clients don't really leverage the tag-based architecture of MusicCabinet. What finally caused me to look for a better alternative was that Subsonic/MusicCabinet uses Jetty with a ProgreSQL database. The app opens about 25 ProgreSQL threads, which wasn't a problem until very recently when each of those 25 threads would suddenly jump to about 5-6% CPU. Do the math - ProgreSQL was trying to consume 150% of my entire server, often locking it up so tight that a reboot was the only way out. I spent hours looking for the reason, and even reinstalled and rebuilt everything from scratch - but was never able to find a fix. So I was delighted to discover Ampache and leave those issues behind, especially after learning that Ampache (theoretically) even supports the same Subsonic clients.

That said, as I've worked with Ampache, I've been compiling a list of what appear to be bugs and error messages, along with some suggestions and questions. I think I'm up to about 25 items right now. How would you prefer to receive the list? I kinda hate to clutter your GitHub by adding a huge pile of separate issues, especially since some may already be known and others are somewhat interrelated. But I'll do whatever is best for you - just let me know.

Thanks again for a great product!
     Rob
___________________
Sent from Nine<http://www.9folders.com/>

**Comment by apastuszak** [comment]
Madsonic, another fork of Subsonic, is going to have full tag support in
the upcoming 6.0 release.   But the Ampache Web UI beats any of the
subsonic forks hands down.

**Comment by Afterster** [comment]
We already derived a bit from the original thread so you can post your list here, we can still create separated issues later if required.

**Comment by Afterster** [comment]
@rvonder, finally separated issues would be better to follow the resolution progress. I'm closing this then, please don't hesitate to report your issues in dedicated threads!
