### ISSUE TITLE
NFS and access denied

### ISSUE THREAD

**Issue by brendankearney** [ampache/ampache#701]
i am using AutoFS to mount a NFS share that ampache is to use for the catalog.  i have tried to provide access/rights/permissions to the mountpoint, but can figure out what i am doing wrong.  the NFS share is mounted when i attempt to update the catalog, so the AutoFS piece is working.  the debug logs shows:

2015-01-30 21:36:01 [-1] (clean) -> Starting on mp3s 
2015-01-30 21:36:01 [ampache] (PHP) -> [Runtime Error] opendir(/music): failed to open dir: Permission denied in file /var/www/html/ampache/lib/class/core.class.php(198) 
2015-01-30 21:36:01 [-1] (catalog) -> Catalog path:/music unreadable, clean failed 
2015-01-30 21:36:01 [-1] (clean) -> clean finished, 0 removed from mp3s 
2015-01-30 21:36:01 [-1] (catalog) -> Database cleanup started 
2015-01-30 21:36:01 [-1] (catalog) -> Database cleanup ended 
2015-01-30 21:36:01 [-1] (verify) -> Starting on mp3s 
2015-01-30 21:36:01 [-1] (verify) -> Finished, 0 updated in mp3s 
2015-01-30 21:36:01 [-1] (catalog) -> Database cleanup started 
2015-01-30 21:36:01 [-1] (catalog) -> Database cleanup ended 
2015-01-30 21:36:01 [-1] (Memory) -> 4.5 MB 
2015-01-30 21:36:01 [ampache] (PHP) -> [Runtime Error] opendir(/music): failed to open dir: Permission denied in file /var/www/html/ampache/modules/catalog/local.catalog.php(238) 
2015-01-30 21:36:01 [-1] (read) -> Unable to open /music

/music is owned by root:nasMusic when the mountpoint is mounted.  permissions are 775.
all files/folders in /music are owned by root:nasMusic.  permissions are 775.

httpd is running as root and child processes are running as apache.  OS is Fedora 20 on web server, nas/NFS server and client.

what am i missing?

**Comment by Afterster** [comment]
This is clearly a permission issue. Check all your rights ; specifically selinux configuration here.

**Comment by brendankearney** [comment]
i agree, but dont know what else to check.  the permissions are 775.  selinux is disabled on all devices.

**Comment by wagnered** [comment]
Make sure the exports file on the server is set up correctly. If your
system is freenas or nas4free it should be in the /etc folder.

Make sure all requests are mapped to root and the entire network is
permitted access. Here is what I use on my nas4free system:
   
  /Storage -mapall=root -network 192.168.2.0 -mask 255.255.255.0

I also mount the share on the client at boot time with /etc/fstab so
it's ready when I need it.

# Device                    Mountpoint                      FStype
Options             Dump  Pass

192.168.2.10:/Storage	 /media/nas4free   	  nfs	  _netdev,rw,users	0 0

NFS is very slow because rpc is used to determine what version of nfs to
use, what ports to communicate on,etc, so the initial mounting can be
very slow.

-- 
73 From Ernie D

AA1AD | CN87ug 

-----Original Message-----

**Comment by brendankearney** [comment]
i installed ampache on my nas device and got it working there, with apache accessing the local disk without issue.  the issue i seem to be facing is the inability to access NFS shares that require authentication.  the os mounts the share without issue, but apache / ampache is not leveraging the keytab i have, or i dont have the right principal in the keytab.  either way, i am trying something new.

with the ampache instance on my nas working, i have created a second database for the web servers to use, so as to not step on the configs, etc that the nas has in its database.   i then tried to configure one of the web servers to point to a remote ampache instance, which is the instance on the nas.  i am running into some issues, but i may have flubbed something and will likely drop the second database and recreate it and the web servers config from scratch.

i plan on running 2 load balanced ampache instances and pointing them to the same database that is their own and the same remote ampache instance, which is on my nas device.  in theory, this seems like it would work.  does anyone see any major gaps or gotchas in this plan?

**Comment by SUTJael** [comment]
Well not really unless you start to edit the same object on both instances. Your database will of course have twice more queries but if your server can handle that, I don't see major gaps. If you find some, don't hesitate to give us some news.

Whatever, wouldn't be better to find the solution of your NFS access rights issues? We may not be able to help you, but I think you wont be the only one trying to do that. @wagnered seems to have it working, you may want to ask him some help :)

**Comment by wagnered** [comment]
@SUTJael,
Not really,:I set up my nfs shares for a "persistent" mount via fstab.  I see no reason to unmount the shares unless rebooting.  

 I do see some possible permissions conflicts in @brendankearney's  previous message.  He shoudn't be running httpd as root.. and the "child processes" (Does he mean virtual hosts?) should be the same owner/group as the music folders and files.  At least that is the way it is using lighttpd.  He doesn't indicate if he is running the catalog update locally, as root: That may be why the update works and the remote folder access doesn't.

Ernie D

**Comment by brendankearney** [comment]
httpd starts as root and drops privs, but the ppid to all the httpd processes is still owned by root.  the pids all belong to apache.

the default virtual host, i believe, is what is running the ampache instance.  because it is under the default virtual host, the pid should be owned by apache.

the directory and files are owned by root:nasMusic and the apache user is in the nasMusic group.

how should i be running the catalog updates?

**Comment by wagnered** [comment]
@brendankearney,

So you are indicating that in httpd.conf you have:
user apache
group nasMusic
Are you sure the top directory /music has mode of 775, otherwise directory tree cannot be traversed.
The debug statement:
"...-> [Runtime Error] opendir(/music): failed to open dir: Permission denied in file /var/www/html/ampache/lib/class/core.class.php(198) "  seems to indicate the top directory doesn't have +x in the group or "other" columns.

You might try, temporarily, chmod -R 777  /music to see if that changes mattters. if it works, then permissions aren't being set as you believe.

I was wondering how you are doing the updates: From a local CLI or browser(localhost)  on the server? From  a remote web browser?  Just trying to understand the difference.  I am assuming you can't access the catalogs as a remote user/admin via browser.

I'm not sure how ampache would respond (what kind of error would be reported if the NFS share isn't properly exported to the network, but  it needs to be defined in the  /etc/exports file as suggested in my above. message   Just because it is mounted, doesn't mean it is acessible to the network, even localhost.

I'm curious, what is the NAS system you are using?  I have experience with NAS4free, freeNAS and several others. It may help me understand the exact problem.

Also, as this doesn't seem to be attributed to Ampache, you can respond directly via wagnered@comcast.net or aa1ad@arrl.net (message forward service).

Ernie D

**Comment by brendankearney** [comment]
i'll reply out of band.  if the powers that be feel the topic is appropriate for discussion here, we can bring it back here when they indicate so.

**Comment by Afterster** [comment]
Ok, I'm closing this then as it is not really an Ampache issue? Thanks guys.
