### ISSUE TITLE
Catalog clean takes a long time with large tag_map

### ISSUE THREAD

**Issue by stebe** [ampache/ampache#723]
Even though I've changed all the art to be on disk rather in the database (thanks @Afterster) the database clean still takes a long time well over an hour with this function: 
 $sql = "DELETE FROM `tag` USING `tag` LEFT JOIN `tag_map` ON `tag`.`id`=`tag_map`.`tag_id` " .
"WHERE `tag_map`.`id` IS NULL " .
"AND NOT EXISTS (SELECT 1 FROM `tag_merge` where `tag_merge`.`tag_id` = `tag`.`id`)";

This is found in tag.class.php

While this is running the table is locked and prevents me from using Ampache for anything usable until the lock is cleared. In the database my tag_map has 1,295,000 rows. If I truncate tag_map clean take just seconds, but of course the next catalog update the tag_map gets filled again. Is there a way to speed up this query or is it something I'm going to have to live with because of all the tags I have?

**Comment by Afterster** [comment]
I'm not sure how it could be improved. At the end the 1,295,000 rows are required to have the real tag map between your library items...
Maybe tag clean shouldn't be done at catalog clean but as a distinct operation? What do you (and other ampache users) think?

**Comment by Psy-Virus** [comment]
One dumb question:
If tag clean is running, is every entry (one after another) checked against the whole table?
I mean .. like a loop, U know?

If it is done that way, isn't it possible to avoid that loop, so that not every entry must check the whole table?
Maybe I'm totally wrong but isn't it possible to make, for example, two lists. Maybe the OS makes a List in database format, let's say a temporary .csv file with the tags and this is then mirrored to the database which is obviously the second list.(?)

Or anything in this direction. I mean 1000 loops need more time to run than a one time scan, one time check, followed by the creation of commands for the server and execute them.

If this isn't that stupid like I think, it maybe improves also other database operations, like checking of existing files(pathes).

Maybe it gives you an idea^^

**Comment by stebe** [comment]
This time I truncated the tag_merge table along with the tag_map table. The tag_map table now goes to about 400,000 entries after an update. Although recent commits could have caused the reduction of the number of entries in the tag_map table to 1/3 of its size. 

Another temporary workaround I've done is to convert the tag, tag_map and tag_merge tables to innoDB so now I'm not dealing with table level locks. I'm sure I'm taking a performance hit somewhere else by doing this.

**Comment by stebe** [comment]
Going to close this. Since I did the workaround mentioned this hasn't been an issue.
