### ISSUE TITLE
Album artist is not working

### ISSUE THREAD

**Issue by The-Compiler** [ampache/ampache#742]
I'm using the develop branch - if I understand #249 correctly, displaying album artists should be enabled by default.

However, when I look at `browse.php?action=artist` I still see the individual track artists.

The files are flac files, with those relevant vorbis comments:

```
    comment[7]: ALBUMARTISTSORT=Welle Erdball
    comment[12]: ALBUMARTIST_CREDIT=Welle: Erdball
    comment[18]: ARTIST=The Screeching Miew
    comment[20]: ARTIST_CREDIT=The Screeching Miew
    comment[25]: ALBUM ARTIST=Welle: Erdball
    comment[26]: ALBUMARTIST=Welle: Erdball
    comment[33]: ARTISTSORT=Screeching Miew, The
```

Or am I just misunderstanding how this feature works? Either way, the mess in "Artists" makes Ampache pretty cumbersome to use for me :-/

**Comment by Afterster** [comment]
Album artist is an additional information used in part to uniquely identify albums. It doesn't replace tagged artist per songs. This could be an option (*don't import song artist of album artist is defined*) but this is a feature request then ;)

**Comment by darkblinded** [comment]
I would like to be able to view my music by albumartist rather than artist. Is there any progress on this feature request? Or maybe a hint where I can adapt this myself?

**Comment by yam655** [comment]
@darkblinded From glancing at the source, it looks like you want to create an albumartist.class.php based upon the existing artist.class.php, the references to the artist will need updated to reference the album artist -- in particular the SQL involved in "get_*" functions will need to be changed. Then to wire it up, you'd need to update the browse.class.php, browse.php and add the browse_albumartist CSS and probably some other minor wiring... At least, that's my understanding from glancing at the source.

I didn't check, but if the Album Artist DB field is null when it isn't set, you'd need to take that in to account, either in the SQL or by removing that possibility when processing the catalog. Since it wasn't used in a manner in which it was required previously, it is likely null when absent. This may well be the tricky part of the process as without this all the other work will be for naught.

This would be to create a "Browse Music" / "Album Artist" feature on-par with the existing "Browse Music" / "Artist" feature. It would create functionality and not break anyone relying upon the current track artist behavior.

My own music collection includes a lot of music from SongFight.org, where the album artist and song title will be constant for an entire album and only the track artist will change. I'd benefit from being able to collapse all the SongFight-only artists in to a single entry, but not if it means losing the ability to access my songs by track artist as well.

**Comment by plabadens** [comment]
Given that you generally would have a library with *Album Artist* fields present or empty/irrelevant, then would it not be more sensible to have it outright replace the *Artist* view?
This seems to be the behaviour in most media players. In Subsonic there seems to be a dedicated option to activate browsing by *Album Artist* when the tag is present. As @yam655 said, this view would have to fallback to the *Artist* field when nothing else is present.

**Comment by yam655** [comment]
@plabadens Anything I've downloaded from SongFight.org is completely unusable without access to the track artist. It is a song contest website. I clean the metadata by hand after downloading it. All the songs have the exact same name. I assign them all to the SongFight album artist. They have the same year. The site presents them in random order so there isn't even an implicit track order. The _only_ difference they have is the track artist.

I, for one, would find favoring the album artist over the track artist to be extremely broken. It is more functional to not have access to album artist at all. I would like access to both, but if I can only have one, it needs to be the track artist.

**Comment by plabadens** [comment]
Sure, this may not be optimal for all uses, but for a general use case this would probably be present as an option either in the interface or in the config file, so as to switch from track to album artist.

**Comment by treys** [comment]
I also vote for some sort of view by "Album Artist" ... perhaps defaulting the "Artist" view to use the album artist tag and fall back to the artist tag. Without this, albums that have lots of "featuring" artist labels and/or "various" artist albums get mixed up in the "artist view."

**Comment by pdf** [comment]
Browsing by artist should (probably) default to Album Artist.  Albums with multiple artists where the Album Artist tag is not populated should be imported to the database as 'Various Artists'.  There should be an option to select whether to browse by Artist or Album Artist.

**Comment by jesse-troy** [comment]
Any progress on this? The only reason I have not fully switched to Ampache from Airsonic is this feature. I need the ability to view my library sorted by albumartist and not artist.

**Comment by kuzi-moto** [comment]
@jesse-troy Unfortunately I don't think anyone has looked at this since it was opened. With Laravel being more or less abandoned for the time being, focus has shifted back to fixing bugs and getting Ampache ready for a 4.0.0 release. I'm not sure if this is something that would be included, but hopefully can be looked at soon.

I agree that this would be a really nice thing to have. My Artists page is over 1700 entries and I definitely don't care about seeing tons of Artists that only have 1 or 2 tracks which makes up a bulk of those.

**Comment by lachlan-00** [comment]
This will be possible. It's just query changes as far as I know. If I make a setting to change queries it should change the UI and all corresponding values.

Recent changes to the Catalog process have made sure that album artist is being populated and updated correctly.

So hang tight because I don't think this is a huge change.

**Comment by superlinuxero** [comment]
+1 on this. The lack of sorting my music catalogue by Artist Album is, as of now, the only feature preventing me from moving to Ampache

**Comment by lachlan-00** [comment]
i've actually put this into the web ui and the api today, browsing artist in the web ui will default to album artist now.

There's also a lot clearer differentiation between whether this is a song artist or an album artist in the text.
![image](https://user-images.githubusercontent.com/1305249/99355324-c4de5080-28f3-11eb-95a3-40a6b91d4fbd.png)

**Comment by lachlan-00** [comment]
oh and the issue with album artist not appearing on the api clients or songs was fixed a while ago too.

There was a code issue where it would check but then not set it so songs didn't have an album artist in responses. the property is now set on all songs correctly

**Comment by kuzi-moto** [comment]
Yaaay, this is a great fix. Thanks @lachlan-00

**Comment by lachlan-00** [comment]
It wasn't a huge change in the end but it just takes time to get to these things.

The query class is where all the browse stuff is set up and is just a bit obtuse when you aren't the one who wrote it.

I think this will help me fix a few more long term issues now.
