### ISSUE TITLE
Database Connections

### ISSUE THREAD

**Issue by abhiklodh** [ampache/ampache#743]
I hosted ampache on Hostinger and in their free account, they give you 3 mysql database connections.
When i try to install ampache, it shows that i have exceeded my database connections.
Can any1 tell me how many connections r required to run ampache and i will upgrade to premium account which gives me 15 connections
Thanks

The error is :

Error: Unable to create user xyz with permissions to ******* on mysql.hostinger.in: SQLSTATE[42000] [1226] User '************' has exceeded the 'max_user_connections' resource (current value: 3)

**Comment by Afterster** [comment]
This is something very similar to other php scripts.
Basically one connection per page load. You can sometimes reach 2-3 simultaneous connection for the same client because of Ajax content load.
Be aware that if you load several pages simultaneously or have multiple users connected in the same time, this would increase the number of database connections of course.
