### ISSUE TITLE
thumbnail image for videos

### ISSUE THREAD

**Issue by alire** [ampache/ampache#747]
hello
thanks for your great & open source application , ampache!!
but how could i set and display a thumbnail image for my videos??
it shows only the default unknown image for all videos.
the ampache version is 3.8.0

**Comment by SUTJael** [comment]
You can activate "generate_video_preview" into the configuration file to automatically set an image from the movie. Otherwise you should be able to manually set an image by click on the "gear" icon hover the picture. BTW, please use [google group](https://groups.google.com/forum/?hl=fr#!forum/ampache) for that kind of questions first ;)

**Comment by alire** [comment]
hi
thank you & sorry to post here Although you've closed this issue.
i think there is a little bug here.
i have set ..
generate_video_preview = "true"
but no change occurred.
also there is no thumbnail place and no gear icon.on video detail page but i see them on a mp3 detail page.
![untitled1](https://cloud.githubusercontent.com/assets/5457004/6541445/b3592fc4-c4e5-11e4-8451-d7b521e8848a.png)

**Comment by Afterster** [comment]
Indeed @alire, thanks. Should be fixed now.
