### ISSUE TITLE
Search by "Comment" is not working

### ISSUE THREAD

**Issue by malkavi** [ampache/ampache#829]
I add as a comment the language of the songs (Spanish, English...). I have try to search using "contains" but doesn't works, also tried using "does not contain" with the same result, "No song found".

**Comment by Afterster** [comment]
This work on my side, which version are you using?
Btw there is a id3 tag for the language, from my opinion you should use it instead.

**Comment by malkavi** [comment]
Thanks for your reply.
I'm using the 3.8.0-develop version, the last version from github. The system is a Synology NAS.
I don't think that is important, but the comment tag is edited from banshee.

**Comment by Afterster** [comment]
Mhh this could be a getid3 issue, could send me a test file to afterster@gmail.com so I can take a look? Thanks.

**Comment by malkavi** [comment]
Thanks for your time. I have sent you 2 songs. If I can do something else, let me know. I have try the command `php bin/print_tags.inc | grep japon` and I can see the tag correctly.

```
DiskStation> php bin/print_tags.inc /volume1/music/Absolute\ Soul/Absolute\ Soul/01.\ Absolute\ Soul.mp3 | grep japon
                    [language] => japones
                                    [comment] => japones
                                    [comment] => japones
                                    [language] => japones
                                    [0] => japones
                                    [0] => japones
                                    [0] => japones
                                    [0] => japones
                                    [0] => japones
                                    [data] => japones
                    [comment] => japones
                                    [0] => japones
                                            [0] => japones
                                            [0] => japones
                                            [0] => japones
                                            [0] => japones
                                            [0] => japones
                                            [data] => japones
                            [comment] => japones
                                            [0] => japones
    [language] => japones
```

**Comment by malkavi** [comment]
I can confirm that the search is working now. Thanks!

**Comment by ufp32633** [comment]
I believe it is not fully working. I store metadata in the comment field like the position in a certain week in the US Billboard Hot 100. Certain songs appear for several months in the list so I store a huge amount of info in the comment tag. As far as I can tell now ampache only considers a certain part of the characters of that field and ignores the rest of them.
The largest number I've found so far is 643 characters. For certain files only the first 30 characters are considered, but that might be a problem due to a possible bug in the past that already has been solved.
I've tested this by using the song information button. I did not manually check the database itself.
(I wanted to add a screenshot as proof but apparently Github doesn't like the filetype of filesize of it)

**Comment by Afterster** [comment]
@ufp32633 could be an unsupported character or getid3 bug. Could you send me a test file to afterster@gmail.com?

**Comment by ufp32633** [comment]
Yes, I'll send you an example soon.
The problem has become more complicated. In the meantime I've found files that are correctly indexed and that contain a substantial amount of info in the comment field.
On the other hand: yesterday I've edited the comment field of 40 files and I've added a few new ones. After that I've performed a manual scan and each night I've scheduled an automatic scan. So that's two scans since the changes. Today I've searched for the new info in the comment field and none of the files show up. However they're in the database and can be played.

**Comment by ufp32633** [comment]
I've send you a testfile.

**Comment by Afterster** [comment]
Ok @ufp32633 thanks for your test file. Should be fixed with https://github.com/ampache/ampache/commit/8f1ede91c4a79b2a2853cbb7c2a5e0b4599fce7a.

**Comment by ufp32633** [comment]
I've performed a few tests to see if I could trick Ampache but I didn't succeed, so I can happily confirm that the issue is solved. Good job and thanks for the effort.
