### ISSUE TITLE
Missing art

### ISSUE THREAD

**Issue by json08** [ampache/ampache#844]
I have loaded both a music and movies catalog.  Not all of the artists / albums have art work showing and all of the movies are missing art.  I suspect that this is an issue with resizing.  I know that the art for movies would need to be resized.  I am using OS X Server 10.10 and I know that the PHP-GD is not the full PHP-GD out of the box.  So, I installed a fresh version of PHP.  I checked my logs and it looks like there is still an issue with resizing.  Any help is appreciated.

2015-05-05 21:31:44 [js] (Art) -> Image failed PHP-GD test
2015-05-05 21:31:44 [js] (Art) -> Not trying to generate thumbnail, invalid data passed
2015-05-05 21:31:44 [js] (autoload) -> 'OAuthException' not found!
2015-05-05 21:31:45 [ampache] (PHP) -> [Runtime Error] imagejpeg(): gd-jpeg: JPEG library reports unrecoverable error:  in file /ap/lib/class/art.class.php(662)
2015-05-05 21:31:45 [js] (Art) -> Unknown Error resizing art

**Comment by wagnered** [comment]
I think I can comment on the movies part of your question:

1. What is the format of your movie files? Quicktime/mp4 from Itunes?
It's the only file format that is formally spec'ed  to have artwork
embedded in the file

2. Where are you expecting to get the art to display; embedded metadata
in the file, from the folder or from themoviedb (Tmdb)?

3. If you expect to get the artwork from meta-data in the file,
ampache.cfg.php needs to be set up correctly. getID3 must be set as the
first item in "metadata_order" and "metadata_order_video".

4. If you want to get the artwork from Tmdb (for movies) or thetvdb
(Tvdb), you need to get an api key from each of them. And then it still
will be "iffy" because the functioning of these plugins ares not yet
very efficient in parsing filenames. I am just finishing up work on the
TMdb and Tbdb plugins and adding a few features to the video side of
Ampache.

5. If you are attempting to get the artwork from image files in their
respective folders, I don't know what the status of that is as I have
not yet tried it.

At first glance at the code, it looks like the artwork for movies can be
re-sized, but not separately from the album art, though.  I'm not sure
why you need the movie artwork to be resized: The default size looks
perfectly acceptable on my 17 inch notebook.

The messages you list below imply that the issue is with music artwork.
I'll let that for someone who is more familiar with that side of
Ampache, but there is a slight chance that it could be because there is
no image to process.


-- 
73 From Ernie D

AA1AD | CN87ug 

-----Original Message-----From: json08 <notifications@github.com>
Reply-to: ampache/ampache <reply
+005d506e18bb198f36fa73b59dadabcf9d39bb4fd32ffb8a92cf0000000111615eb392a169ce0461bad3@reply.github.com>
To: ampache/ampache <ampache@noreply.github.com>
Subject: [ampache] Missing art (#844)
Date: Tue, 05 May 2015 21:46:43 -0700



I have loaded both a music and movies catalog. Not all of the artists /
albums have art work showing and all of the movies are missing art. I
suspect that this is an issue with resizing. I know that the art for
movies would need to be resized. I am using OS X Server 10.10 and I know
that the PHP-GD is not the full PHP-GD out of the box. So, I installed a
fresh version of PHP. I checked my logs and it looks like there is still
an issue with resizing. Any help is appreciated.

2015-05-05 21:31:44 sonic -> Image failed PHP-GD test
2015-05-05 21:31:44 sonic -> Not trying to generate thumbnail, invalid
data passed
2015-05-05 21:31:44 sonic -> 'OAuthException' not found!
2015-05-05 21:31:45 ampache -> [Runtime Error] imagejpeg(): gd-jpeg:
JPEG library reports unrecoverable error: in
file /ap/lib/class/art.class.php(662)
2015-05-05 21:31:45 sonic -> Unknown Error resizing art

**Comment by json08** [comment]
Hi wagnered , thanks for your reply.  I think I have a couple of issues going on but I'll first answer your points 1-5.

1. Format - Yes.  mp4 / m4v
2. Art source - Yes.  embedded metadata
3. getID3 is first on both
4. Not using
5. getID3

I mentioned the re-sizing because I thought it could be connected to the images not being displayed.  Graphs are not displaying either which was leading me to believe both could be connected to PHP-GD.  I am missing images for all movies, some shows and some music.  i think there may be an issue with memory on some of this as well.  I have had this issue in the past and increasing memory helped.  But as mentioned, because graphs aren't showing either I was thinking there may be some connection with PHP-GD.

**Comment by wagnered** [comment]
Seems to me that I remember that the key "quicktime"  had to be added in
front of getID3 in both metadata_order and metadata_order_video. I think
I remember this being documented in 3.7.0.

This should allow the display of previews for each movie.  But there
seems to be a bug with displaying cover/backdrop art from quicktime
files, which I'm looking into.


Could you tell me how the artwork/metadata was embedded? Were the mp4's
downloaded from Itunes with artwork/metadata already embedded? Or was a
third-party utility used to grab the information and embed it?

The reason I asked, is that I have been using an app called MetaX which
is supposed to conform to the ITunes/Quicktime specs.  The engineer sent
me the Itune specs that they use in MetaX. I have no monetary interest in
MetqX.  I just find it the most versatile gui tagger.  It is Windows based
works well with crosstalk (wine) on Linux.

If you are using a third party app to grab/insert the metadata, except
for MetaX, there is no guarantee that Ampache can parse the metadata
from the file.



-- 
73 From Ernie D

AA1AD | CN87ug 

-----Original Message-----From: json08 <notifications@github.com>
Reply-to: ampache/ampache <reply
+005d506e9bcef5fca639d051f1cb3a397e761817246fa37692cf000000011162228092a169ce0461bad3@reply.github.com>
To: ampache/ampache <ampache@noreply.github.com>
Cc: Ernest Wagner <wagnered@comcast.net>
Subject: Re: [ampache] Missing art (#844)
Date: Wed, 06 May 2015 11:42:08 -0700



Hi wagnered , thanks for your reply. I think I have a couple of issues
going on but I'll first answer your points 1-5.

     1. Format - Yes. mp4 / m4v
     2. Art source - Yes. embedded metadata
     3. getID3 is first on both
     4. Not using
     5. getID3

I mentioned the re-sizing because I thought it could be connected to the
images not being displayed. Graphs are not displaying either which was
leading me to believe both could be connected to PHP-GD. I am missing
images for all movies, some shows and some music. i think there may be
an issue with memory on some of this as well. I have had this issue in
the past and increasing memory helped. But as mentioned, because graphs
aren't showing either I was thinking there may be some connection with
PHP-GD. 

—
Reply to this email directly or view it on GitHub.



-- 
73 From Ernie D

AA1AD | CN87ug

**Comment by json08** [comment]
I do use two different 3rd party tools to embed the metadata.  I use iFlicks and iDentify.  I use iFlicks for television shows and iDentify for movies.  Though there could be an issue with parsing there are some shows and one movie that do show art.  I have also added quicktime to the order but haven't seen anything yet.  I am going through logs and it does look like the PHP-GD is an issue.  I did go through process to update but must try again.  I am seeing below in error log.

2015-05-07 15:51:47 [js] (Art) -> Image failed PHP-GD test
2015-05-07 15:51:47 [js] (Art) -> Not trying to generate thumbnail, invalid data passed
2015-05-07 15:51:47 [js] (Art) -> Invalid image passed
2015-05-07 15:51:47 [js] (Art) -> Not inserting image, invalid data passed


2015-05-07 15:52:28 [ampache] (PHP) -> [Strict Error] call_user_func() expects parameter 1 to be a valid callback, non-static method Catalog::update_video_from_tags() should not be called statically in file localhost/ap/lib/class/catalog.class.php(1399)
2015-05-07 15:52:34 [ampache] (PHP) -> [Runtime Error] imagecreatefromstring(): No PNG support in this PHP build in file localhost/ap/lib/class/art.class.php(205)

**Comment by json08** [comment]
One other question for you if you don't mind.  I am also seeing:
Image size (2533198) exceed the limit (1048576).

It looks like this is total file size and not length or width but I do not see on option for that parameter.  I looked in the art.class.php and do not see max file size just length and width.  Is it a correct assumption that this number is a file size?

**Comment by wagnered** [comment]
I'm sure that the Image is failing the PHP-GD test because either null
or false is being passed to the PHP-GD test function.  It looks like the
getID3 api library is removing the quicktime picture from the array it
is passing back. I'm not sure this is a bug or a feature and will be
contacting the author of the getID3 api to find out.  Meanwhile, I am
configuring a work-around.

Concerning your follow up message:

Take a look at "max_upload_size" in the config file.  The number looks
suspiciously like the one in the message.  It probably is commented out,
but it defaults to max_upload_size = 1048576.  That probably should
default to a little higher, but to save memory, you might want to reduce
the file size of the artwork to less than 1 MB each.  If my memory
serves me correctly, increasing that value should solve that problem.

I'll take a look at Iflicks if there is a trial period, but themoviedb
and thetvdb will be much more efficient when I get the changes
published; also less tedious.


-- 
73 From Ernie D

AA1AD | CN87ug 

-----Original Message-----From: json08 <notifications@github.com>
Reply-to: ampache/ampache <reply
+005d506e145c415075d02e0e91295e10314733db85b9d8ec92cf000000011163b20792a169ce0461bad3@reply.github.com>
To: ampache/ampache <ampache@noreply.github.com>
Cc: Ernest Wagner <wagnered@comcast.net>
Subject: Re: [ampache] Missing art (#844)
Date: Thu, 07 May 2015 16:06:47 -0700



I do use two different 3rd party tools to embed the metadata. I use
iFlicks and iDentify. I use iFlicks for television shows and iDentify
for movies. Though there could be an issue with parsing there are some
shows and one movie that do show art. I have also added quicktime to the
order but haven't seen anything yet. I am going through logs and it does
look like the PHP-GD is an issue. I did go through process to update but
must try again. I am seeing below in error log.

2015-05-07 15:51:47 js -> Image failed PHP-GD test
2015-05-07 15:51:47 js -> Not trying to generate thumbnail, invalid data
passed
2015-05-07 15:51:47 js -> Invalid image passed
2015-05-07 15:51:47 js -> Not inserting image, invalid data passed

2015-05-07 15:52:28 ampache -> [Strict Error] call_user_func() expects
parameter 1 to be a valid callback, non-static method
Catalog::update_video_from_tags() should not be called statically in
file localhost/ap/lib/class/catalog.class.php(1399)
2015-05-07 15:52:34 ampache -> [Runtime Error] imagecreatefromstring():
No PNG support in this PHP build in file
localhost/ap/lib/class/art.class.php(205)

**Comment by json08** [comment]
Thanks, again.  After I left post I did increase upload size.

**Comment by wagnered** [comment]
My bad, Ignore my previous message...

Adding "tags" to art_order in the config file should do it.

Sometimes it seems like one needs a college degree to figure out the
config file. ; ' >



-- 
73 From Ernie D

AA1AD | CN87ug 

-----Original Message-----From: json08 <notifications@github.com>
Reply-to: ampache/ampache <reply
+005d506ee7bd2911a5a67d2c941612c0c2fc56107720b2fb92cf000000011163c3f492a169ce0461bad3@reply.github.com>
To: ampache/ampache <ampache@noreply.github.com>
Cc: Ernest Wagner <wagnered@comcast.net>
Subject: Re: [ampache] Missing art (#844)
Date: Thu, 07 May 2015 17:23:16 -0700



Thanks, again. After I left post I did increase upload size.

**Comment by gregoo** [comment]
To complete what @wagnered said with logs, I came accross the issue he describes today.
I have some files with ridiculously large artwork files embedded and they were not integrated to the artwork database.

```
; Maximal upload size
; Specify the maximal allowed upload size for images, in bytes.
; DEFAULT: 1048576
;max_upload_size = 1048576

2015-05-10 15:55:24 [gregoo] (gather_art) -> Gathering art for album/639...
2015-05-10 15:55:24 [gregoo] (Art) -> Searching using:["db","tags","folder"]
2015-05-10 15:55:24 [gregoo] (Art) -> Method used: gather_db
2015-05-10 15:55:24 [gregoo] (Art) -> Method used: gather_tags
2015-05-10 15:55:27 [gregoo] (Art) -> Image size (6485837) exceed the limit (1048576).
2015-05-10 15:55:27 [gregoo] (Art) -> Not inserting image, invalid data passed
2015-05-10 15:55:27 [gregoo] (Art) -> Image size (6485837) exceed the limit (1048576).
2015-05-10 15:55:27 [gregoo] (Art) -> Not trying to generate thumbnail, invalid data passed
```

After pusing the upload size to 10MB, it was working and displaying on the website
```
; Maximal upload size
; Specify the maximal allowed upload size for images, in bytes.
; DEFAULT: 1048576
max_upload_size = 10485760

2015-05-10 15:58:55 [gregoo] (gather_art) -> Gathering art for album/639...
2015-05-10 15:58:55 [gregoo] (Art) -> Searching using:["db","tags","folder"]
2015-05-10 15:58:55 [gregoo] (Art) -> Method used: gather_db
2015-05-10 15:58:55 [gregoo] (Art) -> Method used: gather_tags
```

@Afterster: Not sure of this should be made into its own configuration parameter (`art_embedded_max_size` for instance) or if at least the documentation for this parameter should explicitly tell users what it affects in addition to files uploaded directly on the website.

**Comment by Afterster** [comment]
Maybe the variable name is too general but the comment is explicit enough I believe, it only affect images (album/video arts, user avatars).
