### ISSUE TITLE
Writing theme: modify CSS and HTML

### ISSUE THREAD

**Issue by Niols** [ampache/ampache#875]
Hello there,

I'm trying to write a theme for Ampache.

I created my own CSS file, and started writing it. Sometimes I had to write hacky things to be able to have the correct rendering, but most of the time that was OK, even if that would've been easier with the possibility to modify HTML.

Now I would like to have a better control on the iframes elements (in particular, I would like to customize the web player). I've not found any theme doing it and I wonder if this is possible.

Maybe by adding an other CSS file? The best way to do it would be to be able to have acces to the HTML. I see there are fils `show_*` in `templates/` so maybe this is the way to do it?

Whatever is the answer, I think that would be good to update the wiki page with it:
https://github.com/ampache/ampache/wiki/Themes

Thanks for answering and helping.
Niols

PS: link to 3rd party themes in wiki is dead

**Comment by Afterster** [comment]
Because Ampache themes was developed ten years ago by people who doesn't maintain it anymore we removed all themes in current development version, except the Reborn theme. We found others ugly so we didn't wanted to maintain it. Our opinion ; if someone would like to take care about theme migration from https://github.com/ampache/ampache/tree/048032f7c3c6aeb36d2b3e5cd1a9173ca92982f4/themes and become the officiel maintainer for theme, feel free to suggest a PR.

Back to your original question, theming is not currently supported on web player as /templates/jplayer.midnight.black.css or /templates/jplayer.midnight.black-iframed.css style files are always included indifferently from theme selection. We should be able to define custom theming for web player too => marked as enhancement.

**Comment by Niols** [comment]
I would say that we could replace all path in the template files (includes, css import, images) by a function that tests if the the file exists in theme's directory. If it's the case, this one is imported, and if not Ampache falls back on the default file. That would give a great freedom to themes writes that could completely rewrite the graphic chart.
I think that wouldn't be too hard to do. If you find this enhancement interesting (I do), I could write this and suggest a PR.

**Comment by Afterster** [comment]
Yes that's how I would have fixed it too. Great if you can take care on this point, I will wait for the PR then.

**Comment by Niols** [comment]
Even if I think that would be great to be able to modify the php files in templates, wouldn't that be too dangerous for the user? Because that would give a very important power to the theme writer…

**Comment by SUTJael** [comment]
Of course it would be great, but current code is not written and/or optimized for theming at all. That would require a really big review effort for all the templates files. At te moment, we're tending to a unique theme maybe with some minor customization like color, policies, effects, etc. allowed. So custom themes are not really the priority :)
As you certainly know, changing template files manually isn't the solution as you won't be able to update easily to a new version without overwritting your changes.

I invite you to check the "new-ui" branch I started few months ago related to the [following issue](https://github.com/ampache/ampache/issues/359#issuecomment-53078744). I'm still not available to continue working on Ampache right know but if you want to take a look you will see how I had to change template files and javascript scripts to make something working :)

**Comment by Niols** [comment]
OK @SUTJael I'll take a look at the new UI branch.
Is it a modification of the 3.7.0 release or of something earlier?
Should I close my PR and abandon the idea of theming?
Is there a way to help you in this new UI that seems to be very very promising?
Should I close this issue?

**Comment by SUTJael** [comment]
The last rebase I've done was from January 31, 2015. I will have to update everything but as you know there's been many improvements since so I'll certainly kill myself while merging everything :)
You can keep thinking about improving the theming part but only by playing with current css files and not by changing templates files. I don't know when the new interface will be out so I can't tell you if your work will be outdated in 2 months or more... There's a lot to do in the new UI but I do not have a todolist or precise ideas of what was remaining. The main purpose was to base my work on the Plex web interface (that you may know) which is the best from my side. If you can have a look and give me your feedbacks here. Thanks

**Comment by Afterster** [comment]
Yeah @SUTJael but as you said this is taking more time than excepted. Your new UI branch is here since one year soon. I would love to see it but during this time theming shouldn't be discouraged.

I believe #878 pull request is valid and has value, your opinion?

@Niols you can also take a look on themes in 3.7.0 release https://github.com/ampache/ampache/tree/048032f7c3c6aeb36d2b3e5cd1a9173ca92982f4/themes
Those was removed except Reborn theme to focus our work on this theme and because theme creator didn't updated it. Not because we didn't like it ;)

We will only provide **one** official Ampache theme (maybe in different colors) and will also include on releases updated themes maintained by its creator to work on latest release. If you liked previous themes I believe those can be bring back to 3.8.0 without much efforts. And if someone take responsability (on another git repo) for maintenance then it will be added by default again.

**Comment by Niols** [comment]
I actually agree with @SUTJael: allowing the modification of template files would make themes really hard to maintain. Plus I'm really not sure that the `allow_php_themes` option is efficient enough to prevent people from getting hacked by their themes (who reads the php code of a theme he wants to try?).

I really like the new UI preview. I didn't have time to install it and test it for now, sorry. I guess it'll be really hard to merge the new UI after one year full of commits. Maybe it would be worth it to start it again and try to do it fast? Or to try to merge develop into newUI now? Maybe it could be usefull for the future to use a template engine?

@Afterster I don't really like the old themes (but maybe “fresh”). I actually really like Reborn (I know there is a light version of Reborn, but how do you enable it?). I just wanted to do a minimalist theme that would be easier to use for people that just want to clic on music and listen to it, and that don't need/want to know all the powerful things Ampache is able to do. But maybe I could do it just with lots of `display: none;`.

**Comment by SUTJael** [comment]
A template engine would be awesome but we need an expert dev as we don't really use it with @Afterster. We thought about angularJS but it would require to rewrite everything :)
About merging, I will try to do that in coming days and keep you updated if you want to work on that branch.
The light version of Reborn has not been developed, there's just the black one. With the new UI, I started to separate colors/dispositions to be able to make a new color theme easily.

About the minimalist interface you thought, you can also activate the "Top Menu" and collapse the left menu as well. But like @Afterster said, you can also create a new one and enhance the theming management on develop ;)

**Comment by Niols** [comment]
I heard lots of good things about agularJS, and it seems to be very very good and cool, but I'm not really good with (and I absolutely don't like) JS, so I'm not the expert dev you seek.

I'll wait for you merging, and then discuss further with you to participate to this branch maybe? Because I really like what's happening on it and I would like to see this UI on Ampache, I think this would be great.

I don't have much time right now, but if I find it, I'll try to advance and to find a way to allow cool theming capabilities

**Comment by Afterster** [comment]
Ok, your PR was merged for now waiting for the legendary new UI (can I rename it Duke Nukem Forever theme? :grin:). I'm closing this then, please continue discussion on new UI dedicated issue. Thanks.
