### ISSUE TITLE
transcoded songs slow dl

### ISSUE THREAD

**Issue by cipriant** [ampache/ampache#882]
when i listen a transcoded song(ape/flac to mp3) via subsonic android over wifi; the download speed is very slow:  40 KB
how can I improve this speed? I must check some settings? 

if i listen a mp3 song the download is instant.

some infos about my server:
I use windows 8.1, xampp and a 3 Ghz quad core cpu with 8GB ram.

**Comment by Afterster** [comment]
Transcode takes time to process. Transcode on the fly will have limitate download speed because of the computation. Ampache doesn't add any additional limitation over it.
You can try to change transcode bitrate in Ampache settings or encode_args_mp3 setting in ampache.cfg.php to match better your needs ; but be aware this could have impact on audio quality.

**Comment by cipriant** [comment]
i canceled transcode and work great!
thanks

**Comment by cipriant** [comment]
one more question, web player can't play flac without transcode? :(

**Comment by Afterster** [comment]
If your browser doesn't support html5 flac stream (none) then the web player will not support flac without transcode, except using Javascript decoder Aurora.js if enabled in settings (requires Ampache version >= 3.8.0). Btw, for discussion please use the group instead https://groups.google.com/forum/#!forum/ampache
