### ISSUE TITLE
s3 compatible buckets as remote catalog

### ISSUE THREAD

**Issue by a7medo778** [ampache/ampache#885]
hi there
since we can use dropbox as a source for the catalog files, why not s3 buckets (and compatible storage solutions like openstack) ?
with a field for "cache size" for cacheing recent tracks, this will make ampache very very awesome and ssd cloud machines like linode, digitalocean and vultr will become a no brainer for load balacing nodes

this is a sugeestion
regards
ahmad

**Comment by a7medo778** [comment]
note: i did find a webdav module here in the repo, couldnt fine any documentation on how it work and where i can find it in the script though

if webdav is supported the task just got bit easier

**Comment by Afterster** [comment]
Amazon s3 remote catalog was already requested in #488 but better to have a separate issue for this as it is not small work.
Currently about webdav the support is about accessing Ampache using Webdav, not to use it as a remote catalog

**Comment by a7medo778** [comment]
oh ok
2 popular implementations that support 99% of the solutions out there is 
s3cmd : http://s3tools.org/s3cmd-sync
and s3fuse : https://github.com/s3fs-fuse/s3fs-fuse
both support wide range of operations specially cache which can be great thing 

you can littrally have unlimited storage for your media for fraction of the cost, s3 is cheap, and openstack solutions are even cheaper https://www.scaleway.com/pricing/

**Comment by Afterster** [comment]
In your case, why not using s3fuse to mount it on the system and add this mount path as a local catalog on Ampache?

**Comment by ainola** [comment]
Indeed, this seems like something that should be implemented from a separate utility.

Beware of feature creep, @Afterster. There are many things to work on for ampache and I don't feel that this is one of them. Logically speaking, you should have an ssh, webdav, samba, and afp backend for ampache if you're looking to implement s3 support.

**Comment by arnaudbey** [comment]
Dunno if it's really the role of ampache to handle all that types of external storage.

**Comment by ainola** [comment]
That was the purpose of my post...

**Comment by arnaudbey** [comment]
yep, my post was nothing more than a +1 :)

**Comment by ainola** [comment]
Apologies. I fully agree with you. I don't think any of this support should be in there, personally. I feel that the scope of Ampache should be thinned down and a clean and straightforward interface chiseled into perfection. "Drive-by" projects like this only hurt the overall goal of a project. Ampache's focus is to become a solid music and video player. Let it be that, and let other projects be good at what they do.

Personally, I feel that it is not in the realm of Ampache to provide features beyond the intended purpose of sorting, displaying, and playing music and videos. @afterster's definition likely varies but it is important that he uses his time to implement what he feels to be most beneficial to the vision of his project (since this is basically his project now due to the long running commit stream by him.)

Ampache needs a lot of work but it ultimately needs a focus more than anything else to put it on the path to success. 

Just my two cents. Thanks for all the great work you have put into this project, @afterster!

**Comment by Afterster** [comment]
Yeah I also agree.
Current catalogs list is enough. I would be happy to see new catalogs type as external projects maintained by someone (I would love to see more dedicated ampache plugin github repositories), or even PR, but this is clearly not a focus today. Not for me at least.
Many people asked for new features on Ampache and I created a lot of enhancement issue by myself too as I reminder for something that could be cool to have. GitHub removed priorities and votes years ago, but otherwise most of them would have been marked with low priorities ; some of them maybe fixed sooner just for the fun.
Bug fix remains the priority for sure.

**Comment by Afterster** [comment]
Time to focus sorry :smile_cat: .

If not mounted as a file system, this should be done as an external catalog plugin on Ampache and will not be available in base.
