### ISSUE TITLE
Album cover not showing in web player

### ISSUE THREAD

**Issue by stebe** [ampache/ampache#930]
I don't use the web player too often, today I noticed the album cover isn't showing up in the web player. Shows as a broken image or no image. Tried with MS Edge, Chrome and Firefox. Below is capture from edge.

![capture](https://cloud.githubusercontent.com/assets/4076671/9289086/fd600186-4331-11e5-8643-d6cc3500a84a.PNG)

**Comment by anonymous2ch** [comment]
Seems like a server configuration issue, try to open the image by a direct and see if that works...
![no error](https://cloud.githubusercontent.com/assets/11248668/9289260/95a63f88-4372-11e5-89a1-b6a37b087002.png)

**Comment by stebe** [comment]
The same image is showing in the Now Playing. I'll check the server settings.

**Comment by anonymous2ch** [comment]
It may also relate to thumbnail generation/unicode characters. [Try to run provided art thumbnail update scripts in the (in the ampache/bin)](https://github.com/ampache/ampache/tree/develop/bin) subfolder from your command line

**Comment by stebe** [comment]
I get a 404 when attempting to load directly (https://ca.animeshare.com/ampache/play/art/c7da94da0e1b66a65de8508b14dad795/album/30576/thumb3.jpg). The requested URL /ampache/play//thumb3.jpg was not found on this server. Might be the htaccess file is incorrect. Could the double / be an issue?

<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-s
    RewriteRule ^art/([^/]+)/([0-9]+)/thumb([0-9]*)\.([a-z]+)$ /ampache/image.php?id=$2&sid=$1 [L]
    RewriteRule ^([^/]+)/([^/]+)(/.*)?$ /ampache/play/$3?$1=$2 [N,QSA]
    RewriteRule ^(/[^/]+|[^/]+/|/?)$ /ampache/play/index.php [L,QSA]
</IfModule>
. 
root@juxta-linux:/home/steve/Music/ampache-metadata/album/30576# ls -l default/
total 72
-rw-r--r-- 1 www-data www-data  3656 Feb 21 10:36 art-100x100.jpg
-rw-r--r-- 1 www-data www-data  4816 May  9 07:33 art-128x128.jpg
-rw-r--r-- 1 www-data www-data 14506 Feb 17 20:28 art-275x275.jpg
-rw-r--r-- 1 www-data www-data  2765 May 21 22:04 art-80x80.jpg
-rw-r--r-- 1 www-data www-data 39555 Feb 17 20:28 art-original.jpg

**Comment by anonymous2ch** [comment]
Yes, that's prorbably the issue, cause it shows when accessed through the image.php script:
https://ca.animeshare.com/ampache/image.php?object_id=30576&object_type=album&auth=c7da94da0e1b66a65de8508b14dad795&thumb=3&name=art.jpg
![thumb](https://ca.animeshare.com/ampache/image.php?object_id=30576&object_type=album&auth=c7da94da0e1b66a65de8508b14dad795&thumb=3&name=art.jpg)

**Comment by anonymous2ch** [comment]
Seems like your .htaccess is from a different version of ampache, I think the rule should now look like:

RewriteRule ^art/([^/]+)/([^/]+)/([0-9]+)/thumb([0-9]).([a-z]+)$ /ampache/image.php?object_id=$3&object_type=$2&sid=$1 [L]

Try if that helps!

**Comment by stebe** [comment]
I see the .htaccess.dist was changed since the original .htaccess file I created a year ago.
Everything is working now, even when searching the thumbs are now showing there too.

Thanks for your help @anonymous2ch 

<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-s
    RewriteRule ^art/([^/]+)/([^/]+)/([0-9]+)/thumb([0-9]*)\.([a-z]+)$ /ampache/image.php?object_type=$2&object_id=$3&auth=$1&thumb=$4&name=art.jpg [L]
    RewriteRule ^([^/]+)/([^/]+)(/.*)?$ /ampache/play/$3?$1=$2 [N,QSA]
    RewriteRule ^(/[^/]+|[^/]+/|/?)$ /ampache/play/index.php [L,QSA]

**Comment by ufp32633** [comment]
Hmm, now I have the same problem. Thumbnails are broken in the search engine suggestions and in the webplayer. Clicking on the missing thumbnail in the search engine suggestions shows a page where the apparently not so broken picture does show up. Except for the thumbnails every other pic is showing up.
Thumbnails apparently need to be loaded from the /play folder. But that one is always empty.
I suspect a problem with .htaccess but since documentation is non existing about that topic (as is about any form of documentation in this project) I don't know how to solve it.

The 'public' address of my ampache is: http://localhost:8070/amp

**Comment by anonymous2ch** [comment]
Try setting the following values in your config file:

album_art_store_disk = "true"
local_metadata_dir = "/path/to/your/ampache/metadata" (don't forget to check read/write permissions for the metadata folder )

**Comment by Afterster** [comment]
I also believe it could be an htaccess issue. You're partially right about the documentation but htaccess was widely discussed several time on this issue tracker. You could search about it and see if others issues was related to yours ;)

**Comment by ufp32633** [comment]
Unfortunately that's not particularly helpful. I think the suggestions by @anonymous2ch do not apply as far as I can tell because those determine if album art is stored on disk instead of the database. I want it stored in the database and since regular album art is working those settings are apparently correct. Right after I installed Ampache for the first time the thumbnails did work so apparently I managed to break something and/or the .htaccess rules have changed during a subsequent update.

The comment of @Afterster is also not so helpful because I did a search and I only found this thread where an advice is given, which I followed too, then the asker apparently notices it works and does not tell what was changed. Well, in my case it still doesn't work.
I know there are references in the documentation but those handle about a few .htaccess files while there are more than those. And how about the portnumber. Should it be included in the rewrite rules?

B.T.W.: I'm a PHP programmer by profession so I know what's up and I must say you did a great job. Even tough the project does not comply to all the principles of 'Good Programming Practice' and even tough the code is a bit unstructured and there are a lot of dependencies to fulfill, still it is working. And yes: I know it is difficult to cope with complaining users    :-)
(I don't use rewrite rules in workprojects because I don't have to so far...)

**Comment by bambix** [comment]
Hi, I come to you with the same issue, but, i run on NGINX !
<img width="1677" alt="capture d ecran 2017-09-18 a 16 44 29" src="https://user-images.githubusercontent.com/1344115/30547842-c6585a16-9c90-11e7-9754-6defcc8806d0.png">

- I am using the configuration for NGINX found here : https://github.com/ampache/ampache/wiki/Installation#nginx
- In Administration -> Streaming -> Enable URL rewriting is Activated

If I hit the URL of the not found image : https://ampache.xxx.com/play/art/4a153bf27edb5f4097b4ba6ff8ae83b6/album/1032/thumb3.jpg, my browser automatically download a file named thumb3.jpg witch is corrupted.

If I set "error_log /var/log/ampache/error.log débug;" in my NGINX server config : I can read that URL REWRITE seems work fine : 
- 2017/09/18 16:52:59 [notice] 27918#0: *48 "^/play/art/([^/]+)/([^/]+)/([0-9]+)/thumb([0-9]*)\.([a-z]+)$" matches "/play/art/4a153bf27edb5f4097b4ba6ff8ae83b6/album/1032/thumb3.jpg", client: 80.12.59.206, server: ampache.guilhemostalier.com, request: "GET /play/art/4a153bf27edb5f4097b4ba6ff8ae83b6/album/1032/thumb3.jpg HTTP/1.1", host: "ampache.xxx.com"
- 2017/09/18 16:52:59 [notice] 27918#0: *48 rewritten data: "/image.php", args: "object_type=album&object_id=1032&auth=4a153bf27edb5f4097b4ba6ff8ae83b6", client: 80.12.59.206, server: ampache.guilhemostalier.com, request: "GET /play/art/4a153bf27edb5f4097b4ba6ff8ae83b6/album/1032/thumb3.jpg HTTP/1.1", host: "ampache.xxx.com"
- 2017/09/18 16:52:59 [debug] 27918#0: *48 http finalize request: 0, "/image.php?object_type=album&object_id=1032&auth=4a153bf27edb5f4097b4ba6ff8ae83b6" a:1, c:1

Then if I hit the final request URL : https://ampache.xxx.com/image.php?object_type=album&object_id=1032&auth=4a153bf27edb5f4097b4ba6ff8ae83b6
The album art is correctly displayed in the browser.

I Am here :( Any Idea ?

Thx in advance

**Comment by rponline** [comment]
Hi @bambix! 
I updated the nginx config in the wiki:
I replaced `; break;` with `last;` in the part regarding the artwork.
