### ISSUE TITLE
Video playback in webplayer

### ISSUE THREAD

**Issue by pavlo66** [ampache/ampache#942]
Ampache 3.8.0 installed on Ubuntu 15.04 LTS Apache2. Chrome browser
Almost all working fine.
but exist problem with video in web player. Message:
Unsupported
This media is not supported by the player. Is your browser up to date?

stream player and video file download is working fine

can you help?

**Comment by Afterster** [comment]
That simply means your browser doesn't support it. For video streaming on web player your browser should support the file format.
Only HTML5 tech is supported for video (no flash, etc...).

**Comment by pavlo66** [comment]
did you mean Google chrome last version does not support html5?

**Comment by pavlo66** [comment]
try to play mkv and avi

**Comment by Afterster** [comment]
Mkv and avi are generally not supported by html5 indeed.

**Comment by pavlo66** [comment]
ok. need to setup transcode to supported format such as webm or mp4?

**Comment by Afterster** [comment]
If you want to stream on your browser, yes.

**Comment by pavlo66** [comment]
how i can setup transcode on-the-fly without waiting while transcode will be finished?

**Comment by Afterster** [comment]
Should be the case. It could come from your web server output buffering configuration or more likely from your transcode settings. I believe you tried with mp4 which could result of this behavior because of MOOV ATOM set at the end of the file, see https://creativcoders.wordpress.com/2014/12/12/stream-live-mp4-video-with-ffmpeg-while-encoding/
