### ISSUE TITLE
Data structures undocumented?

### ISSUE THREAD

**Issue by OctalMan** [ampache/ampache#944]
I cannot find the charts/diagrams/maps for your data structure.
I am running one directory with V 3.8.0 and one with the develop branch. 
The album side is working fine.
I need to get the TV Show portion working.
I own a variety of series and want them online for my family.

Without further information, the only option I see is:

ALTER TABLE tvshow_episode ADD COLUMN video INT(11) UNSIGNED;
This gives a PRIMARY KEY path for table video.

Possibly include:
ALTER TABLE tvshow_episode CHANGE id id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT;
AUTO_INCREMENT cuts work load 
   and maintains the pattern found in other tables.
Though a PRIMARY KEY IS NOT NULL implicitly, 
   it prevents MySQL from displaying NULL as the default value.

OctalMan

**Comment by Afterster** [comment]
There is no diagram that's why you cannot find it :)

Mhh you're not saying what is your issue here? You get entries inside tvshow_episode table with id set to NULL? If that's the case, please enable Ampache logs and post it here.
About your suggested changes, id in tvshow_episode shouldn't be autoincrement as it must match the associated video id.

**Comment by wagnered** [comment]
@octalman,

 I think your problem is because the existing parsing logic does a poor
job of extracting tvshow information and will result in a tvshow table
entry with id number but null everything else.

I am working on the parsing problem.

How are you you naming the tvshow files? If you are using the folder
path, could you give me an example.

I am also working on grabbing the metadata for storage in the database
from The Movie db (Tmdb) and The Tv db (Tvdb).

Right now I am working on a PR that partly implements the Kodi (xmbc)
naming conventions: http://kodi.wiki/view/Naming_video_files/TV_shows.

I will be using folder logic for the simple directory format (sec 1.1) only.

For file naming logic, I am using section 2.1 Single episode (With
season) for naming the tv show files.

-- 
73 From
Ernie D
Federal Way, WA | CN87ug

**Comment by OctalMan** [comment]
Directory structure:
"C:\Web_Services\Data\ampache\TV_Series\Hart To Hart\1\0_Pilot_Special.MP4"
C:\Web_Services\Data\ampache\TV_Series\[Series Name]\[Season]\[Episode Number]_[Title]

If Add Catalog asked for type first the table of items could be adjusted so the variables for rename_pattern and sort_pattern were specific to the type of catalog.

**Comment by wagnered** [comment]
It does, it asks what media type to gather.  If by type you mean
something else, then I'll leave this for @afterster to respond to.

Thank you for the info on your file path structure.

Actually, I'm not sure I understand your question.  If it is for a new
feature, you can suggest it to @afterster in a separate issue.

On 09/03/2015 12:02 PM, OctalMan wrote:
> Directory structure:
> "C:\Web_Services\Data\ampache\TV_Series\Hart To Hart\1\0_Pilot_Special.MP4"
> C:\Web_Services\Data\ampache\TV_Series[Series Name][Season][Episode
> Number]_[Title]
> 
> If Add Catalog asked for type first the table of items could be adjusted
> so the variables for rename_pattern and sort_pattern were specific to
> the type of catalog.
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ampache/ampache/issues/944#issuecomment-137543251>.
> 

-- 
73 From
Ernie D
Federal Way, WA | CN87ug

**Comment by OctalMan** [comment]
Gather media types is just before the path.  Your options for data collection are limited to:
Auto-inserted Fields:
%A = album name
%a = artist name
%c = id3 comment
%T = track number (padded with leading 0)
%t = song title
%y = year
%o = other

Which doesn't tell you much about how to parse a TV Show.
If it asked for the Media types first this table could change to suite the media.

**Comment by wagnered** [comment]
Oh yea, you are referring to Filename, Folder Pattern: Ampache
originally was a music only media server, and only relatively recently
was videos of various media types added. Again, make a suggestion and
get feedback from @Afterster.

Actually, in my opinion, the standard seems to be Kodi specs. And
because the video logic is not yet without significant bugs they have
have priority 0ver developing complex search algorithms, which can be
time consuming. .

On 09/03/2015 12:42 PM, OctalMan wrote:
> Gather media types is just before the path. Your options for data
> collection are limited to:
> Auto-inserted Fields:
> %A = album name
> %a = artist name
> %c = id3 comment
> %T = track number (padded with leading 0)
> %t = song title
> %y = year
> %o = other
> 
> Which doesn't tell you much about how to parse a TV Show.
> If it asked for the Media types first this table could change to suite
> the media.
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ampache/ampache/issues/944#issuecomment-137554004>.
> 

-- 
73 From
Ernie D
Federal Way, WA | CN87ug

**Comment by OctalMan** [comment]
Understandable.  The current release is missing:
/templates/show_partial_video.inc.php (not that that is news)  and that is how I ended up installing a develop branch.  I agree this is a nicety.  Now that I know the id in tvshow_episode is the id for the table video,   I can get around if I edit tables by hand where needed. I say lets close this.  Thank you for the info.  

P.S.  I always hated documenting data structures, so I wasn't surprised there is no documentation..
