### ISSUE TITLE
test.php isn't translated

### ISSUE THREAD

**Issue by Psy-Virus** [ampache/ampache#955]
Hey ho,
as the title says it, `test.php` isn't translated but the default language is set to German in my case.

And there's a small glitch on the top left.
Are these `bootstrap*.css` automatically generated? Because the formatting looks ugly or .. isn't .. existing. (O.o)
didn't work with it before..

Screeny:

![ampache -- debug page 2015-09-17 04-04-02](https://cloud.githubusercontent.com/assets/6222200/9923136/59234400-5cf1-11e5-815e-6e71b9542f34.png)

Thanks in advance :-)

**Comment by Afterster** [comment]
Language is related to the user session then test.php cannot be translated as it should be minimalist to not fail (chances are you're going to this page because of an issue, it shouldn't do additional stuffs).
About the header css issue, this is related to move to Composer and a wrong modification on bootstrap base css that should have been done somewhere else. I'm gonna fix it.

**Comment by Afterster** [comment]
Fixed installation header css with 2f00d06a98d16515d5c9b8d03ce6a281baf231b1.

**Comment by Psy-Virus** [comment]
Well, before you login you also have no user session but the login screen is translated ;-)

**Comment by Psy-Virus** [comment]
Well, before you login you also have no user session but the login screen is translated, am I wrong?

And if we wont translate it, then we should consider rewrite the source, so that it isn't gathered for translation.

But my opinion is, that we should translate everything what could be readable by users.

**Comment by Psy-Virus** [comment]
In my eyes it's a part of a quality product. Except those things like the bins who are executed via console.

**Comment by Psy-Virus** [comment]
Oh and we have the global language setting what sets the lang for the login screen for example... isn't it possible to do it the same way for the test.php? Also because of the fact that we already have the translations for it. And if I remember right, It was translated in the past....

**Comment by Afterster** [comment]
Liar :).
I think you mix-up some pages, the test table is translated at installation time because the user explicitly selected the language on the previous page but it never was in my knowledge on the independent test.php file.
There is a difference with login page ; on test.php we don't want to have any database connection to keep the test page simple whereas the login page is connecting to the database to retrieve the default language.
But maybe we could save the language inside a cookie and reuse it here, or something like that.

**Comment by Psy-Virus** [comment]
Oh yes sure, the db connection (facepalm). :D
Okay, then it wasn't translated in the past ^^
Haven't thought about it... And yes, maybe I've mixed it up :D

Anyway, the cookie method sounds relatively good, but maybe handle it via the config file instead of the db is a better option, because it's a global setting like the db account & password or the web path. It is set only one time and shouldn't depend on other things. (?)
That's only my opinion and I like it if things are as user friendly as they can be as long as it does not result in more work for the user.

:-)

**Comment by Phyks** [comment]
@Psy-Virus I implemented the cookie solution in [this commit](https://github.com/Phyks/ampache/commit/802ee76bd52131988dd7dbc9e1fececce2ed64dc) on my fork.

I set up a cookie when opening a session, with the current lang in use. It is destroyed at the end of the user session (not sure if this is necessary or if we want to keep it any longer?).

@Afterster to implement the cookie, I used the `session_name` parameter as was already done for the rest of the cookies. Then, I had to load the config in the `test.php` page. I took care to only load the config if it is valid, and redirect to `?action=config` otherwise. Not sure if it is a good thing, or if I should simply name the cookie `lang` and drop any dependency on the config?

I will open a PR to discuss this more in details.
