### ISSUE TITLE
Composer is telling me guzzle packages are abandoned and I should not use them.

### ISSUE THREAD

**Issue by apastuszak** [ampache/ampache#957]
```
Package guzzle/common is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/stream is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/parser is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/http is abandoned, you should avoid using it. Use guzzle/guzzle instead.
```

**Comment by wagnered** [comment]
Actually, Guzzle/Guzzle has been deprecated and now Guzzlehttp/Guzzle
should be used and can be installed from https://packagist.org/.

One problem is that all the dependent packages will be installed whether
they are needed by Ampache or not. The other problem is that possibly
some Ampache code needs to be adjusted to access the classes in those
packages. or the proper autoloader needs to be used to correctly find
the classes in the new packages.

It's been so long since the modules in Ampache have been updated that
many of the modules have been combined with others and are not backward
compatible.

I tried updating Tmdb package and found out that without the proper auto
loader, Ampache code had to be  modified and the Tmdb modules had to be
reorganized to accomodate them into Ampache.  I did not finish that
update (:' >

On 09/17/2015 10:51 AM, apastuszak wrote:
> |Package guzzle/common is abandoned, you should avoid using it. Use
> guzzle/guzzle instead. Package guzzle/stream is abandoned, you should
> avoid using it. Use guzzle/guzzle instead. Package guzzle/parser is
> abandoned, you should avoid using it. Use guzzle/guzzle instead. Package
> guzzle/http is abandoned, you should avoid using it. Use guzzle/guzzle
> instead. |
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ampache/ampache/issues/957>.
> 

-- 
73 From
Ernie D
Federal Way, WA | CN87ug

**Comment by Afterster** [comment]
Yeah Guzzle/Guzzle is here because of dependencies of dependencies. MusicBrainz library dependency we're using depends of it for instance, see https://github.com/mikealmond/MusicBrainz project. I think I will PR on this project to move to GuzzleHttp when I have some times.
We already also depends of GuzzleHttp btw @wagnered, both are installed by Composer since I updated the dependencies.
Using Composer did some cleanup and the only dependencies not really maintained anymore are those remaining on Ampache git repository under /modules folder.
Almost every dependency is loaded through Composer autoloader, and I believe Tmdb will be autoloaded without issue now @wagnered.

**Comment by Phyks** [comment]
The following packages depend on old version of `guzzle`:

* https://github.com/mikealmond/MusicBrainz
* https://github.com/ratchetphp/Ratchet

I'll see what we can do about this.

**Comment by bowlofeggs** [comment]
I am working on packaging Ampache for Fedora, and these abandoned projects may be difficult to get through package review.

**Comment by bowlofeggs** [comment]
Here is a Ratchet issue about this: https://github.com/ratchetphp/Ratchet/issues/288

**Comment by alice-0-kim** [comment]
Has it been any progress on this? I have `"guzzlehttp/guzzle" : "^6.0@dev"` in composer.json file and the same suggestion message appears.

**Comment by wagnered** [comment]
@alice-0-kim 

Remember, it is only a suggestion that the "mikealmond/MusicBrainz" package gives. Guzzle/Guzzle is only necessary if composer is put into the development mode.   guzzlehttp/guzzle is the replacement for guzzle/guzzle which has been abandoned, but it's not a diirect replacement.

**Comment by wagnered** [comment]
As ratchetphp/Ratchet has changed to guzzlehttp/guzzle, and mikealmond/MusicBrainz doesn't actually require it for production use, I am closing this issue.
