### ISSUE TITLE
Catalog Import - Wrong Artist name

### ISSUE THREAD

**Issue by Jeffsninja** [ampache/ampache#968]
So I've just got round to configuring my Ampache and add my catalog of about 30,000 songs. However I have some problems importing the catalog,

Firstly it is not finding all the files, I only end up with 17,000 songs in Ampache,

Secondly when I do import it randomly decided to change the artist name. When I import the whole catalog it puts 5000 songs into the artist "3 Colours Red", however if I try and import seperate catalogs for A-C, D-F etc, it uses Daft Punk to group them into. 

Does anyone know why these two might occur?

**Comment by Psy-Virus** [comment]
Hey @Jeffsninja,

the first ideas that came around by reading your post are:

> Firstly it is not finding all the files, I only end up with 17,000 songs in Ampache,

+ Are the read write permissions right? Please make sure you have recursively set the right permissions for your music directories, so Ampache can read the files.

+ Did you change the `catalog_file_pattern = "mp3|mpc|m4p|m4a|aac|ogg|oga|wav|aif|aiff|rm|wma|asf|flac|opus|spx|ra|ape|shn|wv"` option whithin the config file?

> Secondly when I do import it randomly decided to change the artist name. When I import the whole catalog it puts 5000 songs into the artist "3 Colours Red", however if I try and import seperate catalogs for A-C, D-F etc, it uses Daft Punk to group them into.

+ This sounds like you have some cross linking within your directory structure. Please make sure you do not have any symbolic links from one directory to another or tell your web server to not use them.

+ are some songs AND it's paths added twice?

If this does not help, could you please provide more details for your problem and also for your setup?
Like used OS, Webserver, PHP version, and so on.

:-)

**Comment by Jeffsninja** [comment]
Ah yes some more details would be a good idea,

This is running on a -

Windows 2012 R2
IIS 8.5
PHP version 5.6.0
MySQL 5.5

Changing the permissions was the solution to the first issue, what I hadn't added was the network services and iuser to access the folder. Thank you for pointing me in the right direction there, I should have really realised as I had to do that on owncloud as well!


As for the second issue, -

![example](https://cloud.githubusercontent.com/assets/13257877/10070460/85e137c2-62aa-11e5-8e33-4b45513ac2c8.PNG)

![database](https://cloud.githubusercontent.com/assets/13257877/10070464/894a9ade-62aa-11e5-9aef-31a73ba20842.PNG)

It seems when I used Musicbrainz to sort my music it has put the mbid values as a random value? And therefore relabel it as 3 Colours red?!?

**Comment by Psy-Virus** [comment]
> Changing the permissions was the solution to the first issue, what I hadn't added was the network services and iuser to access the folder. Thank you for pointing me in the right direction there, I should have really realised as I had to do that on owncloud as well!

Hehe, it's like forgetting the power cord after building a PC and wondering that it doesn't start after pressing the button, a common brainlag :D But anyway, I'm glad that I could help you :-)

> It seems when I used Musicbrainz to sort my music it has put the mbid values as a random value? And therefore relabel it as 3 Colours red?!? 

Well, as I started using MusicBrainz, I also trust that it will do the most work for me. But nope... luckily I made a Backup before. The result after the first tagging attempt with MB was that ~10% of my music (~10k of ~100k titles) was false tagged,- false artist, false album, false title and sometimes false playtime.
MB is a great tool, but you also have to review every changes it makes, otherwise it can render your tags as unusable.

The acoustIDs seem also to be relatively inaccurate 'cause I had some songs of ~3 min that where tagged as radio plays of ~30 min.

I hope you made a Backup before, otherwise I wish you a lot of fun by re tagging your mistagged files... ^^
BTW: MP3Tag is a great tool for manual tagging your files and with [> this <](https://onedrive.live.com/redir?resid=21D33DA1CDEFAEB0!4658&authkey=!ALVTCZPU3bXce98&ithint=file%2crar) Plugin you will also see the complete tags, what's quite useful. (Pls. write back if you don't need the Plugin or if you downloaded it, because I shared it over onedrive, because the main website isn't accessible at the moment)

So as this doesn't seem to be an Ampache issue, and if your issues related to Ampache are "fixed", please don't forget to close this issue ;-)

**Comment by Jeffsninja** [comment]
Thanks for the help,

Ah unfortunately I don't have a proper back up of it all, mind you it was in a pretty bad organisational state beforehand, just means a bit more work to do that,

Downloaded the file thanks,

**Comment by Jeffsninja** [comment]
Thanks PSY for the help, I used MP3 Tag, and applied the filter "brainz" at the bottom of the program (as when it couldn't find musicbrainz info it just put "muiscbrainz" in the tag, sometimes missing off the first few letters weirdly, hence searching for "brainz") and it brought up 6000 odd songs.

Select all songs then and right-click to open extended tags, then find the musicbrainz tags and remove the field. Clears all the music brainz info!


Thanks again, now just for sorting out transcoding! *sigh*
