### ISSUE TITLE
[Enhancement] Changing the labels for input fields -> placeholders? And theme question

### ISSUE THREAD

**Issue by Psy-Virus** [ampache/ampache#999]
Hey ho!
As the title says, I think we should change the labels for the most input fields into placeholders.
Maybe optional via the config file? (I would do it)

It looks more modern and at least for my theme it would look much better. (my thought)

And is it possible to make a repository or a branch for themes?
So that themes are linked to the Author repositories and can be downloaded from here (like a hardlink).

So that the branch *themes* will look like this:
```text
|-themes
    |
    |-v3.0
    .   |-author1
    .   .   |-theme1
    .   .   |-theme2
    .   |-author2
    |-v3.1
```
So no one needs write access to this branch but everyone can work on their themes and update them on their own repos.

Or we need something like a Dropbox, owncloud, what ever, where anyone administrates the themes (shared folders with per user permissions) and the share link of the themes directory would be posted on the main page of Ampache and on the README.md.
I have a Dropbox and OneDrive Account. Both are not really used.

I also would prefer OneDrive, because the UI is muuuch better and you can work on it like on any other desktop. Drag and drop, mark files by "square lasso marking" with the mouse.. like on your desktop.. with this LMB square. O.o... and right click and so on. It also has a good text editor to directly work on the files with great syntax highlighting, version control and so on.
Sorry if I sound like a PR guy, but it's really not that bad^^

Here you can test it on a share from me with my currently used theme (read only): https://onedrive.live.com/redir?resid=21D33DA1CDEFAEB0!4846&authkey=!AI1CRhXUGfcGWrU&ithint=folder%2c

EDIT: And a preview of the theme^^

![preview](https://cloud.githubusercontent.com/assets/6222200/10866476/efb7d744-802f-11e5-8138-cbe27d1ce4e0.png)

**Comment by Psy-Virus** [comment]
:beers: for all for the 999th issue :tada:

**Comment by a7medo778** [comment]
i think themes needs a major change, going to responsive design is much better and functional

maybe linking with of the many music templates at themeforest

**Comment by Afterster** [comment]
@a7medo778 going responsive is another issue as you know. Please keep this discussion on #359 :).

@Psy-Virus using placeholder was originally discussed to add additional information on input field. For me placeholder is not a substitute for labels. And technically it is also the case, see the following stackoverflow discussion : http://stackoverflow.com/questions/9157867/placeholder-vs-label-for-input-in-html5
About theme repository, yes new themes should be maintained on a separate repository. Please forget about the proprietary solutions, we're doing git only here :). But we should not link Ampache repository to external themes repo (using git modules for instance) neither because we cannot be sure external themes will always be up to date to match latest changes. Better to reference all themes on the wiki.
